import {useState,useMemo,useCallback}from'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import {DPTable}from '../../components/shared'
import FloatingPanel from '../../components/shared/FloatingPanel'
import {usePlaybackState}from '../../hooks/usePlaybackState'
import {useCodeVisualConnectivity}from '../../hooks/useCodeVisualConnectivity'
import {getExamplesOr}from '../../config/examplesRegistry'
import {createPortal}from'react-dom'
import './SparseMatrixMultiplicationVisualizer.css'
const CODE=[{line:1,text:'def multiply(mat1, mat2):'},{line:2,text:'    result = [[0] * len(mat2[0]) for _ in mat1]'},{line:3,text:'    for r in range(len(mat1)):'},{line:4,text:'        for k, value in enumerate(mat1[r]):'},{line:5,text:'            if value == 0: continue'},{line:6,text:'            for c in range(len(mat2[0])):'},{line:7,text:'                if mat2[k][c] != 0:'},{line:8,text:'                    result[r][c] += value * mat2[k][c]'},{line:9,text:'    return result'}]
function trace({mat1,mat2}){const R=mat1.length,C=mat2[0].length,result=Array.from({length:R},()=>Array(C).fill(0)),out=[{phase:'init',activeLine:2,message:'Initialize the result matrix with zeroes.',result:result.map(r=>[...r]),active:null}];for(let r=0;r<R;r++)for(let k=0;k<mat2.length;k++){const v=mat1[r][k];if(v===0){out.push({phase:'process',activeLine:5,message:`A[${r}][${k}] is zero, so sparse multiplication skips this row contribution.`,result:result.map(x=>[...x]),active:{row:r,column:0},a:{r,k}});continue}for(let c=0;c<C;c++)if(mat2[k][c]!==0){const add=v*mat2[k][c];result[r][c]+=add;out.push({phase:'process',activeLine:8,message:`A[${r}][${k}] × B[${k}][${c}] = ${v} × ${mat2[k][c]} adds ${add}.`,result:result.map(x=>[...x]),active:{row:r,column:c},a:{r,k},b:{k,c}})}}out.push({phase:'done',activeLine:9,message:'The accumulated cells form the product matrix.',result,active:null});return out}
const EXAMPLES=getExamplesOr('sparse-matrix-multiplication',[{label:'Sparse product',mat1:[[1,0,0],[-1,0,3]],mat2:[[7,0,0],[0,0,0],[0,0,1]]}])
function parse(raw){try{const x=JSON.parse(raw),rect=a=>Array.isArray(a)&&a.length&&a.every(r=>Array.isArray(r)&&r.length===a[0].length&&r.every(Number.isFinite));if(!rect(x.mat1)||!rect(x.mat2)||x.mat1[0].length!==x.mat2.length)throw Error('Use compatible rectangular numeric mat1 and mat2.');return{input:x,inputError:''}}catch(e){return{input:null,inputError:e.message}}}
export default function SparseMatrixMultiplicationVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?trace(input).map(s=>({...s,relatedLines:[s.activeLine]})):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'viz',title:'Sparse product',dockMode:'split-right'},{id:'examples',title:'Examples',dockMode:'split-bottom'}],[]);const contents={input:<div className="sparse-matrix-multiplication-panel"><div className="sparse-matrix-multiplication-panel-body"><textarea className="sparse-matrix-multiplication-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,viz:!input?<div className="sparse-matrix-multiplication-error">{inputError}</div>:<div className="sparse-matrix-multiplication-panel"><div className="sparse-matrix-multiplication-panel-body"><div className="sparse-matrix-multiplication-step-info"><h3>{step?.message||'Press play to multiply non-zero cells.'}</h3></div><DPTable title="Result" values={step?.result||[[0]]} activeCell={step?.active}/></div></div>,examples:<div className="sparse-matrix-multiplication-panel"><div className="sparse-matrix-multiplication-panel-body sparse-matrix-multiplication-examples">{EXAMPLES.map((x,i)=><button className="sparse-matrix-multiplication-example-btn" key={i} onClick={()=>apply(x)}>{x.label||`Example ${i+1}`}</button>)}</div></div>};return <div className="sparse-matrix-multiplication-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
