import { advanceCases } from './expansionAdvanceExamples.js';
import { progressCases } from './expansionProgressExamples.js';
import { continuingCases } from './expansionNextExamples.js';
import { nextCollectionCases } from './nextCollectionExamples.js';
import { expansionCollectionCases } from './expansionCollectionExamples.js';
import { dpCases } from './expansionDPExamples.js';
import { moreCases } from './expansionMoreExamples.js';
import { laterCases } from './expansionLaterExamples.js';
const rookBoard=(pieces)=>{const board=Array.from({length:8},()=>Array(8).fill('.'));for(const[r,c,v]of pieces)board[r][c]=v;return board;};
// Independently authored walkthroughs and named decision boundaries.
const cases={
  ...nextCollectionCases,
  ...expansionCollectionCases,
  ...dpCases,
  ...moreCases,
  ...laterCases,
  ...continuingCases,
  ...progressCases,
  ...advanceCases,
  860:[['Conserve fives across several customers',{bills:[5,5,10,5,20,5,10,5,5,20]}],['First customer needs unavailable change',{bills:[10]}],['Three fives make change',{bills:[5,5,5,20]}],['Too few fives after earlier sale',{bills:[5,10,20]}]],
  861:[['Rows and columns prefer different flips',{grid:[[0,1,0,1,1],[1,0,1,0,0],[0,0,1,1,0],[1,1,0,0,1]]}],['Single zero bit',{grid:[[0]]}],['Already maximal',{grid:[[1,1,1],[1,1,1]]}],['Column tie needs no flip',{grid:[[1,0],[1,1]]}]],
  868:[['Several unequal zero gaps',{n:1161}],['Only one set bit',{n:128}],['All bits set',{n:127}],['Two widely separated bits',{n:513}]],
  869:[['Digits reorder into a large power',{n:8402}],['Repeated digits cannot form a power',{n:333}],['Already a power',{n:16384}],['Leading-zero rearrangement is not enough',{n:100}]],
  881:[['Pairing decisions near the weight limit',{people:[7,3,9,4,6,2,8,5,1,6],limit:10}],['Every person rides alone',{people:[7,8,9],limit:10}],['Exact weight pairs',{people:[3,7,4,6],limit:10}],['Single passenger',{people:[8],limit:8}]],
  883:[['Different silhouettes along each axis',{grid:[[2,0,4,1],[3,5,1,0],[0,2,6,3],[4,1,0,2]]}],['All empty',{grid:[[0,0],[0,0]]}],['Single tower',{grid:[[7]]}],['Equal heights',{grid:[[3,3],[3,3]]}]],
  884:[['Duplicates within and across sentences',{s1:'cedar leaves drift past quiet cedar paths',s2:'quiet streams carry leaves toward distant fields'}],['Same repeated word',{s1:'moss moss',s2:'moss'}],['Disjoint short sentences',{s1:'red fox',s2:'blue bird'}],['Repeated only within one sentence',{s1:'pine pine birch',s2:'oak'}]],
  888:[['Find a balancing exchange among several sizes',{aliceSizes:[4,8,6,10,2],bobSizes:[3,7,5,9]}],['Equal totals allow equal exchange',{aliceSizes:[3,7],bobSizes:[7,3]}],['Only one box each',{aliceSizes:[8],bobSizes:[8]}],['Repeated box sizes',{aliceSizes:[2,2,6],bobSizes:[4,4,6]}]],
  890:[['Several words share letters but not structure',{words:['deed','noon','door','peep','book','elle','moss'],pattern:'abba'}],['All positions distinct',{words:['sun','sky','see','owl'],pattern:'abc'}],['Repeated single letter',{words:['aaa','bbb','aba'],pattern:'ccc'}],['One-character words',{words:['x','y','z'],pattern:'q'}]],
  892:[['Shared faces disappear across adjacent towers',{grid:[[2,1,0,3],[1,4,2,0],[0,2,3,1],[3,0,1,2]]}],['One cube',{grid:[[1]]}],['Two equal adjacent towers',{grid:[[2,2],[0,0]]}],['Empty surface',{grid:[[0]]}]],
  893:[['Words share parity-specific signatures',{words:['abcd','cbad','adcb','cdab','abdc','badc']}],['One-letter groups',{words:['a','b','a','c']}],['Repeated identical words',{words:['moss','moss']}],['Same multiset different parity',{words:['ab','ba']}]],
  898:[['Suffix OR states merge repeatedly',{arr:[1,4,2,8,3,5,0,12,6]}],['Only zeros',{arr:[0,0,0]}],['Equal values',{arr:[7,7,7]}],['Disjoint bit powers',{arr:[2,8,32]}]],
  899:[['One choice restricts us to rotations',{s:'gardenpath',k:1}],['Two choices permit full sorting',{s:'cedarmoss',k:2}],['All letters equal',{s:'zzzzz',k:1}],['A rotation already begins smallest',{s:'abcde',k:1}]],
  901:[['Stock spans absorb several earlier blocks',{prices:[47,31,35,29,42,42,38,55,49,61]}],['Strictly decreasing prices',{prices:[90,70,50,30]}],['Equal prices all join',{prices:[18,18,18,18]}],['Single quote',{prices:[73]}]],
  904:[['Third fruit type repeatedly shrinks the window',{fruits:[4,7,4,4,9,7,9,9,7,2,2,9]}],['One type only',{fruits:[6,6,6,6]}],['Every fruit type differs',{fruits:[2,4,6,8]}],['Exactly two types',{fruits:[3,5,3,5,5,3]}]],
  908:[['Extreme values determine residual range',{nums:[3,17,8,22,11,6,19,14],k:5}],['Reachable intervals overlap',{nums:[8,12,10],k:3}],['No adjustment allowed',{nums:[4,16,7],k:0}],['Single value',{nums:[9],k:7}]],
  914:[['Different frequencies share a common divisor',{deck:[4,4,7,7,7,7,9,9,9,9,9,9]}],['Coprime frequencies',{deck:[2,2,3,3,3]}],['All cards identical',{deck:[8,8,8,8]}],['Singleton deck',{deck:[6]}]],
  915:[['Left boundary must expand more than once',{nums:[6,2,4,7,3,8,9,11,10]}],['Shortest prefix is one element',{nums:[1,3,4,6]}],['Equal values permit earliest cut',{nums:[5,5,5,5]}],['Smallest valid split',{nums:[2,7]}]],
  917:[['Punctuation stays while letters reverse',{s:'ab-Cd!ef?Gh-ij'}],['No letters',{s:'1234--!?'}],['Only letters',{s:'garden'}],['Letters only at boundaries',{s:'A-123-z'}]],
  918:[['Best interval wraps around both ends',{nums:[8,-3,4,-9,6,7,-2,5]}],['All negative',{nums:[-8,-3,-6,-4]}],['Whole array is best',{nums:[2,5,3,7]}],['Single value',{nums:[-9]}]],
  921:[['Both unmatched opening and closing groups',{s:'))(()))((()('}],['Already balanced',{s:'(()())()'}],['Only openers',{s:'(((('}],['Only closers',{s:')))))'}]],
  925:[['Repeated presses at several positions',{name:'marigold',typed:'mmaariiggolldd'}],['Missing final letter',{name:'cedar',typed:'cceedaa'}],['Unexpected character',{name:'moss',typed:'moossx'}],['Identical input',{name:'fern',typed:'fern'}]],
  926:[['Several competing split boundaries',{s:'110010110001011'}],['Already monotone',{s:'0001111'}],['All zeros',{s:'00000'}],['One descent',{s:'111000'}]],
  929:[['Local aliases collapse while domains remain distinct',{emails:['red.fox+garden@woods.org','redfox@woods.org','redfox+pond@woods.net','blue.bird@woods.org','bluebird+note@woods.org']}],['Dots in domains remain significant',{emails:['ab@a.bc','ab@ab.c']}],['Plus suffix is ignored only locally',{emails:['pine+one@forest.org','pine+two@forest.org']}],['One ordinary address',{emails:['moss@green.org']}]],
  930:[['Zero runs create repeated prefix sums',{nums:[1,0,0,1,0,1,1,0,0,1],goal:2}],['All zeros and zero target',{nums:[0,0,0,0],goal:0}],['Target is unreachable',{nums:[0,1,0],goal:3}],['One matching bit',{nums:[1],goal:1}]],
  931:[['Negative cells change the cheapest path',{matrix:[[7,-3,8,4],[6,5,-9,2],[-4,7,3,-6],[9,-2,1,5]]}],['Single cell',{matrix:[[-8]]}],['Equal costs',{matrix:[[4,4],[4,4]]}],['Boundary path wins',{matrix:[[1,8,9],[2,7,8],[3,6,9]]}]],
  933:[['Calls on both sides of the inclusive time boundary',{times:[100,850,1600,3100,3101,4200,6100,7200]}],['Exact boundary stays',{times:[5,3005]}],['Large gaps remove every prior call',{times:[1,4002,8003]}],['One call',{times:[19]}]],
  941:[['Strict climb then descent',{arr:[1,4,8,13,19,16,11,7,3]}],['Plateau at summit',{arr:[2,5,9,9,4]}],['Only ascending',{arr:[1,4,7]}],['Multiple peaks',{arr:[1,6,3,7,2]}]],
  942:[['Alternating and repeated inequalities',{s:'IIDDDIDIID'}],['Only increases',{s:'IIII'}],['Only decreases',{s:'DDDDD'}],['One relation',{s:'D'}]],
  944:[['Independent sorted and descending columns',{strs:['acmpt','bdlqu','cekrv','dfjsw']}],['All columns sorted',{strs:['abc','bcd','cde']}],['Only one row',{strs:['zyxw']}],['Equal characters are allowed',{strs:['aa','aa','aa']}]],
  945:[['Repeated values collide with later originals',{nums:[6,2,6,3,2,7,3,8,6,1]}],['Already unique',{nums:[2,5,8,11]}],['All equal',{nums:[4,4,4,4]}],['Single zero',{nums:[0]}]],
  946:[['Several pushes precede valid pops',{pushed:[8,3,11,5,14,2],popped:[11,5,3,2,14,8]}],['Impossible middle pop',{pushed:[4,7,9],popped:[9,4,7]}],['Immediate pops',{pushed:[2,6,8],popped:[2,6,8]}],['One element',{pushed:[13],popped:[13]}]],
  948:[['Buying cheap tokens and selling an expensive one',{tokens:[70,180,40,260,110,330,90],power:130}],['Cannot buy any token',{tokens:[80,120],power:20}],['Can buy them all',{tokens:[20,30,40],power:100}],['Single affordable token',{tokens:[55],power:55}]],
  950:[['Reveal queue wraps around several times',{deck:[19,4,31,8,23,12,41,6,17]}],['Two cards',{deck:[9,3]}],['One card',{deck:[27]}],['Initially increasing deck',{deck:[2,5,8,11,14]}]],
  953:[['Custom alphabet changes first differences',{words:['zoo','yak','xenon','wood'],order:'zyxwvutsrqponmlkjihgfedcba'}],['Longer shared prefix is invalid first',{words:['garden','gard'],order:'abcdefghijklmnopqrstuvwxyz'}],['Shorter shared prefix comes first',{words:['oak','oaks'],order:'abcdefghijklmnopqrstuvwxyz'}],['Identical neighboring words',{words:['moss','moss'],order:'abcdefghijklmnopqrstuvwxyz'}]],
  961:[['Repeated value is spread across the array',{nums:[7,2,7,4,7,6,7,8,7,9]}],['Smallest promised size',{nums:[3,5,3,8]}],['Repeated block at end',{nums:[1,2,3,4,9,9,9,9]}],['Repeated zero',{nums:[0,4,0,7,0,9]}]],
  962:[['Later low values create new left candidates',{nums:[9,6,8,2,7,1,5,10,3,12]}],['Strictly descending',{nums:[11,8,5,2]}],['Equal endpoints give full width',{nums:[4,9,2,4]}],['Smallest pair',{nums:[3,7]}]],
  970:[['Power combinations collide and deduplicate',{x:2,y:5,bound:120}],['Both bases one',{x:1,y:1,bound:20}],['Only one base grows',{x:1,y:3,bound:35}],['Bound too small',{x:2,y:7,bound:1}]],
  973:[['Quadrants and unequal distances',{points:[[7,2],[-3,4],[1,-2],[6,-5],[-4,-1],[0,8],[2,2],[-1,-1]],k:4}],['Equal distances are valid alternatives',{points:[[2,0],[0,2],[-2,0]],k:2}],['Include origin',{points:[[0,0],[5,1],[-2,3]],k:1}],['Keep every point',{points:[[3,4],[-1,2]],k:2}]],
  974:[['Negative values require normalized remainders',{nums:[7,-3,5,2,-6,4,8,-2,1],k:5}],['Every zero contributes',{nums:[0,0,0],k:7}],['Divisor one',{nums:[3,-2,8],k:1}],['No divisible subarray',{nums:[1,1],k:4}]],
  976:[['Largest side fails before a valid triple',{nums:[24,9,7,12,5,8,3,6]}],['Degenerate equality is rejected',{nums:[3,5,8]}],['All sides equal',{nums:[7,7,7,7]}],['Small valid triangle',{nums:[4,6,7]}]],
  978:[['Alternation interrupted by a plateau',{arr:[5,11,4,9,3,8,8,2,7,1,6]}],['All equal',{arr:[6,6,6,6]}],['Strictly increasing',{arr:[1,4,7,10]}],['Single value',{arr:[12]}]],
  983:[['Dense bursts separated by travel gaps',{days:[2,3,4,8,9,10,11,25,26,40,41,42,43],costs:[4,11,27]}],['One travel day',{days:[17],costs:[3,9,22]}],['A week fits one pass',{days:[10,11,12,13,14,15,16],costs:[5,12,35]}],['Widely spaced trips',{days:[1,50,100],costs:[2,8,20]}]],
  985:[['Parity changes across repeated updates',{nums:[4,-3,8,5,2,7],queries:[[3,0],[5,1],[-4,2],[1,3],[-2,0],[3,5]]}],['Even stays even',{nums:[6,2],queries:[[4,0],[-2,1]]}],['Odd stays odd',{nums:[3,7],queries:[[2,0],[4,1]]}],['Cross zero',{nums:[-2],queries:[[2,0],[1,0],[-3,0]]}]],
  989:[['Carry runs across several nines',{num:[7,3,9,9,9,8,9],k:217}],['New leading digit',{num:[9,9,9,9],k:1}],['Zero plus zero',{num:[0],k:0}],['Addend longer than array',{num:[4,2],k:9876}]],
  991:[['Reverse halving and increment decisions',{startValue:7,target:103}],['Target already smaller',{startValue:19,target:6}],['Equal start and target',{startValue:12,target:12}],['Exact repeated doubling',{startValue:3,target:48}]],
  997:[['Many trust edges with one judge',{n:6,trust:[[1,4],[2,4],[3,4],[5,4],[6,4],[1,2],[2,3],[5,6]]}],['Candidate trusts someone else',{n:3,trust:[[1,3],[2,3],[3,1]]}],['Single person needs no trust',{n:1,trust:[]}],['Nobody has enough incoming trust',{n:4,trust:[[1,2],[2,3],[3,4]]}]],
  999:[['Rays encounter pawns and blocking bishops',{board:rookBoard([[3,4,'R'],[0,4,'p'],[3,7,'p'],[6,4,'p'],[4,4,'B'],[3,1,'p'],[3,2,'B']])}],['Rook in a corner',{board:rookBoard([[0,0,'R'],[0,5,'p'],[7,0,'p']])}],['Only diagonal pawns',{board:rookBoard([[4,4,'R'],[3,3,'p'],[5,5,'p']])}],['Bishops block all directions',{board:rookBoard([[3,3,'R'],[2,3,'B'],[4,3,'B'],[3,2,'B'],[3,4,'B']])}]],
  1002:[['Common letters have different multiplicities',{words:['peppermint','temperament','perimeter']}],['No common letter',{words:['oak','fern','moss']}],['Repeated common characters',{words:['aabbb','abbbb','aaabb']}],['One word preserves every character',{words:['cedar']}]],
  1005:[['Several negatives followed by canceling leftover flips',{nums:[-9,4,-3,7,-6,2,0,5],k:5}],['Odd leftover flips smallest magnitude',{nums:[2,7,4],k:3}],['Even operations cancel',{nums:[3,8,5],k:4}],['More negatives than available flips',{nums:[-8,-5,-2,6],k:2}]],
};
export const collectionStoryExamples=Object.fromEntries(Object.entries(cases).map(([id,rows])=>[id,rows.map(([label,input])=>({label,input:JSON.stringify(input)}))]));
