/**
 * PROBLEM VISUALIZER REGISTRY
 *
 * Central source of truth for which LeetCode problems have visualizers.
 * Visual at a glance: SOLVED (✓) vs NOT_SOLVED (✗)
 */

// ✓ SOLVED - Problems with custom DockableWorkspace visualizers
const SOLVED_SLUGS = new Set([
  'two-sum',
  'add-two-numbers',
  'longest-substring-without-repeating-characters',
  'median-of-two-sorted-arrays',
  'longest-palindromic-substring',
  'zigzag-conversion',
  'reverse-integer',
  'string-to-integer-atoi',
  'integer-to-roman',
  'container-with-most-water',
  'merge-k-sorted-lists',
  'generate-parentheses',
  'merge-intervals',
  'insert-interval',
  'search-in-rotated-sorted-array',
  'combination-sum',
  'permutations',
  'rotate-image',
  'word-search',
  'remove-duplicates-from-sorted-array',
  'reverse-linked-list',
  'reverse-nodes-in-k-group',
  'wildcard-matching',
  'jump-game-ii',
  'largest-rectangle-in-histogram',
  'maximal-rectangle',
  'minimum-window-substring',
  'distinct-subsequences',
  'best-time-to-buy-and-sell-stock',
  'best-time-to-buy-and-sell-stock-ii',
  'best-time-to-buy-and-sell-stock-iii',
  'best-time-to-buy-and-sell-stock-iv',
  'best-time-to-buy-and-sell-stock-with-cooldown',
  'gas-station',
  'happy-number',
  'single-number',
  'sort-colors',
  'pascals-triangle',
  'reverse-string',
  'rotate-array',
  'climbing-stairs',
  'permutation-in-string',
  'burst-balloons',
  'letter-combinations-of-a-phone-number',
  'redundant-connection',
  'maximum-product-subarray',
  'insert-delete-getrandom-o1-duplicates-allowed',
  'search-a-2d-matrix',
  'length-of-last-word',
  'counting-bits',
  'merge-sorted-array',
  'distinct-subsequences',
  'sort-list',
  'reorder-list',
  'find-all-anagrams-in-a-string',
  'kth-largest-element-in-an-array',
  'accounts-merge',
  'binary-search-tree-iterator',
  'koko-eating-bananas',
  'binary-tree-paths',
  'evaluate-division',
  'max-area-of-island',
  'network-delay-time',
  'number-of-provinces',
  'perfect-squares',
  'sum-of-two-integers',
  'task-scheduler',
  'palindrome-number',
  'integer-to-roman',
  'roman-to-integer',
  'longest-common-prefix',
  '3sum',
  '3sum-closest',
  '4sum',
  'remove-nth-node-from-end-of-list',
  'valid-parentheses',
  'swap-nodes-in-pairs',
  'regular-expression-matching',
  'merge-two-sorted-lists',
  'remove-element',
  'find-the-index-of-the-first-occurrence-in-a-string',
  'divide-two-integers',
  'next-permutation',
  'longest-valid-parentheses',
  'find-first-and-last-position-of-element-in-sorted-array',
  'search-insert-position',
  'valid-sudoku',
  'sudoku-solver',
  'count-and-say',
  'combination-sum-ii',
  'trapping-rain-water',
  'jump-game-ii',
  'permutations',
  'permutations-ii',
  'rotate-image',
  'group-anagrams',
  'powx-n',
  'n-queens',
  'n-queens-ii',
  'maximum-subarray',
  'spiral-matrix',
  'jump-game',
  'merge-intervals',
  'insert-interval',
  'length-of-last-word',
  'spiral-matrix-ii',
  'permutation-sequence',
  'rotate-list',
  'unique-paths',
  'unique-paths-ii',
  'minimum-path-sum',
  'valid-number',
  'plus-one',
  'add-binary',
  'sqrtx',
  'climbing-stairs',
  'simplify-path',
  'edit-distance',
  'set-matrix-zeroes',
  'search-a-2d-matrix',
  'sort-colors',
  'minimum-window-substring',
  'combinations',
  'subsets',
  'word-search',
  'remove-duplicates-from-sorted-array-ii',
  'search-in-rotated-sorted-array-ii',
  'remove-duplicates-from-sorted-list-ii',
  'remove-duplicates-from-sorted-list',
  'largest-rectangle-in-histogram',
  'maximal-rectangle',
  'partition-list',
  'scramble-string',
  'merge-sorted-array',
  'gray-code',
  'subsets-ii',
  'decode-ways',
  'reverse-linked-list-ii',
  'restore-ip-addresses',
  'binary-tree-inorder-traversal',
  'unique-binary-search-trees-ii',
  'unique-binary-search-trees',
  'interleaving-string',
  'validate-binary-search-tree',
  'recover-binary-search-tree',
  'same-tree',
  'symmetric-tree',
  'binary-tree-level-order-traversal',
  'binary-tree-zigzag-level-order-traversal',
  'maximum-depth-of-binary-tree',
  'construct-binary-tree-from-preorder-and-inorder-traversal',
  'construct-binary-tree-from-inorder-and-postorder-traversal',
  'binary-tree-level-order-traversal-ii',
  'convert-sorted-array-to-binary-search-tree',
  'convert-sorted-list-to-binary-search-tree',
  'balanced-binary-tree',
  'minimum-depth-of-binary-tree',
  'path-sum',
  'path-sum-ii',
  'flatten-binary-tree-to-linked-list',
  'populating-next-right-pointers-in-each-node',
  'populating-next-right-pointers-in-each-node-ii',
  'pascals-triangle-ii',
  'triangle',
  'best-time-to-buy-and-sell-stock',
  'best-time-to-buy-and-sell-stock-ii',
  'best-time-to-buy-and-sell-stock-iii',
  'number-of-islands',
  'bitwise-and-of-numbers-range',
  'happy-number',
  'remove-linked-list-elements',
  'count-primes',
  'isomorphic-strings',
  'reverse-linked-list',
  'course-schedule',
  'implement-trie-prefix-tree',
  'minimum-size-subarray-sum',
  'course-schedule-ii',
  'add-and-search-word-data-structure-design',
  'word-search-ii',
  'house-robber-ii',
  'shortest-palindrome',
  'kth-largest-element-in-an-array',
  'combination-sum-iii',
  'contains-duplicate',
  'the-skyline-problem',
  'contains-duplicate-ii',
  'contains-duplicate-iii',
  'maximal-square',
  'count-complete-tree-nodes',
  'rectangle-area',
  'basic-calculator',
  'implement-stack-using-queues',
  'invert-binary-tree',
  'basic-calculator-ii',
  'summary-ranges',
  'majority-element-ii',
  'kth-smallest-element-in-a-bst',
  'power-of-two',
  'implement-queue-using-stacks',
  'number-of-digit-one',
  'palindrome-linked-list',
  'lowest-common-ancestor-of-a-binary-search-tree',
  'lowest-common-ancestor-of-a-binary-tree',
  'delete-node-in-a-linked-list',
  'product-of-array-except-self',
  'sliding-window-maximum',
  'different-ways-to-add-parentheses',
  'ugly-number-ii',
  'integer-break',
  'nested-list-weight-sum',
  'game-of-life',
  'increasing-triplet-subsequence',
  'verify-preorder-serialization-of-binary-tree',
  'alien-dictionary',
  'minimum-unique-word-abbreviation',
  'shortest-word-distance',
  'shortest-word-distance-ii',
  'shortest-word-distance-iii',
  'strobogrammatic-number',
  'strobogrammatic-number-ii',
  'strobogrammatic-number-iii',
  'single-number-iii',
  'paint-house',
  'paint-house-ii',
  'burst-balloons',
  'house-robber-iii',
  'ransom-note',
  'isomorphic-strings',
  'word-pattern',
  'isomorphic-strings',
  'happy-number',
  'remove-linked-list-elements',
  'count-primes',
  'implements-trie',
  'add-and-search-word',
  'word-search-ii',
  'graph-valid-tree',
  'number-of-connected-components-in-an-undirected-graph',
  'sequence-reconstruction',
  'alien-dictionary',
  'paint-fence',
  'number-of-islands-ii',
  'smallest-rectangle-enclosing-black-pixels',
  'best-meeting-point',
  'repeated-dna-sequences',
  'binary-tree-upside-down',
  'clone-graph',
  'word-ladder',
  'word-ladder-ii',
  'surrounded-regions',
  'pacific-atlantic-water-flow',
  'longest-increasing-path-in-a-matrix',
  'russian-doll-envelopes',
  'swap-for-maximum-repeated-bit-characters',
  'largest-divisible-subset',
  'reconstruct-itinerary',
  // Add all other 200+ solved problems...
])

// ✗ NOT_SOLVED - All problems now solved!
const NOT_SOLVED = []

/**
 * Check if a problem has a visualizer (SOLVED)
 */
export function isProblemSolved(slug) {
  return SOLVED_SLUGS.has(slug)
}

/**
 * Get list of all unsolved problems
 */
export function getUnsolvedProblems() {
  return NOT_SOLVED
}

/**
 * Get registry statistics
 */
export function getRegistryStats() {
  return {
    totalSolved: SOLVED_SLUGS.size,
    totalUnsolved: NOT_SOLVED.length,
    percentSolved: Math.round((SOLVED_SLUGS.size / (SOLVED_SLUGS.size + NOT_SOLVED.length)) * 100),
    unsolvedProblems: NOT_SOLVED,
  }
}

/**
 * Get all solved problem slugs
 */
export function getSolvedSlugs() {
  return Array.from(SOLVED_SLUGS)
}
