/**
 * Central registry for solution code across all problems
 * Each problem has its own solution code definition
 */

export const SOLUTION_CODE_REGISTRY = {
  'game-on-growing-tree': [
    { line: 1, text: "n = int(input())" },
    { line: 2, text: "parent = [0] + [x - 1 for x in map(int, input().split())]" },
    { line: 3, text: "if n == 1: print(1); exit()" },
    { line: 4, text: "" },
    { line: 5, text: "def solve(size):" },
    { line: 6, text: "    first = [0] * size" },
    { line: 7, text: "    second = [0] * size" },
    { line: 8, text: "    third = [0] * size" },
    { line: 9, text: "    for node in range(size - 1, 0, -1):" },
    { line: 10, text: "        p = parent[node]" },
    { line: 11, text: "        depth = second[node] + 1" },
    { line: 12, text: "        if depth > first[p]: first[p], second[p], third[p] = depth, first[p], second[p]" },
    { line: 13, text: "        elif depth > second[p]: second[p], third[p] = depth, second[p]" },
    { line: 14, text: "        elif depth > third[p]: third[p] = depth" },
    { line: 15, text: "    for node in range(1, size):" },
    { line: 16, text: "        p = parent[node]" },
    { line: 17, text: "        if second[p] <= second[node] + 1:" },
    { line: 18, text: "            depth = third[p] + 1" },
    { line: 19, text: "        else:" },
    { line: 20, text: "            depth = second[p] + 1" },
    { line: 21, text: "        if depth > first[node]: first[node], second[node], third[node] = depth, first[node], second[node]" },
    { line: 22, text: "        elif depth > second[node]: second[node], third[node] = depth, second[node]" },
    { line: 23, text: "        elif depth > third[node]: third[node] = depth" },
    { line: 24, text: "    return max(second) + 1" },
    { line: 25, text: "" },
    { line: 26, text: "ans = [0, 1, 1, 2] + [0] * n" },
    { line: 27, text: "ans[n + 2] = 17" },
    { line: 28, text: "stack = [(3, n + 2)]" },
    { line: 29, text: "while stack:" },
    { line: 30, text: "    left, right = stack.pop()" },
    { line: 31, text: "    mid = (left + right) >> 1" },
    { line: 32, text: "    value = solve(mid)" },
    { line: 33, text: "    ans[mid] = value" },
    { line: 34, text: "    if ans[left] == ans[mid]:" },
    { line: 35, text: "        for i in range(left + 1, mid): ans[i] = value" },
    { line: 36, text: "    elif left + 1 < mid:" },
    { line: 37, text: "        stack.append((left, mid))" },
    { line: 38, text: "    if ans[mid] == ans[right]:" },
    { line: 39, text: "        for i in range(mid + 1, right): ans[i] = value" },
    { line: 40, text: "    elif mid + 1 < right:" },
    { line: 41, text: "        stack.append((mid, right))" },
    { line: 42, text: "print(*ans[2:n + 2])" },
  ],

  'climbing-stairs': [
    { line: 1, text: 'class Solution:' },
    { line: 2, text: '    def climbStairs(self, n: int) -> int:' },
    { line: 3, text: '        one, two = 1, 1' },
    { line: 4, text: '        ' },
    { line: 5, text: '        for i in range(n - 1):' },
    { line: 6, text: '            temp = one' },
    { line: 7, text: '            one = one + two' },
    { line: 8, text: '            two = temp' },
    { line: 9, text: '            ' },
    { line: 10, text: '        return one' },
  ],

  'house-robber': [
    { line: 1, text: 'class Solution:' },
    { line: 2, text: '    def rob(self, nums: List[int]) -> int:' },
    { line: 3, text: '        if not nums: return 0' },
    { line: 4, text: '        ' },
    { line: 5, text: '        prev2 = 0' },
    { line: 6, text: '        prev1 = 0' },
    { line: 7, text: '        for money in nums:' },
    { line: 8, text: '            take = prev2 + money' },
    { line: 9, text: '            skip = prev1' },
    { line: 10, text: '            curr = max(take, skip)' },
    { line: 11, text: '            prev2, prev1 = prev1, curr' },
    { line: 12, text: '        return prev1' },
  ],

  'course-schedule': [
    { line: 1, text: 'class Solution:' },
    { line: 2, text: '    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:' },
    { line: 3, text: '        adj = {i: [] for i in range(numCourses)}' },
    { line: 4, text: '        indegree = [0] * numCourses' },
    { line: 5, text: '        ' },
    { line: 6, text: '        for crs, pre in prerequisites:' },
    { line: 7, text: '            adj[pre].append(crs)' },
    { line: 8, text: '            indegree[crs] += 1' },
    { line: 9, text: '            ' },
    { line: 10, text: '        queue = [i for i in range(numCourses) if indegree[i] == 0]' },
    { line: 11, text: '        visited = 0' },
    { line: 12, text: '        ' },
    { line: 13, text: '        while queue:' },
    { line: 14, text: '            node = queue.pop(0)' },
    { line: 15, text: '            visited += 1' },
    { line: 16, text: '            for neighbor in adj[node]:' },
    { line: 17, text: '                indegree[neighbor] -= 1' },
    { line: 18, text: '                if indegree[neighbor] == 0:' },
    { line: 19, text: '                    queue.append(neighbor)' },
    { line: 20, text: '                    ' },
    { line: 21, text: '        return visited == numCourses' },
  ],

  'max-depth-binary-tree': [
    { line: 1, text: 'class Solution:' },
    { line: 2, text: '    def maxDepth(self, root):' },
    { line: 3, text: '        if not root: return 0' },
    { line: 4, text: '        leftDepth  = self.maxDepth(root.left)' },
    { line: 5, text: '        rightDepth = self.maxDepth(root.right)' },
    { line: 6, text: '        return 1 + max(leftDepth, rightDepth)' },
  ],

  'minimum-window-substring': [
    { line: 1, text: 'class Solution:' },
    { line: 2, text: '    def minWindow(self, s: str, t: str) -> str:' },
    { line: 3, text: '        if not t or not s: return ""' },
    { line: 4, text: '        need = Counter(t)' },
    { line: 5, text: '        have = defaultdict(int)' },
    { line: 6, text: '        required = len(need)' },
    { line: 7, text: '        formed = 0' },
    { line: 8, text: '        left = 0' },
    { line: 9, text: '        best = (inf, 0, 0)' },
    { line: 10, text: '        for right, ch in enumerate(s):' },
    { line: 11, text: '            have[ch] += 1' },
    { line: 12, text: '            if ch in need and have[ch] == need[ch]:' },
    { line: 13, text: '                formed += 1' },
    { line: 14, text: '            while left <= right and formed == required:' },
    { line: 15, text: '                if right-left+1 < best[0]: best = (...)' },
    { line: 16, text: '                drop = s[left]' },
    { line: 17, text: '                have[drop] -= 1' },
    { line: 18, text: '                if drop in need and have[drop] < need[drop]: formed -= 1' },
    { line: 19, text: '                left += 1' },
    { line: 20, text: '        return s[l:r+1] if best found else ""' },
  ],

  'rotate-array': [
    { line: 1, text: 'def rotate(nums, k):' },
    { line: 2, text: '    k %= len(nums)' },
    { line: 3, text: '    def rev(l, r):' },
    { line: 4, text: '        while l < r:' },
    { line: 5, text: '            nums[l], nums[r] = nums[r], nums[l]' },
    { line: 6, text: '            l += 1; r -= 1' },
    { line: 7, text: '    rev(0, len(nums)-1)   # reverse all' },
    { line: 8, text: '    rev(0, k-1)           # reverse first k' },
    { line: 9, text: '    rev(k, len(nums)-1)   # reverse rest' },
  ],

  'gas-station': [
    { line: 1, text: 'def canCompleteCircuit(gas, cost):' },
    { line: 2, text: '    total, tank, start = 0, 0, 0' },
    { line: 3, text: '    for i in range(len(gas)):' },
    { line: 4, text: '        diff = gas[i] - cost[i]' },
    { line: 5, text: '        total += diff' },
    { line: 6, text: '        tank += diff' },
    { line: 7, text: '        if tank < 0:' },
    { line: 8, text: '            start = i + 1' },
    { line: 9, text: '            tank = 0' },
    { line: 10, text: '    return start if total >= 0 else -1' },
  ],

  'happy-number': [
    { line: 1, text: 'def isHappy(n):' },
    { line: 2, text: '    seen = set()' },
    { line: 3, text: '    while n != 1:' },
    { line: 4, text: '        if n in seen: return False' },
    { line: 5, text: '        seen.add(n)' },
    { line: 6, text: '        n = sum(d**2 for d in digits(n))' },
    { line: 7, text: '    return True' },
  ],

  'single-number': [
    { line: 1, text: 'def singleNumber(nums):' },
    { line: 2, text: '    result = 0' },
    { line: 3, text: '    for n in nums:' },
    { line: 4, text: '        result ^= n' },
    { line: 5, text: '    return result' },
  ],

  'sort-colors': [
    { line: 1, text: 'def sortColors(nums):' },
    { line: 2, text: '    lo, mid, hi = 0, 0, len(nums)-1' },
    { line: 3, text: '    while mid <= hi:' },
    { line: 4, text: '        if nums[mid] == 0:' },
    { line: 5, text: '            nums[lo], nums[mid] = nums[mid], nums[lo]' },
    { line: 6, text: '            lo += 1; mid += 1' },
    { line: 7, text: '        elif nums[mid] == 1:' },
    { line: 8, text: '            mid += 1' },
    { line: 9, text: '        else:  # nums[mid] == 2' },
    { line: 10, text: '            nums[mid], nums[hi] = nums[hi], nums[mid]' },
    { line: 11, text: '            hi -= 1' },
  ],

  'pascals-triangle': [
    { line: 1, text: 'def generate(numRows):' },
    { line: 2, text: '    triangle = [[1]]' },
    { line: 3, text: '    for i in range(1, numRows):' },
    { line: 4, text: '        prev = triangle[i - 1]' },
    { line: 5, text: '        row = [1]' },
    { line: 6, text: '        for j in range(1, i):' },
    { line: 7, text: '            row.append(prev[j-1] + prev[j])' },
    { line: 8, text: '        row.append(1)' },
    { line: 9, text: '        triangle.append(row)' },
    { line: 10, text: '    return triangle' },
  ],

  'reverse-string': [
    { line: 1, text: 'def reverseString(s):' },
    { line: 2, text: '    l, r = 0, len(s) - 1' },
    { line: 3, text: '    while l < r:' },
    { line: 4, text: '        s[l], s[r] = s[r], s[l]' },
    { line: 5, text: '        l += 1' },
    { line: 6, text: '        r -= 1' },
  ],

  'plus-one': [
    { line: 1, text: 'def plusOne(digits):' },
    { line: 2, text: '    for i in range(len(digits)-1, -1, -1):' },
    { line: 3, text: '        if digits[i] < 9:' },
    { line: 4, text: '            digits[i] += 1' },
    { line: 5, text: '            return digits' },
    { line: 6, text: '        digits[i] = 0  # carry' },
    { line: 7, text: '    return [1] + digits  # all 9s' },
  ],

  'reverse-bits': [
    { line: 1, text: 'def reverseBits(n):' },
    { line: 2, text: '    result = 0' },
    { line: 3, text: '    for i in range(32):' },
    { line: 4, text: '        result = (result << 1) | (n & 1)' },
    { line: 5, text: '        n >>= 1' },
    { line: 6, text: '    return result' },
  ],

  'min-size-subarray-sum': [
    { line: 1, text: 'def minSubArrayLen(target, nums):' },
    { line: 2, text: '    n = len(nums)' },
    { line: 3, text: '    left = 0' },
    { line: 4, text: '    current_sum = 0' },
    { line: 5, text: '    min_len = float("inf")' },
    { line: 6, text: '    for right in range(n):' },
    { line: 7, text: '        current_sum += nums[right]' },
    { line: 8, text: '        while current_sum >= target:' },
    { line: 9, text: '            min_len = min(min_len, right - left + 1)' },
    { line: 10, text: '            current_sum -= nums[left]' },
    { line: 11, text: '            left += 1' },
    { line: 12, text: '    return min_len if min_len != float("inf") else 0' },
  ],

  'number-of-1-bits': [
    { line: 1, text: 'def hammingWeight(n):' },
    { line: 2, text: '    count = 0' },
    { line: 3, text: '    while n:' },
    { line: 4, text: '        count += n & 1' },
    { line: 5, text: '        n >>= 1' },
    { line: 6, text: '    return count' },
  ],

  'find-peak-element': [
    { line: 1, text: 'def findPeakElement(nums):' },
    { line: 2, text: '    left, right = 0, len(nums) - 1' },
    { line: 3, text: '    while left < right:' },
    { line: 4, text: '        mid = (left + right) // 2' },
    { line: 5, text: '        if nums[mid] < nums[mid + 1]:' },
    { line: 6, text: '            left = mid + 1' },
    { line: 7, text: '        else:' },
    { line: 8, text: '            right = mid' },
    { line: 9, text: '    return left' },
  ],

  'missing-number': [
    { line: 1, text: 'def missingNumber(nums):' },
    { line: 2, text: '    n = len(nums)' },
    { line: 3, text: '    expected_sum = n * (n + 1) // 2' },
    { line: 4, text: '    actual_sum = sum(nums)' },
    { line: 5, text: '    return expected_sum - actual_sum' },
  ],

  'rotate-image': [
    { line: 1, text: 'def rotate(matrix):' },
    { line: 2, text: '    n = len(matrix)' },
    { line: 3, text: '    for i in range(n // 2):' },
    { line: 4, text: '        for j in range((n + 1) // 2):' },
    { line: 5, text: '            top, right = i, n - 1 - i' },
    { line: 6, text: '            bottom, left = n - 1 - i, j' },
    { line: 7, text: '            temp = matrix[top][j]' },
    { line: 8, text: '            matrix[top][j] = matrix[bottom][left]' },
    { line: 9, text: '            matrix[bottom][left] = matrix[right][n - 1 - j]' },
    { line: 10, text: '            matrix[right][n - 1 - j] = matrix[i][n - 1 - j]' },
    { line: 11, text: '            matrix[i][n - 1 - j] = temp' },
  ],

  'set-matrix-zeroes': [
    { line: 1, text: 'def setZeroes(matrix):' },
    { line: 2, text: '    rows, cols = set(), set()' },
    { line: 3, text: '    for i in range(len(matrix)):' },
    { line: 4, text: '        for j in range(len(matrix[0])):' },
    { line: 5, text: '            if matrix[i][j] == 0:' },
    { line: 6, text: '                rows.add(i)' },
    { line: 7, text: '                cols.add(j)' },
    { line: 8, text: '    for i in range(len(matrix)):' },
    { line: 9, text: '        for j in range(len(matrix[0])):' },
    { line: 10, text: '            if i in rows or j in cols:' },
    { line: 11, text: '                matrix[i][j] = 0' },
  ],

  'decode-string': [
    { line: 1, text: 'def decodeString(s):' },
    { line: 2, text: '    stack = []' },
    { line: 3, text: '    for char in s:' },
    { line: 4, text: '        if char == "]":' },
    { line: 5, text: '            string = ""' },
    { line: 6, text: '            while stack and stack[-1] != "[":' },
    { line: 7, text: '                string = stack.pop() + string' },
    { line: 8, text: '            stack.pop()  # remove "["' },
    { line: 9, text: '            num = ""' },
    { line: 10, text: '            while stack and stack[-1].isdigit():' },
    { line: 11, text: '                num = stack.pop() + num' },
    { line: 12, text: '            stack.append(string * int(num))' },
    { line: 13, text: '        else:' },
    { line: 14, text: '            stack.append(char)' },
    { line: 15, text: '    return "".join(stack)' },
  ],

  'eval-rpn': [
    { line: 1, text: 'def evalRPN(tokens):' },
    { line: 2, text: '    stack = []' },
    { line: 3, text: '    for token in tokens:' },
    { line: 4, text: '        if token in "+-*/":' },
    { line: 5, text: '            b = stack.pop()' },
    { line: 6, text: '            a = stack.pop()' },
    { line: 7, text: '            if token == "+": stack.append(a + b)' },
    { line: 8, text: '            elif token == "-": stack.append(a - b)' },
    { line: 9, text: '            elif token == "*": stack.append(a * b)' },
    { line: 10, text: '            else: stack.append(int(a / b))' },
    { line: 11, text: '        else:' },
    { line: 12, text: '            stack.append(int(token))' },
    { line: 13, text: '    return stack[0]' },
  ],

  'ipo': [
    { line: 1, text: 'def findMaximizedCapital(k, w, profits, capital):' },
    { line: 2, text: '    projects = sorted(zip(capital, profits))' },
    { line: 3, text: '    heap = []' },
    { line: 4, text: '    idx = 0' },
    { line: 5, text: '    for _ in range(k):' },
    { line: 6, text: '        while idx < len(projects) and projects[idx][0] <= w:' },
    { line: 7, text: '            heappush(heap, -projects[idx][1])' },
    { line: 8, text: '            idx += 1' },
    { line: 9, text: '        if not heap: break' },
    { line: 10, text: '        w += -heappop(heap)' },
    { line: 11, text: '    return w' },
  ],

  'copy-list-with-random-pointer': [
    { line: 1, text: 'def copyRandomList(head):' },
    { line: 2, text: '    if not head: return None' },
    { line: 3, text: '    mapping = {}' },
    { line: 4, text: '    node = head' },
    { line: 5, text: '    while node:' },
    { line: 6, text: '        mapping[node] = Node(node.val)' },
    { line: 7, text: '        node = node.next' },
    { line: 8, text: '    node = head' },
    { line: 9, text: '    while node:' },
    { line: 10, text: '        if node.next:' },
    { line: 11, text: '            mapping[node].next = mapping[node.next]' },
    { line: 12, text: '        if node.random:' },
    { line: 13, text: '            mapping[node].random = mapping[node.random]' },
    { line: 14, text: '        node = node.next' },
    { line: 15, text: '    return mapping[head]' },
  ],

  'first-missing-positive': [
    { line: 1, text: 'def firstMissingPositive(nums):' },
    { line: 2, text: '    n = len(nums)' },
    { line: 3, text: '    for i in range(n):' },
    { line: 4, text: '        while 1 <= nums[i] <= n and nums[nums[i]-1] != nums[i]:' },
    { line: 5, text: '            nums[nums[i]-1], nums[i] = nums[i], nums[nums[i]-1]' },
    { line: 6, text: '    for i in range(n):' },
    { line: 7, text: '        if nums[i] != i + 1:' },
    { line: 8, text: '            return i + 1' },
    { line: 9, text: '    return n + 1' },
  ],

  'candy': [
    { line: 1, text: 'def candy(ratings):' },
    { line: 2, text: '    n = len(ratings)' },
    { line: 3, text: '    candies = [1] * n' },
    { line: 4, text: '    for i in range(1, n):' },
    { line: 5, text: '        if ratings[i] > ratings[i-1]:' },
    { line: 6, text: '            candies[i] = candies[i-1] + 1' },
    { line: 7, text: '    for i in range(n-2, -1, -1):' },
    { line: 8, text: '        if ratings[i] > ratings[i+1]:' },
    { line: 9, text: '            candies[i] = max(candies[i], candies[i+1] + 1)' },
    { line: 10, text: '    return sum(candies)' },
  ],

  'largest-rectangle-in-histogram': [
    { line: 1, text: 'def largestRectangleArea(heights):' },
    { line: 2, text: '    stack = []' },
    { line: 3, text: '    max_area = 0' },
    { line: 4, text: '    for i, h in enumerate(heights):' },
    { line: 5, text: '        start = i' },
    { line: 6, text: '        while stack and stack[-1][1] > h:' },
    { line: 7, text: '            idx, height = stack.pop()' },
    { line: 8, text: '            max_area = max(max_area, height * (i - idx))' },
    { line: 9, text: '            start = idx' },
    { line: 10, text: '        if h > 0:' },
    { line: 11, text: '            stack.append((start, h))' },
    { line: 12, text: '    for idx, h in stack:' },
    { line: 13, text: '        max_area = max(max_area, h * (len(heights) - idx))' },
    { line: 14, text: '    return max_area' },
  ],

  'best-time-to-buy-and-sell-stock-iii': [
    { line: 1, text: 'def maxProfit(prices):' },
    { line: 2, text: '    if not prices: return 0' },
    { line: 3, text: '    left_profit = [0] * len(prices)' },
    { line: 4, text: '    left_min = prices[0]' },
    { line: 5, text: '    for i in range(1, len(prices)):' },
    { line: 6, text: '        left_min = min(left_min, prices[i])' },
    { line: 7, text: '        left_profit[i] = max(left_profit[i-1], prices[i] - left_min)' },
    { line: 8, text: '    right_profit = [0] * len(prices)' },
    { line: 9, text: '    right_max = prices[-1]' },
    { line: 10, text: '    for i in range(len(prices)-2, -1, -1):' },
    { line: 11, text: '        right_max = max(right_max, prices[i])' },
    { line: 12, text: '        right_profit[i] = max(right_profit[i+1], right_max - prices[i])' },
    { line: 13, text: '    return max(left_profit[i] + right_profit[i] for i in range(len(prices)))' },
  ],

  'basic-calculator': [
    { line: 1, text: 'def calculate(s):' },
    { line: 2, text: '    stack = []' },
    { line: 3, text: '    num, sign = 0, "+"' },
    { line: 4, text: '    for i, c in enumerate(s + "+"):' },
    { line: 5, text: '        if c.isdigit():' },
    { line: 6, text: '            num = num * 10 + int(c)' },
    { line: 7, text: '        if c in "+-*/" or i == len(s):' },
    { line: 8, text: '            if sign == "+": stack.append(num)' },
    { line: 9, text: '            elif sign == "-": stack.append(-num)' },
    { line: 10, text: '            elif sign == "*": stack.append(stack.pop() * num)' },
    { line: 11, text: '            else: stack.append(int(stack.pop() / num))' },
    { line: 12, text: '            num, sign = 0, c' },
    { line: 13, text: '    return sum(stack)' },
  ],

  'permutation-in-string': [
    { line: 1, text: 'def checkInclusion(s1, s2):' },
    { line: 2, text: '    if len(s1) > len(s2): return False' },
    { line: 3, text: '    count1 = [0] * 26' },
    { line: 4, text: '    count2 = [0] * 26' },
    { line: 5, text: '    for c in s1: count1[ord(c) - ord("a")] += 1' },
    { line: 6, text: '    for i in range(len(s2)):' },
    { line: 7, text: '        count2[ord(s2[i]) - ord("a")] += 1' },
    { line: 8, text: '        if i >= len(s1):' },
    { line: 9, text: '            count2[ord(s2[i - len(s1)]) - ord("a")] -= 1' },
    { line: 10, text: '        if count1 == count2: return True' },
    { line: 11, text: '    return False' },
  ],

  'burst-balloons': [
    { line: 1, text: 'def maxCoins(nums):' },
    { line: 2, text: '    nums = [1] + [n for n in nums if n > 0] + [1]' },
    { line: 3, text: '    n = len(nums)' },
    { line: 4, text: '    dp = [[0] * n for _ in range(n)]' },
    { line: 5, text: '    for length in range(3, n + 1):' },
    { line: 6, text: '        for left in range(n - length + 1):' },
    { line: 7, text: '            right = left + length - 1' },
    { line: 8, text: '            for k in range(left + 1, right):' },
    { line: 9, text: '                coins = nums[left] * nums[k] * nums[right]' },
    { line: 10, text: '                dp[left][right] = max(dp[left][right],dp[left][k] + coins + dp[k][right])' },
    { line: 11, text: '    return dp[0][n - 1]' },
  ],

  'letter-combinations-of-a-phone-number': [
    { line: 1, text: 'def letterCombinations(digits):' },
    { line: 2, text: '    if not digits: return []' },
    { line: 3, text: '    mapping = {"2":"abc", "3":"def", "4":"ghi", "5":"jkl",\n              "6":"mno", "7":"pqrs", "8":"tuv", "9":"wxyz"}' },
    { line: 4, text: '    result = [""]' },
    { line: 5, text: '    for digit in digits:' },
    { line: 6, text: '        temp = []' },
    { line: 7, text: '        for combo in result:' },
    { line: 8, text: '            for letter in mapping[digit]:' },
    { line: 9, text: '                temp.append(combo + letter)' },
    { line: 10, text: '        result = temp' },
    { line: 11, text: '    return result' },
  ],

  'redundant-connection': [
    { line: 1, text: 'def findRedundantConnection(edges):' },
    { line: 2, text: '    parent = list(range(len(edges) + 1))' },
    { line: 3, text: '    def find(x):' },
    { line: 4, text: '        if parent[x] != x: parent[x] = find(parent[x])' },
    { line: 5, text: '        return parent[x]' },
    { line: 6, text: '    for u, v in edges:' },
    { line: 7, text: '        pu, pv = find(u), find(v)' },
    { line: 8, text: '        if pu == pv: return [u, v]' },
    { line: 9, text: '        parent[pu] = pv' },
    { line: 10, text: '    return []' },
  ],

  'maximum-product-subarray': [
    { line: 1, text: 'def maxProduct(nums):' },
    { line: 2, text: '    if not nums: return 0' },
    { line: 3, text: '    max_prod = nums[0]' },
    { line: 4, text: '    min_prod = nums[0]' },
    { line: 5, text: '    result = nums[0]' },
    { line: 6, text: '    for i in range(1, len(nums)):' },
    { line: 7, text: '        if nums[i] < 0: max_prod, min_prod = min_prod, max_prod' },
    { line: 8, text: '        max_prod = max(nums[i], max_prod * nums[i])' },
    { line: 9, text: '        min_prod = min(nums[i], min_prod * nums[i])' },
    { line: 10, text: '        result = max(result, max_prod)' },
    { line: 11, text: '    return result' },
  ],

  'best-time-to-buy-and-sell-stock-iv': [
    { line: 1, text: 'def maxProfit(k, prices):' },
    { line: 2, text: '    if k >= len(prices) // 2: return sum(max(0, prices[i+1] - prices[i]) for i in range(len(prices)-1))' },
    { line: 3, text: '    buy = [-float("inf")] * (k + 1)' },
    { line: 4, text: '    sell = [0] * (k + 1)' },
    { line: 5, text: '    for price in prices:' },
    { line: 6, text: '        for j in range(k, 0, -1):' },
    { line: 7, text: '            sell[j] = max(sell[j], buy[j] + price)' },
    { line: 8, text: '            buy[j] = max(buy[j], sell[j-1] - price)' },
    { line: 9, text: '    return sell[k]' },
  ],

  'insert-delete-getrandom-o1-duplicates-allowed': [
    { line: 1, text: 'class RandomizedCollection:' },
    { line: 2, text: '    def __init__(self):' },
    { line: 3, text: '        self.nums = []' },
    { line: 4, text: '        self.indices = {}' },
    { line: 5, text: '    def insert(self, val):' },
    { line: 6, text: '        if val not in self.indices:' },
    { line: 7, text: '            self.indices[val] = set()' },
    { line: 8, text: '        self.indices[val].add(len(self.nums))' },
    { line: 9, text: '        self.nums.append(val)' },
    { line: 10, text: '    def remove(self, val):' },
    { line: 11, text: '        if not self.indices[val]: return False' },
    { line: 12, text: '        idx = self.indices[val].pop()' },
    { line: 13, text: '        last = self.nums[-1]' },
    { line: 14, text: '        self.nums[idx] = last' },
    { line: 15, text: '        self.indices[last].add(idx)' },
    { line: 16, text: '        self.nums.pop()' },
    { line: 17, text: '        return True' },
  ],

  'palindrome-number': [
    { line: 1, text: 'def isPalindrome(x: int) -> bool:' },
    { line: 2, text: '    if x < 0 or (x % 10 == 0 and x != 0):' },
    { line: 3, text: '        return False' },
    { line: 4, text: '    rev = 0' },
    { line: 5, text: '    while x > rev:' },
    { line: 6, text: '        rev = rev * 10 + x % 10' },
    { line: 7, text: '        x //= 10' },
    { line: 8, text: '    return x == rev or x == rev // 10' },
  ],

  'sum-of-two-integers': [
    { line: 1, text: 'def getSum(a: int, b: int) -> int:' },
    { line: 2, text: '    # Mask for 32-bit integers' },
    { line: 3, text: '    mask = 0xffffffff' },
    { line: 4, text: '    ' },
    { line: 5, text: '    while b != 0:' },
    { line: 6, text: '        # Calculate sum without carry (XOR)' },
    { line: 7, text: '        xor = (a ^ b) & mask' },
    { line: 8, text: '        ' },
    { line: 9, text: '        # Calculate carry bits (AND then shift)' },
    { line: 10, text: '        carry = ((a & b) << 1) & mask' },
    { line: 11, text: '        ' },
    { line: 12, text: '        a = xor' },
    { line: 13, text: '        b = carry' },
    { line: 14, text: '    ' },
    { line: 15, text: '    # Handle negative numbers (two\'s complement)' },
    { line: 16, text: '    return a if a <= 0x7fffffff else ~(a ^ mask)' },
  ],

  'super-power': [
    { line: 1, text: 'def superPower(base: int, exponents: List[int]) -> int:' },
    { line: 2, text: '    MOD = 1337' },
    { line: 3, text: '    result = 1' },
    { line: 4, text: '    # Process digits from right to left' },
    { line: 5, text: '    for digit in reversed(exponents):' },
    { line: 6, text: '        result *= pow(base, digit, MOD)' },
    { line: 7, text: '        result %= MOD' },
    { line: 8, text: '        base = pow(base, 10, MOD)' },
    { line: 9, text: '    return result' },
  ],

  'guess-number-higher-or-lower': [
    { line: 1, text: 'def guessNumber(n: int) -> int:' },
    { line: 2, text: '    left, right = 1, n' },
    { line: 3, text: '    ' },
    { line: 4, text: '    while left <= right:' },
    { line: 5, text: '        mid = left + (right - left) // 2' },
    { line: 6, text: '        res = guess(mid)' },
    { line: 7, text: '        ' },
    { line: 8, text: '        if res == 0:' },
    { line: 9, text: '            return mid' },
    { line: 10, text: '        elif res == 1:' },
    { line: 11, text: '            left = mid + 1' },
    { line: 12, text: '        else:' },
    { line: 13, text: '            right = mid - 1' },
    { line: 14, text: '    ' },
    { line: 15, text: '    return -1' },
    { line: 16, text: '    ' },
  ],

  'wiggle-sort-ii': [
    { line: 1, text: 'def wiggleSort(nums: List[int]) -> None:' },
    { line: 2, text: '    # Find median using quickselect' },
    { line: 3, text: '    median = findKthLargest(nums, (len(nums) + 1) // 2)' },
    { line: 4, text: '    # Partition: small | equal | large' },
    { line: 5, text: '    small, equal, large = [], [], []' },
    { line: 6, text: '    for num in nums:' },
    { line: 7, text: '        if num < median: small.append(num)' },
    { line: 8, text: '        elif num == median: equal.append(num)' },
    { line: 9, text: '        else: large.append(num)' },
    { line: 10, text: '    # Alternate placement: large at odd, small at even' },
    { line: 11, text: '    small.reverse()' },
    { line: 12, text: '    large.reverse()' },
    { line: 13, text: '    j, k = 0, 0' },
    { line: 14, text: '    for i in range(len(nums)):' },
    { line: 15, text: '        if i % 2 == 1: nums[i] = large[k]; k += 1' },
    { line: 16, text: '        else: nums[i] = small[j] if j < len(small) else large[k]' },
  ],

  // Add more problems here...
};

/**
 * Get solution code for a problem
 * @param {string} problemSlug - The problem slug
 * @returns {Array} Array of code line objects
 */
export function getSolutionCode(problemSlug) {
  return SOLUTION_CODE_REGISTRY[problemSlug] || [];
}

/**
 * Register solution code for a new problem
 * @param {string} problemSlug - The problem slug
 * @param {Array} codeLines - Array of code line objects
 */
export function registerSolutionCode(problemSlug, codeLines) {
  SOLUTION_CODE_REGISTRY[problemSlug] = codeLines;
}
