export const trieCases = {
648:[['Short roots beat overlapping longer roots',{dictionary:['for','forest','gro','grove','riv','river','sun'],sentence:'foresters gathered riverside sunshine beside groves and mountains'}],['One-letter root wins',{dictionary:['a','ac','ace'],sentence:'acers across amber'}],['No root matches',{dictionary:['oak','elm'],sentence:'pine cedar birch'}],['Exact roots remain unchanged',{dictionary:['fern','moss'],sentence:'fern moss mossy ferns'}]],
677:[['Overwrite values while several keys share prefixes',{operations:[['insert','forest',8],['insert','fork',5],['insert','form',11],['sum','for'],['insert','forest',3],['sum','for'],['insert','fern',7],['sum','f'],['sum','fo'],['sum','z']]}],['Missing prefix returns zero',{operations:[['sum','oak'],['insert','pine',4],['sum','oak']]}],['A complete key can also be a prefix',{operations:[['insert','a',3],['insert','ab',7],['sum','a'],['sum','ab']]}],['Same-value overwrite adds nothing',{operations:[['insert','elm',9],['insert','elm',9],['sum','e']]}]],
720:[['Two complete prefix chains compete by length and spelling',{words:['f','fo','for','fore','fores','forest','g','gr','gro','grov','grove','forester']}],['Missing intermediate prefix blocks longer word',{words:['s','su','sunny']}],['Equal lengths choose lexicographically smaller',{words:['b','ba','bar','c','ca','cat']}],['No one-letter starting word',{words:['oak','pine','forest']}]],
820:[['Suffix chains share reversed trie branches',{words:['cedar','dar','ar','star','tar','river','iver','ver','r','moss','oss']}],['Duplicate words add no length',{words:['grove','grove','grove']}],['All words suffixes of one longest word',{words:['g','ng','ing','ring','spring']}],['No suffix sharing',{words:['oak','elm','fir']}]],
1032:[['Overlapping matches appear throughout a longer stream',{words:['fir','ir','river','ver','moss','ss','oak'],queries:'xfirivermossyoakfir'}],['One-letter matches are immediate',{words:['a','z'],queries:'abzzca'}],['No stream suffix matches',{words:['oak','elm'],queries:'ppppqqqrr'}],['Repeated suffix matches overlap',{words:['aa','aaa'],queries:'aaaaa'}]],
1268:[['Typed prefixes narrow shared suggestion lists',{products:['forest','fork','form','format','formal','fern','forge','fort','grove','fir'],searchWord:'formal'}],['Absent prefix stays absent',{products:['oak','oat','elm'],searchWord:'orbit'}],['Fewer than three products',{products:['pine','pink'],searchWord:'pine'}],['Exact product also prefixes longer products',{products:['a','ac','ace','acorn','actor'],searchWord:'ace'}]],
1804:[['Duplicates, shared prefixes, and erasure affect different counts',{operations:[['insert','forest'],['insert','fork'],['insert','forest'],['insert','for'],['countWordsStartingWith','for'],['countWordsEqualTo','for'],['erase','forest'],['countWordsEqualTo','forest'],['countWordsStartingWith','fore'],['erase','for'],['countWordsEqualTo','for'],['countWordsStartingWith','for']]}],['Counts on an empty trie',{operations:[['countWordsEqualTo','oak'],['countWordsStartingWith','o']]}],['Erasing a prefix preserves its longer word',{operations:[['insert','a'],['insert','ab'],['erase','a'],['countWordsEqualTo','a'],['countWordsStartingWith','a'],['countWordsEqualTo','ab']]}],['Erase final occurrence then reuse its path',{operations:[['insert','elm'],['erase','elm'],['countWordsStartingWith','e'],['insert','elm'],['countWordsEqualTo','elm']]}]],
};
