import { useState, useMemo, useCallback } from 'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import PointerRail from '../../components/shared/PointerRail'
import FloatingPanel from '../../components/shared/FloatingPanel'
import { usePlaybackState } from '../../hooks/usePlaybackState'
import { useCodeVisualConnectivity } from '../../hooks/useCodeVisualConnectivity'
import { getExamplesOr } from '../../config/examplesRegistry'
import { createPortal } from 'react-dom'
import './RangeSumQuery-MutableVisualizer.css'
const CODE=[{line:1,text:'class NumArray:'},{line:2,text:'    def __init__(self, nums):'},{line:3,text:'        self.bit = [0] * (len(nums) + 1)'},{line:4,text:'    def add(self, index, delta):'},{line:5,text:'        while index < len(self.bit):'},{line:6,text:'            self.bit[index] += delta; index += index & -index'},{line:7,text:'    def sumRange(self, left, right):'},{line:8,text:'        return prefix(right + 1) - prefix(left)'}]
function trace({nums,operations}){const a=[...nums],bit=Array(a.length+1).fill(0),out=[];const snap=(active,message,line)=>out.push({phase:line===8?'done':'process',activeLine:line,message,values:[...a],bit:[...bit],active,relatedLines:[line]});const add=(i,d,label)=>{for(let p=i+1;p<bit.length;p+=p&-p){bit[p]+=d;snap(i,`${label}: update Fenwick cell ${p} by ${d}.`,6)}};out.push({phase:'init',activeLine:3,message:'Fenwick tree cells store partial sums.',values:[...a],bit:[...bit],active:null,relatedLines:[3]});a.forEach((v,i)=>add(i,v,`Build value ${v}`));for(const op of operations){if(op.type==='update'){const d=op.value-a[op.index];a[op.index]=op.value;snap(op.index,`Set nums[${op.index}] to ${op.value}; propagate delta ${d}.`,4);add(op.index,d,'Update')}else if(op.type==='sumRange'){const pref=x=>{let s=0;for(let p=x;p>0;p-=p&-p)s+=bit[p];return s};const result=pref(op.right+1)-pref(op.left);snap(null,`sumRange(${op.left}, ${op.right}) = ${result}.`,8)}}return out}
const EXAMPLES=getExamplesOr('range-sum-query-mutable',[{label:'Update then query',nums:[1,3,5],operations:[{type:'sumRange',left:0,right:2},{type:'update',index:1,value:2},{type:'sumRange',left:0,right:2}]}])
function parse(raw){try{const x=JSON.parse(raw);if(!Array.isArray(x.nums)||!x.nums.every(Number.isFinite)||!Array.isArray(x.operations))throw Error('Use nums and operations.');return {input:x,inputError:''}}catch(e){return {input:null,inputError:e.message}}}
export default function RangeSumQueryMutableVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?trace(input):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'viz',title:'Fenwick tree',dockMode:'split-right'},{id:'examples',title:'Examples',dockMode:'split-bottom'}],[]);const contents={input:<div className="range-sum-query--mutable-panel"><div className="range-sum-query--mutable-panel-body"><textarea className="range-sum-query--mutable-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,viz:!input?<div className="range-sum-query--mutable-error">{inputError}</div>:<div className="range-sum-query--mutable-panel"><div className="range-sum-query--mutable-panel-body"><div className="range-sum-query--mutable-step-info"><h3>{step?.message||'Press play to build the Fenwick tree.'}</h3></div><PointerRail title="Mutable array" values={step?.values||input.nums} pointers={step?.active===null||step?.active===undefined?[]:[{id:'changed',label:'i',index:step.active,tone:'primary'}]}/><PointerRail title="Fenwick tree (1-indexed)" values={(step?.bit||[0]).slice(1)} note="Each update climbs through parent ranges with i += i & -i."/></div></div>,examples:<div className="range-sum-query--mutable-panel"><div className="range-sum-query--mutable-panel-body range-sum-query--mutable-examples">{EXAMPLES.map((x,i)=><button className="range-sum-query--mutable-example-btn" key={i} onClick={()=>apply(x)}>{x.label||`Example ${i+1}`}</button>)}</div></div>};return <div className="range-sum-query--mutable-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
