import { solvers } from './algorithms.js';
import { scanStoryExamples } from '../../../config/scanStoryExamples.js';
import { scanStoryMetadata } from './metadata.js';

// Five teaching lines correspond to setup, iteration, decision, update, return.
const specs={
  594:['nums','Find the longest subsequence whose maximum and minimum differ by exactly one.','Count each value, then combine only neighboring value buckets. Equal values alone cannot satisfy an exact difference of one.',['counts = frequencies(nums)','for value in counts:','    inspect counts[value + 1]','    if present, maximize counts[value] + counts[value+1]','return best length'],'O(n) time and space.'],
  598:['m n ops','Count cells that attain the maximum after origin-anchored rectangle increments.','Every operation includes the origin. The intersection of all rectangles receives every increment, so only its dimensions matter.',['rows = m; cols = n','for a, b in ops:','    intersect with this rectangle','    rows = min(rows,a); cols = min(cols,b)','return rows * cols'],'O(number of operations) time; O(1) state.'],
  599:['list1 list2','Return all common strings with the least combined index.','Index the first list, then scan the second. Replace winners on a lower sum and append on an equal sum.',['indices = positions in list1; best = infinity','for j, name in list2:','    if name is common, compare i+j with best','    replace winners on improvement; append on tie','return winners'],'O(n + m) time and space.'],
  646:['pairs','Find the maximum number of strictly nonoverlapping pairs in a chain.','Take available pairs by earliest finish. Leaving the earliest possible endpoint gives later pairs the most room.',['sort pairs by end; end = negative infinity','for start, finish in pairs:','    check start > end','    if true, take pair and set end = finish','return number of taken pairs'],'O(n log n) time; O(n) sorted-copy space.'],
  657:['moves','Decide whether the robot returns to its starting position.','Track horizontal and vertical displacement separately. Returning requires both totals to become zero.',['x = y = 0','for move in moves:','    read the direction displacement','    update x and y','return x == 0 and y == 0'],'O(n) time; O(1) state.'],
  658:['arr k x','Return the k closest values in sorted order, preferring smaller values on distance ties.','Trim the worse endpoint of a sorted range until exactly k values remain. On a tie remove the larger endpoint.',['left = 0; right = n-1','while remaining length > k:','    compare endpoint distances from x','    discard left if farther, otherwise right','return arr[left:right+1]'],'O(n) time; O(k) output space.'],
  661:['img','Replace each pixel with the floored average of its valid surrounding 3×3 neighborhood.','At boundaries use only neighbors that exist. Read the original matrix throughout so updated averages never contaminate later cells.',['allocate output image','for every pixel:','    sum existing neighboring pixels and count them','    write floor(sum / count) into output','return output'],'O(rows × columns) time and output space.'],
  665:['nums','Decide whether at most one changed value can make the array nondecreasing.','At a drop, lower the previous value when the earlier boundary permits it; otherwise raise the current value. A second drop exhausts the budget.',['copy nums; edits = 0','for each adjacent boundary:','    if current < previous, an edit is needed','    lower previous or raise current; reject second edit','return true'],'O(n) time; O(n) working-copy space.'],
  670:['num','Maximize a number using at most one swap of two digits.','Improve the earliest digit possible. Swap with the rightmost occurrence of the greatest larger digit to keep the remaining suffix maximal.',['record last position of every digit','for each digit from left:','    look for a larger digit farther right','    swap with rightmost greatest candidate, then stop','return resulting number'],'O(d) time and space for d digits.'],
  673:['nums','Count the longest strictly increasing subsequences by index choices.','For each ending position track both the best length and its number of constructions. A better length replaces the count; an equal length adds ways.',['length[i] = ways[i] = 1','for i, inspect every earlier j:','    consider j only when nums[j] < nums[i]','    improve length or accumulate ways on equal length','return sum of ways at the global greatest length'],'O(n²) time; O(n) DP state.'],
  678:['s','Decide whether stars can represent empty strings or parentheses to balance the string.','Track the minimum and maximum feasible number of unmatched openers. Negative maximum means failure; final minimum zero means success.',['low = high = 0','for character in s:','    update feasible open-count interval','    reject negative high; clamp low to zero','return low == 0'],'O(n) time; O(1) state.'],
  680:['s','Decide whether deleting at most one character can produce a palindrome.','Matching endpoints can stay. At the first mismatch, only deleting the left or right endpoint can repair that pair.',['left = 0; right = n-1','while endpoints match, move inward:','    on mismatch try skipping either endpoint','    require the remaining substring to be a palindrome','return whether either choice succeeds'],'O(n) time; O(1) auxiliary state.'],
  682:['operations','Compute the total of valid baseball rounds after cancel, double, and sum operations.','A stack stores only valid rounds. Derived scores use the current stack, so canceled rounds immediately disappear from future calculations.',['stack = []','for operation:','    distinguish score, cancel, double, or sum','    modify valid-round stack','return sum(stack)'],'O(n) time and space.'],
  686:['a b','Find the fewest repeats of a that contain b as a contiguous substring.','Try enough copies to cover the target length plus one extra for a target that crosses copy boundaries. More copies cannot create a new alignment.',['text = empty; limit = ceil(len(b)/len(a)) + 1','repeat a up to limit times:','    check whether b is inside text','    return current repeat count on first match','return -1 if absent'],'O((|a|+|b|) × ceil(|b|/|a|)) substring-search work in this direct teaching implementation.'],
  692:['words k','Return the k most frequent words, resolving ties alphabetically.','Count exact words first, then sort frequency descending and word ascending. Ranking without the secondary key gives incorrect ties.',['counts = word frequencies','rank all distinct words:','    compare frequency descending, then word ascending','    take first k ranked words','return selected words'],'O(n + u log u) time and O(u) space for u distinct words.'],
  693:['n','Decide whether adjacent bits in the binary representation always differ.','Compare consecutive bits without adding leading zeros. One repeated neighboring bit disproves alternation.',['bits = binary digits of n','for every adjacent bit pair:','    compare the two bits','    reject if equal','return true'],'O(log n) time and representation space.'],
  696:['s','Count substrings with equal-sized consecutive runs of zeros and ones.','A boundary between runs of lengths a and b contributes min(a,b) valid substrings. Nonadjacent runs cannot combine into a grouped substring.',['previous = 0; current = 1; total = 0','for each next bit:','    detect whether its run continues','    extend current or add min(previous,current) and roll runs','return total + min(previous,current)'],'O(n) time; O(1) state.'],
  709:['s','Convert uppercase English letters to lowercase while preserving all other characters.','Only ASCII codes A through Z shift by 32. Lowercase letters, punctuation, spaces, and digits keep their original values.',['output = []','for character in s:','    test ASCII code between 65 and 90','    append shifted code or unchanged character','return joined output'],'O(n) time and output space.'],
  713:['nums k','Count contiguous subarrays whose product is strictly smaller than k.','Positive numbers permit a sliding window: remove left values until the product is small enough, then count every suffix ending at the right edge.',['left = 0; product = 1; count = 0','for right, value in nums:','    multiply in value; shrink while product >= k','    add right-left+1 valid endings','return count (zero immediately when k <= 1)'],'O(n) time; O(1) state.'],
  714:['prices fee','Maximize profit with any number of nonoverlapping stock trades and a fee per sale.','Keep best cash and best held-stock profit. Read the previous day states for both transitions so one update cannot contaminate the other.',['cash = 0; hold = -prices[0]','for each later day:','    compare staying put with selling or buying','    update cash and hold from previous states','return cash'],'O(n) time; O(1) state.'],
  717:['bits','Decide whether the last zero is a one-bit character.','Decode from the beginning: zero consumes one bit and one consumes two. The last zero stands alone only if decoding lands exactly on it.',['index = 0','while index is before the final bit:','    read leading bit to determine character width','    advance by one for zero or two for one','return index == final index'],'O(n) time; O(1) state.'],
  718:['nums1 nums2','Find the length of the longest contiguous block shared by both arrays.','DP cell (i,j) stores the common suffix length ending at those prefixes. Matching values extend the northwest cell; a mismatch resets to zero.',['dp = zero matrix; best = 0','for prefix lengths i and j:','    compare nums1[i-1] and nums2[j-1]','    write northwest+1 on match, else zero; update best','return best'],'O(nm) time and space.'],
  728:['left right','List numbers in the inclusive interval divisible by every one of their own digits.','Reject zero digits immediately. Every other digit must divide the original whole number, not the remaining quotient.',['output = []','for candidate in [left, right]:','    inspect every decimal digit','    append if no zero and every remainder is zero','return output'],'O(range length × digit count) time; output space.'],
  733:['image sr sc color','Recolor the starting pixel’s orthogonally connected component of equal-colored pixels.','Use a queue and mark pixels when enqueuing. Only pixels of the original color join the component; diagonal contact does not connect regions.',['copy image; remember original color','process queued matching pixels:','    inspect four orthogonal neighbors','    recolor and enqueue previously unvisited matches','return recolored image'],'O(rows × columns) time and space.'],
  735:['asteroids','Return the surviving asteroids after all collisions.','A stack contains survivors in order. A collision is possible only when its top moves right and the next asteroid moves left.',['stack = []','for incoming asteroid:','    while top moves right and incoming moves left, compare sizes','    remove smaller or both on equality; append surviving incoming','return stack'],'O(n) time and space.'],
  738:['n','Find the largest integer no greater than n with nondecreasing decimal digits.','Repair descents right to left so a decrement can propagate. Fill the affected suffix with nines to maximize the remaining value.',['digits = decimal digits; mark = length','scan boundaries from right to left:','    if left digit exceeds right digit:','        decrement left; mark suffix, then fill suffix with nines','return repaired integer'],'O(d) time and space.'],
  740:['nums','Maximize points when taking a value removes all occurrences of its neighboring values.','Combine equal values into one reward bucket. The sorted distinct values then form a take-or-skip DP with conflicts only between consecutive numbers.',['points = grouped value sums; take = skip = 0','for each distinct value in sorted order:','    check whether prior value is consecutive','    update take and skip, excluding conflicting neighbor','return max(take,skip)'],'O(n + u log u) time; O(u) space.'],
  744:['letters target','Find the smallest letter strictly greater than target, wrapping around if needed.','Binary-search the first strictly greater position. If it lies beyond the array, return the first letter.',['left = 0; right = length','while left < right:','    compare middle letter with target','    keep left half if greater, otherwise move beyond middle','return letters[left modulo length]'],'O(log n) time; O(1) state.'],
  771:['jewels stones','Count stones whose case-sensitive type occurs in the jewel set.','Build a membership set once and test every stone independently. Repeated stones each contribute, while letter case remains significant.',['set = jewel types; count = 0','for stone in stones:','    test membership in set','    increment count when present','return count'],'O(j + s) time; O(j) space.'],
  796:['s goal','Decide whether repeatedly moving the first character to the end can produce goal.','A rotation preserves length and cyclic order. Compare every cut position, including the unchanged string.',['reject different lengths','for each rotation offset:','    compare suffix+prefix with goal','    return true on the first matching rotation','return false'],'O(n²) time and O(n) temporary space in this direct rotation trace.'],
  804:['words','Count distinct Morse encodings of the supplied lowercase words.','Encode characters with the standard Morse alphabet and concatenate without separators. Different words may map to the same combined code.',['seen = set of encodings','for word in words:','    look up each character’s Morse code','    concatenate and insert into seen','return size(seen)'],'O(total characters) time and stored-encoding space.'],
  806:['widths s','Return the number of lines and final-line width when writing letters into 100-unit lines.','Test whether each next letter fits before writing it. Exactly 100 units fits; only a strictly larger width wraps.',['lines = 1; width = 0','for letter in s:','    compare width + letterWidth with 100','    start new line if needed, then add letter width','return [lines,width]'],'O(n) time; O(1) state.'],
  821:['s c','Find each position’s distance to its nearest occurrence of c.','A left-to-right pass finds the nearest target on the left. A right-to-left pass compares the nearest target on the right.',['distances = unknown','scan left to right, then right to left:','    remember latest target position in this direction','    minimize each position’s distance','return distances'],'O(n) time and output space.'],
  830:['s','Return inclusive start and end indices of character runs at least three long.','A run ends when the next character changes or the string ends. Evaluate its full length before starting the next group.',['start = 0; output = []','scan through end-of-string sentinel:','    detect end of the current character run','    record [start,end] if length >= 3; start next run','return output'],'O(n) time; output space.'],
  836:['rec1 rec2','Decide whether two axis-aligned rectangles overlap with positive area.','Intersect projections independently on both axes. A zero-width or zero-height intersection is only touching, not positive-area overlap.',['read both rectangles','intersect horizontal and vertical ranges:','    compute minimum upper minus maximum lower boundary','    require both intersection lengths strictly positive','return overlap decision'],'O(1) time and space.'],
  844:['s t','Compare the final texts after treating # as backspace.','Reduce each text with a character stack. Backspacing an empty stack has no effect, and only surviving characters participate in the final comparison.',['create an empty stack for each text','for each character in each text:','    distinguish backspace from a normal character','    pop if backspace, otherwise push','return equality of reduced strings'],'O(n + m) time and space.'],
  849:['seats','Choose an empty seat maximizing its distance to the nearest occupied seat.','Leading and trailing gaps have one occupied boundary. Interior gaps have two, so the best possible minimum distance is half their endpoint spacing.',['lastOccupied = -1; best = 0','for occupied seats from left to right:','    distinguish leading gap from interior gap','    compare its best distance; remember occupied index','return max(best, trailing gap length)'],'O(n) time; O(1) state.'],
  852:['arr','Find the peak index of a strictly increasing then strictly decreasing mountain.','At the midpoint, an ascending edge puts the peak to the right. A descending edge keeps the midpoint as a possible peak.',['left = 0; right = n-1','while left < right:','    compare arr[mid] with arr[mid+1]','    move left beyond mid on ascent, otherwise set right=mid','return left'],'O(log n) time; O(1) state.'],
  856:['s','Compute the recursive score of a balanced parentheses string.','Only primitive empty pairs contribute directly. Each enclosing pair doubles that contribution, so add two to the power of the enclosing depth.',['depth = score = 0','for each parenthesis:','    detect immediate empty pair when closing','    add 2^depth for that pair after decreasing depth','return score'],'O(n) time; O(1) state.'],
  859:['s goal','Decide whether swapping exactly two positions in s can produce goal.','Two differing positions must cross-match. Identical strings require a repeated character so a swap can leave the visible text unchanged.',['differences = []; reject unequal lengths','for each index:','    compare source and goal characters','    record mismatches; evaluate cross-match or repeated-character case','return whether exactly one swap is possible'],'O(n) time and space.'],
};

function validate(id,input) {
  if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Use a JSON object with the named fields.');
  for(const field of specs[id][0].split(' '))if(!(field in input))throw new Error(`Missing ${field}.`);
  const fail=message=>{throw new Error(message);};
  const vector=(a,min=1,max=80)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(n=>Number.isSafeInteger(n)&&Math.abs(n)<=10000);
  const text=s=>typeof s==='string'&&s.length>=1&&s.length<=120;
  const list=a=>Array.isArray(a)&&a.length>=1&&a.length<=60&&a.every(s=>text(s)&&s.length<=25);
  const integer=(n,min=0,max=10000)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
  for(const key of ['nums','arr','prices','bits','asteroids','seats','widths','rec1','rec2','nums1','nums2'])if(key in input&&!vector(input[key]))fail(`${key}: use 1–80 bounded integers.`);
  for(const key of ['s','t','moves','a','b','goal','jewels','stones'])if(key in input&&!text(input[key]))fail(`${key}: use 1–120 characters.`);
  for(const key of ['words','list1','list2','letters'])if(key in input&&!list(input[key]))fail(`${key}: use 1–60 nonempty strings, at most 25 characters each.`);
  for(const key of ['image','img'])if(key in input){const a=input[key];if(!Array.isArray(a)||a.length<1||a.length>12||!a.every(row=>vector(row,1,12)&&row.length===a[0].length&&row.every(v=>v>=0&&v<=255)))fail(`${key}: use a rectangular 1–12 by 1–12 matrix with values 0–255.`);}
  if(id===598&&(!integer(input.m,1,100)||!integer(input.n,1,100)||!Array.isArray(input.ops)||input.ops.length>60||!input.ops.every(p=>Array.isArray(p)&&p.length===2&&integer(p[0],1,input.m)&&integer(p[1],1,input.n))))fail('Use positive m,n ≤ 100 and operations within those dimensions.');
  if(id===599&&(new Set(input.list1).size!==input.list1.length||new Set(input.list2).size!==input.list2.length||!input.list1.some(v=>input.list2.includes(v))))fail('Each list must have unique strings and the lists must share at least one string.');
  if(id===646&&(!Array.isArray(input.pairs)||input.pairs.length<1||input.pairs.length>40||!input.pairs.every(p=>vector(p,2,2)&&p[0]<p[1])))fail('Use 1–40 pairs with start < end.');
  if(id===657&&!/^[UDLR]+$/.test(input.moves))fail('Moves must contain only U,D,L,R.');
  if(id===658&&(!integer(input.k,1,input.arr.length)||!integer(input.x,-10000)||input.arr.some((v,i,a)=>i&&v<a[i-1])))fail('arr must be sorted, k must fit, and x must be an integer.');
  if([670,738,693].includes(id)&&!integer(input.num??input.n,id===693?1:0,999999999))fail('Use an integer from the problem domain through 999999999.');
  if(id===673&&input.nums.length>30)fail('Use at most 30 numbers so all subsequence counts and the detailed DP trace remain bounded.');
  if(id===678&&!/^[()*]+$/.test(input.s))fail('Only (, ), and * are allowed.');
  if([680,796,821,830,859].includes(id)&&!['s',...(['goal'].filter(k=>k in input))].every(k=>/^[a-z]+$/.test(input[k])))fail('Use lowercase English letters.');
  if(id===682){if(!Array.isArray(input.operations)||input.operations.length<1||input.operations.length>80)fail('Use 1–80 operations.');let depth=0;for(const op of input.operations){if(typeof op!=='string')fail('Operations must be strings.');if(op==='C'){if(!depth)fail('Cancel needs one valid score.');depth--;}else if(op==='D'){if(!depth)fail('Double needs one valid score.');depth++;}else if(op==='+'){if(depth<2)fail('Sum needs two valid scores.');depth++;}else if(/^-?\d+$/.test(op)&&integer(Number(op),-10000))depth++;else fail('Use integer scores, C, D, or +.');}let stack=[];for(const op of input.operations){if(op==='C')stack.pop();else if(op==='D')stack.push(2*stack.at(-1));else if(op==='+')stack.push(stack.at(-1)+stack.at(-2));else stack.push(Number(op));if(!stack.every(Number.isSafeInteger)||!Number.isSafeInteger(stack.reduce((a,b)=>a+b,0)))fail('Scores exceed safe integer range.');}}
  if([692,804].includes(id)&&!input.words.every(w=>/^[a-z]+$/.test(w)))fail('Use lowercase English words.');
  if(id===692&&!integer(input.k,1,new Set(input.words).size))fail('k must fit the distinct-word count.');
  if(id===696&&!/^[01]+$/.test(input.s))fail('Use a nonempty binary string.');
  if(id===709&&![...input.s].every(c=>c.charCodeAt(0)>=32&&c.charCodeAt(0)<=126))fail('This ASCII exercise accepts printable ASCII characters.');
  if(id===713&&(input.nums.some(v=>v<1||v>1000)||!integer(input.k,0,1000000)))fail('Use positive values ≤ 1000 and a nonnegative threshold ≤ 1000000.');
  if(id===714&&(input.prices.some(v=>v<1)||!integer(input.fee)))fail('Prices must be positive and fee a nonnegative integer.');
  if(id===717&&(!input.bits.every(v=>v===0||v===1)||input.bits.at(-1)!==0))fail('Use binary bits ending with zero.');
  if(id===718&&(input.nums1.length>12||input.nums2.length>12||input.nums1.some(v=>v<0)||input.nums2.some(v=>v<0)))fail('Use up to 12 nonnegative values in each array for the DP scene.');
  if(id===728&&(!integer(input.left,1)||!integer(input.right,input.left)||input.right-input.left>200))fail('Use 1 ≤ left ≤ right ≤ 10000, with interval width at most 200.');
  if(id===733&&(!integer(input.sr,0,input.image.length-1)||!integer(input.sc,0,input.image[0].length-1)||!integer(input.color,0,255)))fail('Start coordinates must be inside the image and color must be 0–255.');
  if(id===735&&input.asteroids.includes(0))fail('Asteroid size cannot be zero.');
  if(id===740&&input.nums.some(v=>v<1))fail('Use positive values.');
  if(id===744&&(!input.letters.every((v,i,a)=>/^[a-z]$/.test(v)&&(!i||v>=a[i-1]))||typeof input.target!=='string'||!/^[a-z]$/.test(input.target)||new Set(input.letters).size<2))fail('Use sorted lowercase single letters with at least two distinct entries, and a single target letter.');
  if(id===771&&(!/^[a-zA-Z]+$/.test(input.jewels)||!/^[a-zA-Z]+$/.test(input.stones)||new Set(input.jewels).size!==input.jewels.length))fail('Use distinct alphabetic jewel types and alphabetic stones.');
  if(id===806&&(input.widths.length!==26||input.widths.some(v=>v<2||v>10)||!/^[a-z]+$/.test(input.s)))fail('Provide 26 widths from 2 to 10 and a lowercase string.');
  if(id===821&&(typeof input.c!=='string'||!/^[a-z]$/.test(input.c)||!input.s.includes(input.c)))fail('c must be one lowercase character present in s.');
  if(id===836&&![input.rec1,input.rec2].every(r=>r.length===4&&r[0]<r[2]&&r[1]<r[3]))fail('Each rectangle is [left,bottom,right,top] with positive width and height.');
  if(id===844&&![input.s,input.t].every(s=>/^[a-z#]+$/.test(s)))fail('Use lowercase letters and # only.');
  if(id===849&&(!input.seats.every(v=>v===0||v===1)||!input.seats.includes(0)||!input.seats.includes(1)))fail('Use binary seats with both occupied and empty positions.');
  if(id===852){const a=input.arr;let peak=0;while(peak+1<a.length&&a[peak+1]>a[peak])peak++;if(peak===0||peak===a.length-1||!a.slice(peak+1).every((v,i)=>v<a[peak+i]))fail('Use a strict mountain with increasing and decreasing sides.');}
  if(id===856){let depth=0;if(!/^[()]+$/.test(input.s)||input.s.length>60)fail('Use up to 60 balanced parentheses.');for(const c of input.s){depth+=c==='('?1:-1;if(depth<0)fail('Parentheses must be balanced.');}if(depth)fail('Parentheses must be balanced.');}
  return input;
}

function sourceFor(id,input) {
  if(id===598)return input.ops.map(p=>`[${p}]`);
  if(id===646)return input.pairs.map(p=>`[${p}]`);
  if(id===806)return input.s;
  if(id===771)return input.stones;
  if(id===836)return [`A: ${input.rec1}`,`B: ${input.rec2}`];
  const value=input[specs[id][0].split(' ')[0]];
  return typeof value==='number'?[...String(value)]:value;
}

export const definitions=Object.fromEntries(Object.entries(specs).map(([key,[fields,goal,strategy,lines,complexity]])=>{
  const id=Number(key),meta=scanStoryMetadata[id];
  return [id,{...meta,goal,strategy,complexity,inputLabel:`${fields} (JSON; bounded for a readable trace)`,
    code:lines.map((text,i)=>({line:i+1,text})),examples:scanStoryExamples[id],
    phases:[{id:'start',label:'Set up',description:goal},{id:'inspect',label:'Decide',description:strategy},{id:'update',label:'Record progress',description:strategy},{id:'done',label:'Return',description:goal}],
    parse:text=>validate(id,JSON.parse(text)),
    build:raw=>{const input=validate(id,raw),sequence=sourceFor(id,input),frames=[];
      const emit=(message,state={},phase='inspect')=>frames.push(structuredClone({sequence,index:-1,metrics:{},...state,message,phase,activeLine:{start:1,inspect:3,update:4}[phase]}));
      emit(goal,{},'start');const result=solvers[id](input,emit);
      frames.push({...frames.at(-1),phase:'done',activeLine:5,message:`Return ${JSON.stringify(result)}. ${goal}`,result:structuredClone(result)});
      return {frames,result};
    },
  }];
}));
