import {useState,useMemo,useCallback} from 'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import FloatingPanel from '../../components/shared/FloatingPanel'
import {usePlaybackState} from '../../hooks/usePlaybackState'
import {useCodeVisualConnectivity} from '../../hooks/useCodeVisualConnectivity'
import {getExamplesOr} from '../../config/examplesRegistry'
import {createPortal} from 'react-dom'
import './NumberofIslandsIIVisualizer.css'
const CODE=[{line:1,text:'def numIslands2(m, n, positions):'},{line:2,text:'    parent = list(range(m * n)); land = set(); count = 0'},{line:3,text:'    for row, col in positions:'},{line:4,text:'        if (row, col) in land: yield count; continue'},{line:5,text:'        land.add((row, col)); count += 1'},{line:6,text:'        for nr, nc in four_neighbors(row, col):'},{line:7,text:'            if (nr, nc) in land and union(row, col, nr, nc):'},{line:8,text:'                count -= 1'},{line:9,text:'        yield count'}]
function trace({m,n,positions}){const parent=Array.from({length:m*n},(_,i)=>i),land=new Set(),steps=[{phase:'init',activeLine:2,message:'Every grid cell begins as its own possible union-find root.',land:[],count:0,active:null,parents:[...parent]}];const id=(r,c)=>r*n+c;const find=x=>{while(parent[x]!==x){parent[x]=parent[parent[x]];x=parent[x]}return x};for(const [r,c] of positions){const key=`${r},${c}`;if(land.has(key)){steps.push({phase:'process',activeLine:4,message:`(${r}, ${c}) is already land; island count stays unchanged.`,land:[...land],count:[...land].length?steps.at(-1).count:0,active:key,parents:[...parent]});continue}land.add(key);let count=(steps.at(-1).count||0)+1;steps.push({phase:'process',activeLine:5,message:`Add land at (${r}, ${c}); it starts as a new island.`,land:[...land],count,active:key,parents:[...parent]});for(const[nr,nc]of[[r-1,c],[r+1,c],[r,c-1],[r,c+1]]){const nk=`${nr},${nc}`;if(nr>=0&&nr<m&&nc>=0&&nc<n&&land.has(nk)){const a=find(id(r,c)),b=find(id(nr,nc));if(a!==b){parent[a]=b;count-=1;steps.push({phase:'process',activeLine:8,message:`Union (${r}, ${c}) with neighboring land (${nr}, ${nc}); two islands become one.`,land:[...land],count,active:key,neighbor:nk,parents:[...parent]})}}}steps.push({phase:'process',activeLine:9,message:`After this operation there ${count===1?'is':'are'} ${count} island${count===1?'':'s'}.`,land:[...land],count,active:key,parents:[...parent]})}steps.push({...steps.at(-1),phase:'done',activeLine:9,message:'All land additions have been processed.'});return steps}
const EXAMPLES=getExamplesOr('number-of-islands-ii',[{label:'Merge islands',m:3,n:3,positions:[[0,0],[0,1],[1,2],[2,1],[1,1]]}])
function parse(raw){try{const x=JSON.parse(raw);if(!Number.isInteger(x.m)||!Number.isInteger(x.n)||x.m<1||x.n<1||!Array.isArray(x.positions)||!x.positions.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isInteger)&&p[0]>=0&&p[0]<x.m&&p[1]>=0&&p[1]<x.n))throw Error('Use m, n, and in-bounds [row, col] positions.');return {input:x,inputError:''}}catch(e){return {input:null,inputError:e.message}}}
export default function NumberofIslandsIIVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?trace(input).map(s=>({...s,relatedLines:[s.activeLine]})):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'grid',title:'Dynamic islands',dockMode:'split-right'},{id:'state',title:'Operations',dockMode:'split-bottom'}],[]);const contents={input:<div className="numberof-islands-i-i-panel"><div className="numberof-islands-i-i-panel-body"><textarea className="numberof-islands-i-i-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,grid:!input?<div className="numberof-islands-i-i-error">{inputError}</div>:<div className="numberof-islands-i-i-panel"><div className="numberof-islands-i-i-panel-body"><div className="numberof-islands-i-i-step-info"><h3>{step?.message||'Press play to add land.'}</h3></div><div className="numberof-islands-i-i-grid" style={{gridTemplateColumns:`repeat(${input.n}, minmax(38px, 1fr))`}}>{Array.from({length:input.m*input.n},(_,i)=>{const key=`${Math.floor(i/input.n)},${i%input.n}`;return <b key={key} className={`${step?.land?.includes(key)?'land':'water'} ${step?.active===key?'active':''} ${step?.neighbor===key?'neighbor':''}`}>{key}</b>})}</div><strong>islands: {step?.count||0}</strong></div></div>,state:<div className="numberof-islands-i-i-panel"><div className="numberof-islands-i-i-panel-body numberof-islands-i-i-examples">{input?.positions.map((p,i)=><span key={i}>#{i+1}: ({p.join(', ')})</span>)}{EXAMPLES.map((x,i)=><button className="numberof-islands-i-i-example-btn" key={i} onClick={()=>apply(x)}>{x.label||`Example ${i+1}`}</button>)}</div></div>};return <div className="numberof-islands-i-i-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
