import{useState,useMemo,useCallback}from'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import PointerRail from '../../components/shared/PointerRail'
import FloatingPanel from '../../components/shared/FloatingPanel'
import{usePlaybackState}from '../../hooks/usePlaybackState'
import{useCodeVisualConnectivity}from '../../hooks/useCodeVisualConnectivity'
import{getExamplesOr}from '../../config/examplesRegistry'
import{createPortal}from'react-dom'
import './AdditiveNumberVisualizer.css'
const CODE=[{line:1,text:'def isAdditiveNumber(num):'},{line:2,text:'    for first_end in range(1, len(num)):'},{line:3,text:'        for second_end in range(first_end + 1, len(num)):'},{line:4,text:'            first, second = num[:first_end], num[first_end:second_end]'},{line:5,text:'            if leading_zero(first) or leading_zero(second): continue'},{line:6,text:'            while second_end < len(num):'},{line:7,text:'                expected = str(int(first) + int(second))'},{line:8,text:'                if not num.startswith(expected, second_end): break'},{line:9,text:'                first, second = second, expected; second_end += len(expected)'},{line:10,text:'            if second_end == len(num): return True'},{line:11,text:'    return False'}]
function trace({num}){const out=[{phase:'init',activeLine:2,message:'Try each split for the first two numbers.',parts:[],cursor:0}];for(let a=1;a<num.length-1;a++){for(let b=a+1;b<num.length;b++){let x=num.slice(0,a),y=num.slice(a,b),p=b;if((x.length>1&&x[0]==='0')||(y.length>1&&y[0]==='0')){out.push({phase:'process',activeLine:5,message:`Skip ${x}, ${y}: a multi-digit number cannot start with zero.`,parts:[x,y],cursor:p});continue}out.push({phase:'process',activeLine:4,message:`Try first pair ${x}, ${y}.`,parts:[x,y],cursor:p});while(p<num.length){const z=String(BigInt(x)+BigInt(y));if(!num.startsWith(z,p)){out.push({phase:'process',activeLine:8,message:`Expected ${z} after ${x} + ${y}, but the digits do not match.`,parts:[x,y,z],cursor:p});break}p+=z.length;x=y;y=z;out.push({phase:'process',activeLine:9,message:`Match ${z}; shift the additive pair forward.`,parts:[x,y],cursor:p})}if(p===num.length){out.push({phase:'done',activeLine:10,message:'All digits form an additive sequence.',parts:[x,y],cursor:p,valid:true});return out}}}out.push({phase:'done',activeLine:11,message:'No split consumes the string as an additive sequence.',parts:[],cursor:0,valid:false});return out}
const EXAMPLES=getExamplesOr('additive-number',[{label:'112358',num:'112358'},{label:'not additive',num:'1023'}])
function parse(raw){try{const x=JSON.parse(raw);if(typeof x.num!=='string'||!/^[0-9]{3,}$/.test(x.num))throw Error('Use { "num": "at least three digits" }.');return{input:x,inputError:''}}catch(e){return{input:null,inputError:e.message}}}
export default function AdditiveNumberVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?trace(input).map(s=>({...s,relatedLines:[s.activeLine]})):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'trace',title:'Additive parser',dockMode:'split-right'},{id:'examples',title:'Examples',dockMode:'split-bottom'}],[]);const contents={input:<div className="additive-number-panel"><div className="additive-number-panel-body"><textarea className="additive-number-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,trace:!input?<div className="additive-number-error">{inputError}</div>:<div className="additive-number-panel"><div className="additive-number-panel-body"><div className="additive-number-step-info"><h3>{step?.message||'Press play to try additive splits.'}</h3></div><PointerRail title="Digit cursor" values={[...input.num]} pointers={[{id:'cursor',label:'next',index:Math.min(step?.cursor||0,input.num.length-1),tone:'primary'}]}/><div className="additive-number-parts">{(step?.parts||[]).map((part,i)=><b key={i}>{part}</b>)}</div><strong>{step?.valid===undefined?'':'valid additive sequence: '+step.valid}</strong></div></div>,examples:<div className="additive-number-panel"><div className="additive-number-panel-body additive-number-examples">{EXAMPLES.map((x,i)=><button className="additive-number-example-btn" key={i} onClick={()=>apply(x)}>{x.label||x.num}</button>)}</div></div>};return <div className="additive-number-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
