// Boundary behavior for implementations without an explicit early-return guard.
export const catalogEdgeCases = {
  'CF-F': 'Each insertion adds a new node beneath an existing parent; use the tree state after that insertion rather than reusing a score from a different prefix.',
  11: 'The shorter endpoint limits the water height; moving the taller endpoint alone cannot improve that pair at a smaller width.',
  114: 'Save the original right subtree before rewiring left links; the final chain must preserve preorder and clear every left pointer.',
  115: 'An empty target has one matching subsequence. Repeated source characters create different index choices even when their text is identical.',
  126: 'Keep all predecessors at the shortest distance; stopping at the first discovered path would lose other shortest ladders.',
  143: 'Split and reverse the second half before interleaving; an odd-length list leaves one extra node in the first half.',
  146: 'Reading a cached key refreshes recency; updating an existing key must not consume an additional capacity slot.',
  149: 'Vertical lines need a separate slope representation, and repeated coordinates must count without dividing by zero.',
  152: 'A negative value exchanges the roles of maximum and minimum ending products; zero can restart a segment.',
  153: 'The array may already be sorted; comparing against the right boundary still retains the minimum.',
  154: 'Equal boundary values can hide the pivot, requiring one-at-a-time shrinking instead of a guaranteed halving step.',
  160: 'Intersection means the same node object, not merely equal values; two disjoint lists eventually align at null.',
  162: 'An endpoint may be a peak under the virtual negative-infinity boundary convention; the peak need not be the global maximum.',
  173: 'An iterator must keep enough pending ancestors to resume inorder traversal without returning a node twice.',
  174: 'Health must remain at least one at every cell; the cheapest total sum alone does not determine the needed starting health.',
  189: 'Reduce k modulo array length; a full-length rotation returns the original order.',
  190: 'Reverse exactly the specified bit width, including leading zeros; signed display must not change the bit pattern.',
  191: 'Zero contains no one bits; clearing the lowest set bit must eventually terminate for the chosen fixed width.',
  202: 'One ends the process successfully; revisiting a non-one value proves the digit-square process is cycling.',
  203: 'Several consecutive matches may include the head; removing one must not skip inspecting the next node.',
  206: 'Save the next node before reversing a link; null and one-node lists need no multi-node rewiring.',
  209: 'The shrinking-window proof assumes positive values; if no window reaches the target, the minimum length is zero.',
  210: 'A cycle prevents a complete topological ordering; independent zero-indegree courses can have several valid orders.',
  214: 'Only the longest palindromic prefix can remain untouched when characters may be added at the front only.',
  215: 'Duplicates occupy separate ranks; kth largest is not kth distinct largest.',
  218: 'Process events at the same x coordinate together so temporary height changes do not create spurious skyline points.',
  22: 'A prefix cannot contain more closing than opening parentheses; completion requires exactly n of each.',
  223: 'Touching rectangles have zero overlap area; clamp negative overlap widths or heights to zero before multiplying.',
  227: 'Multiplication and division bind before addition and subtraction; integer division truncates toward zero.',
  23: 'Some input lists may be empty; every chosen minimum must expose only that list’s next candidate.',
  235: 'If the current node equals either target, it can be the ancestor; otherwise use BST ordering to choose a side or the split point.',
  238: 'Zero values prevent a division-based solution; prefix and suffix products naturally handle one or multiple zeros.',
  251: 'Skip empty inner vectors before reading; repeated hasNext calls must not consume an element.',
  253: 'A room can be reused when a meeting ends exactly as another begins; the peak concurrent count determines capacity.',
  254: 'Exclude the trivial factorization containing only n, and keep factors nondecreasing to avoid reordered duplicates.',
  256: 'Neighboring houses cannot choose the same color; each current color compares only the other preceding colors.',
  258: 'Zero stays zero; positive multiples of nine map to nine rather than zero.',
  259: 'After sorting, a pair sum below target can certify several smaller-right-end choices at once; the inequality is strict.',
  26: 'Only the compacted prefix is the result; equal adjacent values must not advance the write position.',
  260: 'The XOR of the two singles has a set bit because they differ; use that bit to separate them before canceling pairs.',
  265: 'The cheapest previous color cannot be reused for the same current color; retain the second-best alternative too.',
  266: 'At most one character may have odd multiplicity for any permutation to form a palindrome.',
  268: 'The missing value may be zero or n; the comparison range includes both endpoints.',
  269: 'A longer word before its exact prefix makes the ordering invalid; a cycle also prevents an alphabet order.',
  270: 'The target need not be stored in the BST; retain the closest candidate before following the next search branch.',
  271: 'Empty strings and delimiter characters inside strings must round-trip; length information must distinguish data from separators.',
  278: 'Keep the first failing version inside the search interval; finding any failing version is not enough.',
  279: 'A perfect square needs one term; repeated use of the same square is allowed.',
  280: 'Adjacent inequalities alternate; equal values can satisfy non-strict wiggle ordering.',
  281: 'When one input ends, continue returning values from the other without trying to alternate into an empty source.',
  282: 'A multi-digit operand cannot have a leading zero; multiplication must adjust the previous term to preserve precedence.',
  283: 'Retain the relative order of nonzero values while moving zeros to the tail.',
  284: 'Peeking twice must return the same value; only next consumes the cached element.',
  285: 'A right subtree supplies its leftmost node; otherwise the successor is an ancestor reached from a left branch.',
  286: 'All gates are simultaneous distance-zero sources; walls remain impassable and unreachable rooms keep their sentinel.',
  288: 'A dictionary containing the same word repeatedly does not create an abbreviation conflict with itself.',
  289: 'All updates use the original generation; an in-place encoding must retain old state until every neighbor count is read.',
  291: 'The character-to-substring mapping is bijective: different pattern characters cannot share a substring.',
  292: 'A pile size divisible by four is losing under optimal play; the final legal removal wins.',
  293: 'Only adjacent plus signs can flip; each distinct starting pair describes a separate next state.',
  294: 'A move is winning only if it leaves the opponent no winning reply; having any legal move does not alone prove a win.',
  296: 'Row and column travel costs separate, and each is minimized at a median; the meeting point need not contain a person.',
  297: 'Null markers preserve missing-child positions; equal node values do not uniquely describe tree structure.',
  298: 'Only parent-to-child values increasing by exactly one extend the current run; other edges restart its length.',
  300: 'Strictly increasing subsequences cannot extend with an equal value; replacing a tail need not mean that tail list itself is the final witness.',
  302: 'The supplied black-pixel seed must belong to the component; extreme occupied rows and columns define the enclosing area.',
  303: 'An inclusive query uses prefix[right+1] minus prefix[left]; a query beginning at zero still needs the empty prefix.',
  304: 'Two-dimensional range sums subtract both outside strips and add their overlap back once.',
  305: 'Adding land twice at the same position does not create a new island; neighboring cells may already belong to one component.',
  307: 'An update replaces a value, so propagate its difference rather than adding the replacement value itself.',
  308: 'A cell update affects multiple two-dimensional index blocks; query rectangles require inclusion-exclusion.',
  310: 'One or two centers can remain after leaf peeling; a single-node tree needs no peeling round.',
  312: 'Choose the last balloon inside an interval so its two surviving outside neighbors are known; choosing the first does not separate subproblems.',
  313: 'Several prime factors may produce the same next number; advance every matching candidate to avoid duplicate sequence entries.',
  314: 'Nodes sharing a column preserve the required top-to-bottom and traversal tie order; column position alone does not determine output order.',
  315: 'Equal values are not smaller; only elements strictly to the right contribute to each count.',
  317: 'An empty cell qualifies only if every building can reach it; a low partial distance from one building is insufficient.',
  318: 'Words with repeated letters still use one membership bit per letter; any shared letter disqualifies a pair.',
  321: 'Equal leading merge digits require comparing remaining suffixes, not choosing arbitrarily by the current digit.',
  322: 'An unreachable amount needs a failure sentinel rather than zero coins; coins may be reused.',
  324: 'The required inequalities are strict; grouping equal median values incorrectly can leave an invalid adjacent pair.',
  325: 'Keep the earliest index of each prefix sum to maximize subarray length; negative values are allowed.',
  327: 'Count prefix-sum differences in the inclusive lower-to-upper range; equal prefixes represent distinct endpoints.',
  330: 'When all sums below miss are representable, adding miss doubles the covered prefix; a larger gap cannot be skipped.',
  344: 'Swap symmetric positions only until pointers meet or cross; the middle character of odd-length input stays put.',
  346: 'Before the window fills, divide by the number of values actually seen, not the maximum window size.',
  348: 'A winning line must belong to one player; moves are assumed to be legal and placed on previously empty cells.',
  349: 'This intersection returns each common value once, regardless of duplicate occurrences.',
  353: 'Each checkout pairs with that passenger’s active check-in; averages are maintained separately for ordered station pairs.',
  362: 'Hits exactly at the expiry boundary no longer belong to the rolling window; multiple hits can share a timestamp.',
  363: 'The chosen rectangle must not exceed k; the unconstrained maximum may be invalid.',
  370: 'The end marker lies just after the inclusive update interval; omit it when that position is beyond the array.',
  381: 'Sampling must be uniform over allowed values; blacklisted values need a mapping that does not introduce collisions.',
  382: 'Reservoir sampling replaces the current choice with probability 1/i at the ith node, keeping all seen nodes equally likely.',
  384: 'Reset restores the original order; a shuffle must choose among the correct remaining positions to avoid bias.',
  3894: 'Timer zero is Green, 30 is Orange, and values strictly above 30 through 90 are Red; other accepted timers return Invalid.',
  3895: 'Repeated occurrences inside one number all count; a zero digit is counted when it appears inside a positive input number.',
  3896: 'Even indices require prime values and odd indices non-prime values; only increments are allowed, and one is non-prime.',
  3899: 'The two shorter sides must sum strictly above the longest; equality gives a degenerate triangle, not valid angles.',
  3905: 'All starting sources enter the flood together; same-layer competing arrivals must be resolved before advancing to the next layer.',
  3908: 'The target digit must occur but must not be the leading digit. Zero is represented by a single zero, so n=0 and x=0 fails the leading-digit rule.',
  3909: 'The peak belongs to both inclusive sums. Equal sums return -1; equal neighboring values and an upward turn after descending are rejected.',
  3910: 'Only nonempty connected selected subgraphs with even node-value sum count; an even sum alone is insufficient.',
  3912: 'A value qualifies by beating all values on either side, not necessarily both; equality fails the strict comparison.',
  3913: 'Frequency ties follow first occurrence rather than alphabetic order; consonants remain fixed.',
  3914: 'Only positive adjacent drops add cost; each paid increment applies to a suffix, and already non-decreasing input costs zero.',
  3915: 'Equal values cannot extend a strict rise or fall; predecessors must also be at least k indices away.',
  396: 'Each rotation moves one endpoint across the weighted sum; reuse the total sum rather than recomputing every coefficient.',
  397: 'Even values halve directly; odd values choose between neighboring evens, with small cases needing careful termination.',
  398: 'Repeated target values must have equal selection probability; selecting the first occurrence is biased.',
  400: 'Ranks cross digit-length blocks such as 9 to 10; convert the remaining rank consistently when locating the digit inside a number.',
  401: 'A bit-count match is not enough if hours exceed 11 or minutes exceed 59.',
  405: 'Zero needs an explicit digit; negative values use the specified 32-bit two’s-complement representation.',
  406: 'Process taller people before shorter ones so insertion at index k counts only people at least as tall.',
  410: 'The feasibility check asks whether a bound permits at most the allowed number of parts; zeros and exact-bound sums must not force extra splits.',
  412: 'A number divisible by both three and five uses the combined label rather than either single label.',
  414: 'The rank concerns distinct values; if fewer than three distinct values exist, return the maximum.',
  415: 'Digits are processed from the least significant end; different lengths and final carry must be preserved without numeric conversion overflow.',
  418: 'A word cannot be split across rows; a word wider than the screen prevents placing a complete sentence cycle.',
  419: 'Under the valid-board assumptions, count only the start of each ship so long ships are not counted once per cell.',
  420: 'Length, character-class and repeated-run constraints interact; one edit may satisfy more than one requirement.',
  421: 'Prefer an opposite bit at each high-to-low trie level; the first differing high bit dominates later choices.',
  469: 'Consistent turn orientation is required around the polygon; collinear triples need handling without treating zero as an opposite turn.',
  470: 'Reject excess source outcomes instead of applying a biased modulo mapping to an uneven-sized sample space.',
  474: 'Update capacities backward so one string cannot be selected multiple times during its own iteration.',
  475: 'Each house chooses its nearest heater, but the common radius is the maximum of those nearest distances.',
  476: 'Flip only the significant bits of the positive number; leading machine-word zeros are not part of its complement.',
  478: 'Uniform radius does not give uniform area; the radial sampling distribution must account for larger outer rings.',
  480: 'Expired values can be buried inside heaps; lazy deletion must preserve heap sizes and expose valid middle values.',
  481: 'Generated digits also determine later run lengths; count only the requested prefix when a final run extends past it.',
  485: 'A zero ends the current run; the maximum may occur before the final array position.',
  487: 'Track the allowed zero replacements inside the active window; exceeding the limit forces the left boundary forward.',
  489: 'After exploring a direction, restore both the robot’s position and orientation before trying the next direction.',
  490: 'The ball can stop only at a wall or boundary; passing over the destination without stopping does not finish the route.',
  494: 'Zero has two sign assignments even though both yield the same numeric sum; multiplicities must be counted.',
  496: 'The next greater value must be strictly larger and occur to the right; absence returns the sentinel.',
  497: 'Choose rectangles in proportion to their number of integer points, including their boundary coordinates.',
  500: 'Case does not change keyboard-row membership; every character of the word must belong to one row.',
  503: 'A circular second pass may resolve pending indices but must not append duplicate answer positions.',
  506: 'Rank by score while writing labels back to original positions; the first three ranks have special medal labels.',
  507: 'One is not perfect; paired divisors must not count a square root twice or include the number itself.',
  510: 'With no right subtree, climb parent links until leaving a left child; the maximum node has no successor.',
  511: 'Choose the earliest event date independently for each player, regardless of device or number of later sessions.',
  512: 'The device must come from the same record as the player’s earliest login date, not an independently chosen minimum device ID.',
  515: 'Initialize each level maximum from an actual value or negative infinity so all-negative levels are handled.',
  517: 'If total load is not divisible by machine count, balancing is impossible; both local surplus and cross-boundary flow constrain moves.',
  518: 'Count combinations rather than permutations by fixing coin order; amount zero has one empty combination.',
  519: 'Sampling must exclude previously flipped cells until reset; reset restores the full available population.',
  524: 'Candidates must be subsequences, not substrings; equal maximum lengths use the stated lexicographic tie-break.',
  525: 'Treat zeros as minus one so equal prefix balances delimit equal-count subarrays; keep the earliest index for maximum length.',
  527: 'An abbreviation must remain unique and shorter than the original; conflicting prefixes need additional distinguishing characters.',
  528: 'Sampling probability is proportional to weight, not index frequency; prefix-sum boundary handling must give each weight exactly its interval size.',
  529: 'Clicking a mine ends differently from revealing an empty region; numbered cells stop recursive expansion.',
  531: 'A black pixel qualifies only when both its entire row and entire column contain exactly one black pixel.',
  532: 'For k zero, a value needs at least two occurrences; for positive k count distinct value pairs rather than index pairs.',
  533: 'Row and column black counts alone are insufficient; the required rows sharing a candidate column must also have identical patterns.',
  534: 'Truncate timestamps to the requested granularity before the inclusive range comparison.',
  539: 'The closest pair may cross midnight; identical times produce a zero difference.',
  540: 'Pair alignment changes after the singleton; ensure comparisons use the correct even-aligned pair boundary.',
  542: 'All zero cells are simultaneous BFS sources; distance is to the nearest zero, not the first source processed alone.',
  547: 'Count connected components rather than individual friendship edges; symmetric entries describe one undirected relationship.',
  550: 'The first activity date is chosen per player; later activity records must not replace that earliest date.',
  555: 'The cut can lie inside a string; choosing an orientation independently for every untouched string differs from choosing the cut string’s orientation.',
  561: 'After sorting, pairing adjacent values maximizes the sum of pair minima; every value is used exactly once.',
  565: 'Each index belongs to a cycle under the permutation mapping; already visited indices must not be recounted indefinitely.',
  569: 'Even-sized employee groups have two middle positions, and ties need stable ordering under the query’s ranking convention.',
  570: 'Count direct reports rather than all descendants in the management tree; the threshold is inclusive.',
  571: 'The two chosen values must come from different arrays; two extremes in one array are not an eligible pair.',
  573: 'Only the first nut trip starts at the squirrel; later trips start and end at the tree, so optimize the first-trip saving.',
  575: 'The number of distinct types received cannot exceed either the available types or half the total candy count.',
  577: 'Only gaps between merged busy intervals are finite common free time; overlapping schedules must be merged first.',
  578: 'Answer rate needs both answers and shows; a zero-show denominator cannot be treated as an ordinary ratio.',
  579: 'A rolling salary window is defined by months, not merely the previous fixed number of stored rows when months are absent.',
  580: 'Departments with no students must remain in the result with count zero; counting joined rows incorrectly can produce one.',
  581: 'An already sorted array needs length zero; out-of-order interior values can extend both boundaries beyond the first inversion.',
  582: 'Killing a process includes every descendant, not just its immediate children; preserve parent-to-children direction.',
  584: 'A null referee still qualifies when excluding one referee ID; ordinary inequality alone may discard nulls in SQL.',
  721: 'Shared email identity connects accounts transitively; equal names alone do not prove the same account owner.',
  739: 'An equal temperature is not warmer; unresolved days at the end keep zero waiting time.',
  746: 'The top is beyond the final stair, and the climb may start at either of the first two steps.',
  80: 'The sorted array may retain at most two copies of each value; the write boundary, not the read index, determines the valid prefix.',
  83: 'Keep one representative of each sorted equal-value run; unlike the remove-all-duplicates variant, a repeated value still remains once.',
  875: 'Each pile requires a ceiling division in hours; the minimum feasible integer speed is the first passing boundary.',
  92: 'Reversing from position one changes the head; preserve links on both sides of the requested inclusive segment.',
  94: 'A node is emitted after its entire left subtree and before its right subtree; pending ancestors must remain available.',
  96: 'An empty subtree contributes one structural choice, allowing roots with no left or right child to count.',
  99: 'Swapped values can create one inversion or two separated inversions in inorder traversal; the tree structure itself stays unchanged.',
  994: 'All initially rotten oranges spread simultaneously; fresh oranges isolated from every source make completion impossible.',
  B1: 'A one-row or one-column matrix collapses several traversal directions; do not visit a cell twice when boundaries meet.',
  1143: 'Empty prefixes have common-subsequence length zero. Equal characters extend the diagonal; unequal characters require choosing between dropping either suffix character.',
  150: 'Pop the right operand before the left operand for subtraction and division. Division truncates toward zero.',
  151: 'Leading, trailing and repeated spaces must not become extra output words.',
  155: 'Repeated minima need independent history so popping one minimum does not lose the next minimum.',
  156: 'A missing left child stops the downward transformation; the original right child becomes the new left sibling under the stated tree-shape assumptions.',
  159: 'A third distinct character forces shrinking until one character count reaches zero; repeated characters alone do not violate the limit.',
  168: 'Column names are one-based: 26 is Z and 27 is AA. Subtract one before taking a base-26 remainder.',
  169: 'Boyer–Moore finds a candidate under the guarantee that a majority exists; without that guarantee a separate frequency check is required.',
  171: 'A means one rather than zero; each additional letter shifts the preceding total by a factor of 26.',
  172: 'Multiples of 25 contribute two factors of five, multiples of 125 contribute three; counting only multiples of five misses trailing zeros.',
  175: 'A person with no address must remain in a LEFT JOIN result with null address columns.',
  176: 'The second salary is the second distinct salary; if it does not exist, return null.',
  177: 'Duplicate salaries share a rank; if fewer than n distinct salaries exist, no nth salary is available.',
  178: 'Equal scores receive the same dense rank and do not create a gap before the next score.',
  179: 'Compare concatenations a+b and b+a, not ordinary numeric order. An all-zero input must produce a single zero.',
  180: 'A value must repeat in consecutive records, not merely appear three times anywhere.',
  181: 'Employees without a matching manager cannot satisfy a manager-salary comparison; equal salaries do not count as earning more.',
  182: 'Return each duplicated email once, even if it occurs more than twice.',
  183: 'A customer with zero matching orders is retained; multiple orders still exclude that customer only once.',
  184: 'All employees tied at their department maximum must be returned, rather than arbitrarily choosing one.',
  185: 'The top three are distinct salary levels within each department; ties can make the result contain more than three employees.',
  186: 'Reverse the whole character sequence and then each word without changing spaces into word characters.',
  187: 'Overlapping ten-character windows count. Report a repeated sequence once rather than once per repeated occurrence.',
  192: 'Repeated whitespace does not create empty words; word counts must aggregate occurrences before frequency ordering.',
  193: 'Only the supported full phone-number formats qualify; a valid-looking substring inside a longer line is insufficient.',
  194: 'The ith field from every row forms output row i; row/column indexing must not be interchanged twice.',
  195: 'A file with fewer than ten lines has no tenth line; line numbering is one-based.',
  196: 'For each duplicate email group, retain the record with the smallest ID rather than deleting every member.',
  197: 'Compare consecutive calendar dates, not simply consecutive stored rows when a date is missing.',
  201: 'Only the common high-bit prefix survives across a range; a singleton range returns its own value.',
  224: 'Nested parentheses restore the outer accumulated value and sign; a minus before parentheses applies to the whole nested result.',
  225: 'LIFO behavior must survive interleaved pushes and pops even though each underlying queue removes from its front.',
  226: 'A null subtree remains null. A leaf stays a leaf while its parent’s left/right relationship may change.',
  228: 'A one-value run is written as that value; a gap closes the preceding run even at the end of the array.',
  229: 'There can be at most two values occurring more than n/3 times; candidate voting must be followed by frequency verification.',
  232: 'Transfer into the output stack only when it is empty; transferring on every operation would disturb FIFO order.',
  233: 'At each digit position, the contribution differs depending on whether the current digit is zero, one or greater than one.',
  237: 'The supplied node must not be the tail: copy its successor value and unlink that successor to simulate deleting it.',
  239: 'Expired indices must leave the deque even if their values are large; equal values at different indices expire at different times.',
  240: 'From a sorted-matrix corner, each comparison removes one whole row or column. The target can be absent.',
  241: 'Different parenthesizations can yield the same number; retain multiplicity when each expression grouping counts as a result.',
  243: 'The closest occurrences can appear in either word order; compare positions rather than the order of query arguments.',
  244: 'Each query compares sorted occurrence lists without rebuilding the entire index; repeated occurrences can change the minimum distance.',
  245: 'When the two query words are equal, use two distinct occurrences rather than comparing an occurrence with itself.',
  246: 'Only digits with valid rotated partners qualify; a middle digit must rotate to itself.',
  247: 'Multi-digit results cannot start with zero; an odd-length center must be one of the self-rotating digits.',
  248: 'Bounds are inclusive; leading-zero strings are not separate numbers inside the range.',
  249: 'Character shifts wrap modulo 26. Single-character strings share the same empty-difference signature.',
  250: 'Equal values at a parent and child are insufficient if a deeper descendant breaks uniformity; both child subtrees must already qualify.',
  27: 'Only the returned prefix length is meaningful after compaction; overwritten or leftover values beyond that prefix are not part of the result.',
  319: 'Only perfect-square positions have an odd number of divisors and remain on; zero rounds leave no bulb on.',
  320: 'Adjacent abbreviated characters combine into one count; pending counts must be flushed before a literal character or the end.',
  332: 'Every ticket must be used once, including duplicate tickets. A locally smallest edge can be appended to the final itinerary only after its remaining trail is resolved.',
  334: 'The triplet requires strict increases at increasing indices; equal values must not count as an increase.',
  336: 'The two word indices must differ; an empty word can pair with a palindrome, and both concatenation orders may matter.',
  338: 'Zero has no set bits; each positive value reuses a smaller already-computed bit count.',
  339: 'Only integers contribute to the total; entering a nested list increases the depth weight of its contained integers.',
  343: 'At least one split is required: returning n unchanged is not valid even if it exceeds a small split product.',
  345: 'Only vowels exchange positions; consonants remain at their original indices, and letter case remains part of each character.',
  38: 'Each term describes runs in the preceding term, not counts across the entire string; the initial term is one.',
  385: 'A scalar integer and a nested list are distinct parse cases; signs and empty lists must preserve their meaning.',
  388: 'Directory names contribute to later path lengths, but only file paths compete for the answer; tab depth determines the parent.',
  389: 'Repeated characters are allowed; the extra character is identified by multiplicity, not ordinary set difference.',
  3903: 'Prefix maxima and suffix minima include the candidate index. A singleton has instability zero; return the first passing index, not the best-scoring index.',
  3904: 'The threshold comparison is inclusive. If every index fails, return -1; the large-input version must not rescan every prefix and suffix.',
  394: 'Nested repeats need separate count and prefix state; multi-digit counts are not individual repeat operations.',
  409: 'Use all available pairs and at most one odd leftover as a center; several odd counts cannot all become centers.',
  424: 'A valid window needs at most k replacements after keeping its most frequent character; repeated expansion must still respect the best-window invariant.',
  44: 'A question mark matches one character, while a star may match zero or many; empty text can match only a pattern reducible to empty.',
  466: 'Partial matches carry across repeated source blocks; an impossible required character prevents completing any target copy.',
  467: 'Wraparound adjacency includes z followed by a. Counting only the longest valid run ending in each letter avoids duplicate substrings.',
  483: 'A good base represents n using only ones; n-1 is always the two-digit fallback base.',
  484: 'Each decreasing run needs reversal as a group; reversing isolated comparisons can break neighboring constraints.',
  505: 'The final recipient may receive fewer candies than the next scheduled gift; the recipient index wraps after the last person.',
  516: 'Subsequences may skip characters. A single character has length one, and mismatching ends require choosing which end to exclude.',
  521: 'If the strings differ, the longer whole string is an uncommon subsequence; identical strings have no uncommon subsequence.',
  535: 'Different long URLs must not collide under a reused short code; decoding an unknown code must not invent a destination.',
  537: 'The imaginary-unit product contributes a negative real term; signed components must be parsed independently of the separator.',
  541: 'In a final partial block, reverse up to k available characters; leave the remainder of a 2k block unchanged.',
  544: 'The bracket construction assumes a power-of-two team count; pair opposite ends of each round until one bracket remains.',
  557: 'Reverse characters inside each word while preserving word order and separators.',
  560: 'Negative values invalidate a simple shrinking-window approach. Count all prior matching prefix sums, including the empty prefix.',
  568: 'A subsequence need not be contiguous; matching outer characters extend an inner solution while mismatches require excluding an end.',
  583: 'Only deletions are allowed. Characters retained in a common subsequence need not be deleted from either string.',
  585: 'A policy qualifies only if its previous-year value is shared and its location pair is unique; both conditions must hold.',
  586: 'Count orders per customer before choosing the maximum; the query’s tie assumptions determine whether multiple customers can qualify.',
  621: 'The cooldown separates equal tasks, not all tasks. Idle slots are unnecessary when other tasks can fill the gaps.',
  647: 'Count occurrences, not distinct text values; every character is a palindrome, and even palindromes need between-character centers.',
};
