import {useState,useMemo,useCallback} from 'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import {GraphFrontierLane} from '../../components/shared'
import FloatingPanel from '../../components/shared/FloatingPanel'
import {usePlaybackState} from '../../hooks/usePlaybackState'
import {useCodeVisualConnectivity} from '../../hooks/useCodeVisualConnectivity'
import {getExamplesOr} from '../../config/examplesRegistry'
import {createPortal} from 'react-dom'
import './MinimumHeightTreesVisualizer.css'
const CODE=[{line:1,text:'def findMinHeightTrees(n, edges):'},{line:2,text:'    graph, degree = build_adjacency(edges)'},{line:3,text:'    leaves = deque(i for i in range(n) if degree[i] == 1)'},{line:4,text:'    remaining = n'},{line:5,text:'    while remaining > 2:'},{line:6,text:'        remaining -= len(leaves)'},{line:7,text:'        for leaf in pop_this_layer(leaves):'},{line:8,text:'            degree[neighbor] -= 1'},{line:9,text:'            if degree[neighbor] == 1: leaves.append(neighbor)'},{line:10,text:'    return list(leaves)'}]
function trace({n,edges}){const g=Array.from({length:n},()=>[]),d=Array(n).fill(0);edges.forEach(([a,b])=>{g[a].push(b);g[b].push(a);d[a]++;d[b]++});let leaves=[];for(let i=0;i<n;i+=1)if(d[i]<=1)leaves.push(i);let rem=n;const S=(line,message,active=null,removed=[])=>({phase:line===10?'done':'process',activeLine:line,message,nodes:Array.from({length:n},(_,id)=>({id})),edges,activeNode:active,visited:removed,degrees:[...d],leaves:[...leaves],remaining:rem,relatedLines:[line]});const out=[S(3,`Start with all outer leaves: ${leaves.join(', ')}.`)];while(rem>2){const layer=[...leaves];leaves=[];rem-=layer.length;out.push(S(6,`Trim this outer layer (${layer.join(', ')}); ${rem} nodes remain.`,null,layer));for(const leaf of layer)for(const nb of g[leaf])if(d[nb]>0){d[nb]-=1;out.push(S(8,`Removing leaf ${leaf} lowers degree(${nb}) to ${d[nb]}.`,nb,layer));if(d[nb]===1){leaves.push(nb);out.push(S(9,`${nb} becomes a leaf for the next layer.`,nb,layer))}d[leaf]=0}}out.push(S(10,`The remaining centroid${leaves.length===1?'':'s'} ${leaves.join(', ')} minimize tree height.`));return out}
const EXAMPLES=getExamplesOr('minimum-height-trees',[{label:'Star',n:4,edges:[[1,0],[1,2],[1,3]]},{label:'Two centroids',n:6,edges:[[3,0],[3,1],[3,2],[3,4],[5,4]]}])
function parse(raw){try{const x=JSON.parse(raw);if(!Number.isInteger(x.n)||x.n<1||!Array.isArray(x.edges)||!x.edges.every(e=>Array.isArray(e)&&e.length===2&&e.every(i=>Number.isInteger(i)&&i>=0&&i<x.n)))throw Error('Use n and valid [from, to] edges.');if(x.n>1&&x.edges.length!==x.n-1)throw Error('Minimum Height Trees requires a tree (n − 1 edges).');return{input:x,inputError:''}}catch(e){return{input:null,inputError:e.message}}}
export default function MinimumHeightTreesVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?trace(input):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'graph',title:'Leaf-pruning graph',dockMode:'split-right'},{id:'state',title:'Degrees & layers',dockMode:'split-bottom'}],[]);const contents={input:<div className="minimum-height-trees-panel"><div className="minimum-height-trees-panel-body"><textarea className="minimum-height-trees-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,graph:!input?<div className="minimum-height-trees-error">{inputError}</div>:<div className="minimum-height-trees-panel"><div className="minimum-height-trees-panel-body"><div className="minimum-height-trees-step-info"><h3>{step?.message||'Press play to trim leaves.'}</h3></div><GraphFrontierLane nodes={step?.nodes||[]} edges={step?.edges||[]} activeNode={step?.activeNode} visited={step?.visited||[]} embedded/></div></div>,state:<div className="minimum-height-trees-panel"><div className="minimum-height-trees-panel-body minimum-height-trees-examples"><strong>remaining: {step?.remaining??input?.n}</strong><span>leaves: {(step?.leaves||[]).join(', ')||'—'}</span><div className="minimum-height-trees-degrees">{(step?.degrees||[]).map((d,i)=><span key={i}>{i}: {d}</span>)}</div>{EXAMPLES.map((x,i)=><button className="minimum-height-trees-example-btn" key={i} onClick={()=>apply(x)}>{x.label||`Example ${i+1}`}</button>)}</div></div>};return <div className="minimum-height-trees-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
