import { useState, useMemo, useCallback } from 'react'
import CodeTracePanel from '../../components/CodeTracePanel'
import PlaybackControls from '../../components/PlaybackControls'
import LuminoDockPanel from '../../components/LuminoDockPanel'
import { DPTable } from '../../components/shared'
import FloatingPanel from '../../components/shared/FloatingPanel'
import { usePlaybackState } from '../../hooks/usePlaybackState'
import { useCodeVisualConnectivity } from '../../hooks/useCodeVisualConnectivity'
import { getExamplesOr } from '../../config/examplesRegistry'
import { createPortal } from 'react-dom'
import './RangeSumQuery2D-ImmutableVisualizer.css'
const CODE = [{line:1,text:'class NumMatrix:'},{line:2,text:'    def __init__(self, matrix):'},{line:3,text:'        self.sum = [[0] * (n + 1) for _ in range(m + 1)]'},{line:4,text:'        for r in range(m):'},{line:5,text:'            for c in range(n):'},{line:6,text:'                sum[r+1][c+1] = matrix[r][c] + sum[r][c+1] + sum[r+1][c] - sum[r][c]'},{line:7,text:'    def sumRegion(self, r1, c1, r2, c2):'},{line:8,text:'        return sum[r2+1][c2+1] - sum[r1][c2+1] - sum[r2+1][c1] + sum[r1][c1]'}]
function stepsFor({ matrix, row1, col1, row2, col2 }) { const m=matrix.length,n=matrix[0].length,p=Array.from({length:m+1},()=>Array(n+1).fill(0)); const steps=[{phase:'init',activeLine:3,message:'Create a one-cell padded 2D prefix table.',prefix:p,active:null}]; for(let r=0;r<m;r+=1) for(let c=0;c<n;c+=1){p[r+1][c+1]=matrix[r][c]+p[r][c+1]+p[r+1][c]-p[r][c];steps.push({phase:'process',activeLine:6,message:`Build prefix[${r+1}][${c+1}] = ${p[r+1][c+1]}.`,prefix:p.map(x=>[...x]),active:{row:r+1,column:c+1}})} const result=p[row2+1][col2+1]-p[row1][col2+1]-p[row2+1][col1]+p[row1][col1];steps.push({phase:'done',activeLine:8,message:`Inclusion–exclusion answers the selected rectangle: ${result}.`,prefix:p,active:null,result,region:{row1,col1,row2,col2}});return steps }
const EXAMPLES=getExamplesOr('range-sum-query-2d-immutable',[{label:'Example',matrix:[[3,0,1,4,2],[5,6,3,2,1],[1,2,0,1,5],[4,1,0,1,7],[1,0,3,0,5]],row1:2,col1:1,row2:4,col2:3}])
function parse(raw){try{const x=JSON.parse(raw);const valid=Array.isArray(x.matrix)&&x.matrix.length&&x.matrix.every(r=>Array.isArray(r)&&r.length===x.matrix[0].length&&r.every(Number.isFinite));if(!valid)throw Error('Use a rectangular numeric matrix plus row1, col1, row2, col2.');const {row1=0,col1=0,row2=x.matrix.length-1,col2=x.matrix[0].length-1}=x;if(![row1,col1,row2,col2].every(Number.isInteger)||row1<0||col1<0||row2<row1||col2<col1||row2>=x.matrix.length||col2>=x.matrix[0].length)throw Error('Query bounds are outside the matrix.');return {input:{...x,row1,col1,row2,col2},inputError:''}}catch(e){return {input:null,inputError:e.message}}}
export default function RangeSumQuery2DImmutableVisualizer(){const[raw,setRaw]=useState(JSON.stringify(EXAMPLES[0]));const{input,inputError}=useMemo(()=>parse(raw),[raw]);const steps=useMemo(()=>input?stepsFor(input).map(s=>({...s,relatedLines:[s.activeLine]})):[],[input]);const{stepIndex,setStepIndex,stepForward,stepBack,togglePlay,handleReset,isPlaying,speed,setSpeed,isDone}=usePlaybackState(steps.length);const step=stepIndex>=0?steps[stepIndex]:null;const links=useCodeVisualConnectivity({steps,stepIndex,onStepJump:setStepIndex});const apply=useCallback(x=>{setRaw(JSON.stringify(x));handleReset()},[handleReset]);const[divs,setDivs]=useState(null);const panels=useMemo(()=>[{id:'input',title:'Input'},{id:'code',title:'Python code',dockMode:'split-bottom'},{id:'viz',title:'2D prefix table',dockMode:'split-right'},{id:'examples',title:'Examples',dockMode:'split-bottom'}],[]);const contents={input:<div className="range-sum-query2-d--immutable-panel"><div className="range-sum-query2-d--immutable-panel-body"><textarea className="range-sum-query2-d--immutable-textarea" value={raw} onChange={e=>setRaw(e.target.value)}/></div></div>,code:<CodeTracePanel step={step} codeLines={CODE} highlightedLines={links.highlightedLines} onLineSelect={links.handleLineSelect}/>,viz:!input?<div className="range-sum-query2-d--immutable-error">{inputError}</div>:<div className="range-sum-query2-d--immutable-panel"><div className="range-sum-query2-d--immutable-panel-body"><div className="range-sum-query2-d--immutable-step-info"><h3>{step?.message||'Press play to build the prefix table.'}</h3></div><DPTable title="Padded prefix sums" values={step?.prefix||[[0]]} activeCell={step?.active}/>{step?.result!==undefined&&<strong>sumRegion = {step.result}</strong>}</div></div>,examples:<div className="range-sum-query2-d--immutable-panel"><div className="range-sum-query2-d--immutable-panel-body range-sum-query2-d--immutable-examples">{EXAMPLES.map((x,i)=><button className="range-sum-query2-d--immutable-example-btn" key={i} onClick={()=>apply(x)}>{x.label||`Example ${i+1}`}</button>)}</div></div>};return <div className="range-sum-query2-d--immutable-shell"><LuminoDockPanel panels={panels} onPanelReady={setDivs}/>{divs&&Object.entries(contents).map(([id,c])=>divs[id]&&createPortal(c,divs[id]))}<FloatingPanel title="Playback Controls"><PlaybackControls isPlaying={isPlaying} isDone={isDone} speed={speed} onPlayToggle={togglePlay} onPrev={stepBack} onNext={stepForward} onReset={handleReset} prevDisabled={stepIndex<0} nextDisabled={isDone} resetDisabled={stepIndex<0} onSpeedChange={e=>setSpeed(Number(e.target.value))}/></FloatingPanel></div>}
