import {solvers,parseTree} from './algorithms.js';
import {treeStoryExamples} from '../../../config/treeStoryExamples.js';
import {treeStoryMetadata} from './metadata.js';

const specs={
  606:['root','Serialize the tree into preorder text while preserving its exact structure.','Omit unnecessary empty child groups, but retain an empty left group whenever a right child exists. Otherwise left-only and right-only shapes become indistinguishable.',['visit node in preorder','serialize left and right subtrees','decide which child parentheses are structurally necessary','combine node value and required child groups','return tree string'],'O(n) traversal; up to O(n²) string-copy work in this direct recursive implementation.'],
  617:['root1 root2','Merge trees by adding corresponding values and retaining unmatched branches.','Recursion aligns positions rather than values. Each output node sums the two nodes at that position; an absent node contributes zero.',['align the two roots','recurse on corresponding children','treat missing nodes as zero','construct a node with summed value and merged children','return merged root'],'O(n+m) time and output space.'],
  623:['root val depth','Insert a new row while attaching original left and right subtrees to the correct sides.','Find nodes one level above the insertion depth. Their old left branches go under new left nodes, and old right branches go under new right nodes.',['handle depth one with a new root','advance frontier to depth-1','save each parent’s existing children','insert two nodes and reattach each old branch on its original side','return root'],'O(n) time and frontier/output space.'],
  637:['root','Compute the average node value separately at each depth.','A breadth-first frontier contains exactly one level. Complete its sum and count before constructing the next frontier.',['frontier = root; output = []','while frontier is nonempty','sum values and count nodes on this level','append average and collect all children','return averages'],'O(n) time; O(width) frontier space plus output.'],
  653:['root k','Find whether two distinct tree nodes sum to k.','Before adding a node to the seen set, look for its complement among earlier nodes. This prevents matching the node with itself.',['seen = empty set; stack = root','visit each node','look for target - current value in seen','return true if found, otherwise record value and traverse children','return false after exhausting nodes'],'O(n) expected time and space.'],
  654:['nums','Construct the tree whose root is the maximum and whose subtrees represent the original left and right ranges.','A decreasing stack stores the right spine of the processed prefix. Each new value adopts popped smaller roots as its left subtree.',['stack = empty','process array values from left to right','pop roots smaller than the new value','attach last popped root as left; attach new node as remaining top’s right','return bottom of stack'],'O(n) time and space.'],
  669:['root low high','Remove out-of-range BST nodes while preserving the relative structure of retained nodes.','If a node is too small, its left subtree is also too small; keep searching right. Symmetrically skip right subtrees of nodes that are too large.',['trim the root recursively','visit the next candidate root','compare its value with inclusive bounds','skip an impossible side or trim both children of a retained node','return the retained root'],'O(n) time; O(height) recursion space.'],
  671:['root','Find the second smallest distinct value in a tree whose parent equals the minimum of its children.','The root is the minimum. Explore below equal-valued nodes; once a larger candidate appears, descendants cannot improve it within that branch.',['minimum = root value; second = infinity','visit candidate nodes','compare node with minimum','update second if greater; otherwise explore children','return second or -1'],'O(n) time; O(height) traversal stack.'],
  687:['root','Find the greatest number of edges on a path whose node values are all equal.','Return one extendable equal-value arm to a parent. At each node, combine its left and right arms to test a path passing through that node.',['best = 0','recursively obtain child arm lengths','extend an arm only when child value equals parent','maximize joined arms; return longer single arm','return best edge count'],'O(n) time; O(height) recursion space.'],
  700:['root val','Find a target in a BST and return the entire matching subtree.','A smaller target can occur only on the left and a larger target only on the right. Follow one search path until a match or missing child.',['current = root','while current exists','compare target with current value','return match or follow only the possible child','return empty subtree if absent'],'O(height) time; O(1) search state.'],
  701:['root val','Insert a new value as a leaf while preserving strict BST order.','Follow the same comparisons as search. The first missing child on that path is the unique insertion position for this leaf strategy.',['create the new node','follow the BST search path','choose left or right according to value','attach at the first missing child','return root'],'O(height) time; O(1) traversal state plus the inserted node.'],
  872:['root1 root2','Decide whether two trees have identical left-to-right leaf sequences.','Internal values and tree shape do not determine leaf similarity. Traverse left before right and record only nodes with no children.',['prepare one leaf sequence per tree','traverse each tree left to right','recognize nodes with no children','append leaf values in visitation order','return equality of both sequences'],'O(n+m) time; O(n+m) sequence/stack space.'],
  897:['root','Rearrange a BST into increasing order with no left children.','Inorder traversal gives sorted node order. Relink those nodes in that order, clearing every left pointer and ending the right chain with null.',['collect nodes in inorder','traverse left, node, right','record each node in sorted order','clear left pointers and connect consecutive right pointers','return the first inorder node'],'O(n) time and node-list space.'],
  938:['root low high','Sum BST node values within an inclusive range.','BST ordering lets a boundary exclude whole branches. Add in-range nodes, explore left only above the lower bound, and right only below the upper bound.',['stack = root; total = 0','visit remaining candidates','compare value with inclusive bounds','add qualifying value and push only potentially useful children','return total'],'O(n) worst-case time; O(height) traversal space.'],
  965:['root','Decide whether every node has the same value as the root.','One mismatch is sufficient to disprove the property. Otherwise every reachable node must be visited before returning true.',['expected = root value','visit each reachable node','compare its value with expected','return false on mismatch; otherwise push children','return true after all nodes match'],'O(n) time; O(height) traversal stack.'],
};

function prepare(id,input){
 if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Use a JSON object with the named fields.');
 for(const field of specs[id][0].split(' '))if(!(field in input))throw new Error(`Missing ${field}.`);
 const state={...input},roots=[];
 for(const field of ['root','root1','root2'])if(field in input){const a=input[field];if(!Array.isArray(a)||a.length>63||a.some(v=>v!==null&&(!Number.isInteger(v)||Math.abs(v)>10000)))throw new Error('Use level-order arrays of at most 63 integers or nulls, with values between -10000 and 10000.');state[field]=parseTree(a,field);roots.push(state[field]);}
 if([606,623,637,653,671,700,872,897,938,965].includes(id)&&roots.some(r=>!r))throw new Error('This problem requires a nonempty input tree.');
 for(const field of ['val','k','low','high'])if(field in input&&(!Number.isInteger(input[field])||Math.abs(input[field])>20000))throw new Error(`${field} must be an integer between -20000 and 20000.`);
 if('low'in input&&input.low>input.high)throw new Error('low must not exceed high.');
 const nodes=[];function visit(n,low=-Infinity,high=Infinity){if(!n)return;nodes.push(n);if([653,669,700,701,897,938].includes(id)&&!(low<n.val&&n.val<high))throw new Error('This problem requires a strict BST without duplicate values.');visit(n.left,low,n.val);visit(n.right,n.val,high);}roots.forEach(r=>visit(r));
 if(id===701&&nodes.some(n=>n.val===input.val))throw new Error('The inserted value must not already exist in the BST.');
 if(id===623){const height=n=>n?1+Math.max(height(n.left),height(n.right)):0;if(!Number.isInteger(input.depth)||input.depth<1||input.depth>height(state.root)+1)throw new Error('depth must be between 1 and tree height plus one.');}
 if(id===654&&(!Array.isArray(input.nums)||!input.nums.length||input.nums.length>40||!input.nums.every(v=>Number.isInteger(v)&&v>=0&&v<=10000)||new Set(input.nums).size!==input.nums.length))throw new Error('Use 1–40 distinct nonnegative integer values.');
 if(id===671&&nodes.some(n=>n.val<0||Boolean(n.left)!==Boolean(n.right)||(n.left&&n.val!==Math.min(n.left.val,n.right.val))))throw new Error('Every internal node must have two children and equal their minimum; values must be nonnegative.');
 return state;
}
export const definitions=Object.fromEntries(Object.entries(specs).map(([key,[fields,goal,strategy,lines,complexity]])=>{
 const id=Number(key),meta=treeStoryMetadata[id];return [id,{...meta,goal,strategy,complexity,inputLabel:`${fields} (JSON; trees use level-order arrays and null children)`,examples:treeStoryExamples[id],code:lines.map((text,i)=>({line:i+1,text})),phases:[{id:'start',label:'Input trees',description:goal},{id:'inspect',label:'Decide',description:strategy},{id:'update',label:'Build result',description:strategy},{id:'done',label:'Return',description:goal}],
 parse:text=>{const value=JSON.parse(text);prepare(id,value);return value;},
 build:raw=>{const input=prepare(id,raw),trees=['root','root1','root2'].filter(k=>k in input).map(k=>({label:k==='root'?'Working tree':k==='root1'?'First input':'Second input',root:input[k]})),frames=[];
  const emit=(message,state={},phase='inspect')=>frames.push(structuredClone({trees,active:[],metrics:{},...state,message,phase,activeLine:{start:1,inspect:3,update:4}[phase]}));
  emit(goal,{},'start');const result=solvers[id](input,emit);frames.push({...frames.at(-1),phase:'done',activeLine:5,message:`Return ${JSON.stringify(result)}. ${goal}`,result:structuredClone(result)});return {frames,result};
 }}];
}));
