export const databaseSchemas={
1667:{table:'Users',columns:['user_id','name'],result:['user_id','name']},
1683:{table:'Tweets',columns:['tweet_id','content'],result:['tweet_id']},
1693:{table:'DailySales',columns:['date_id','make_name','lead_id','partner_id'],result:['date_id','make_name','unique_leads','unique_partners']},
1729:{table:'Followers',columns:['user_id','follower_id'],result:['user_id','followers_count']},
1741:{table:'Employees',columns:['emp_id','event_day','in_time','out_time'],result:['day','emp_id','total_time']},
1757:{table:'Products',columns:['product_id','low_fats','recyclable'],result:['product_id']},
1821:{table:'Customers',columns:['customer_id','year','revenue'],result:['customer_id']},
1873:{table:'Employees',columns:['employee_id','name','salary'],result:['employee_id','bonus']},
1890:{table:'Logins',columns:['user_id','time_stamp'],result:['user_id','last_stamp']},
1907:{table:'Accounts',columns:['account_id','income'],result:['category','accounts_count']},
};
export function databaseInput(id, rows, activeRow=-1){return{label:databaseSchemas[id].table,columns:databaseSchemas[id].columns,rows,activeRow};}
function report(emit,id,rows,index,result,message,metrics={}){emit(message,{sourceRecords:databaseInput(id,rows,index),resultRecords:{label:'Result rows so far',columns:databaseSchemas[id].result,rows:result},codeStage:'update',metrics},'update');}
const compareText=(a,b)=>a<b?-1:a>b?1:0;
export const databaseSolvers={
1667({rows},emit){const result=[];rows.forEach((row,index)=>{result.push({user_id:row.user_id,name:row.name[0].toUpperCase()+row.name.slice(1).toLowerCase()});report(emit,1667,rows,index,result,'Capitalize only the first character and lowercase the remaining name. Preserve user IDs, then order the final rows by ID.');});return result.sort((a,b)=>a.user_id-b.user_id);},
1683({rows},emit){const result=[];rows.forEach((row,index)=>{const length=[...row.content].length,invalid=length>15;if(invalid)result.push({tweet_id:row.tweet_id});report(emit,1683,rows,index,result,'Keep tweets with more than fifteen characters. Exactly fifteen remains valid and must be excluded.',{length,invalid});});return result;},
1693({rows},emit){const groups=new Map();rows.forEach((row,index)=>{const key=JSON.stringify([row.date_id,row.make_name]);if(!groups.has(key))groups.set(key,{date_id:row.date_id,make_name:row.make_name,leads:new Set(),partners:new Set()});const group=groups.get(key);group.leads.add(row.lead_id);group.partners.add(row.partner_id);const result=[...groups.values()].map(g=>({date_id:g.date_id,make_name:g.make_name,unique_leads:g.leads.size,unique_partners:g.partners.size}));report(emit,1693,rows,index,result,'Group by both date and make. Count lead IDs and partner IDs independently as distinct sets; repeated source rows do not inflate either count.',{group:key});});return[...groups.values()].map(g=>({date_id:g.date_id,make_name:g.make_name,unique_leads:g.leads.size,unique_partners:g.partners.size})).sort((a,b)=>compareText(a.date_id,b.date_id)||compareText(a.make_name,b.make_name));},
1729({rows},emit){const counts=new Map();rows.forEach((row,index)=>{counts.set(row.user_id,(counts.get(row.user_id)||0)+1);report(emit,1729,rows,index,[...counts].map(([user_id,followers_count])=>({user_id,followers_count})),'Each unique user/follower relation adds one follower to that user. Group by the followed user, not the follower ID.');});return[...counts].sort((a,b)=>a[0]-b[0]).map(([user_id,followers_count])=>({user_id,followers_count}));},
1741({rows},emit){const groups=new Map();rows.forEach((row,index)=>{const key=JSON.stringify([row.event_day,row.emp_id]);if(!groups.has(key))groups.set(key,{day:row.event_day,emp_id:row.emp_id,total_time:0});const duration=row.out_time-row.in_time;groups.get(key).total_time+=duration;report(emit,1741,rows,index,[...groups.values()],'Subtract entry time from exit time for this visit, then accumulate by employee and day. Separate visits on one day belong to the same result row.',{duration});});return[...groups.values()].sort((a,b)=>compareText(a.day,b.day)||a.emp_id-b.emp_id);},
1757({rows},emit){const result=[];rows.forEach((row,index)=>{const selected=row.low_fats==='Y'&&row.recyclable==='Y';if(selected)result.push({product_id:row.product_id});report(emit,1757,rows,index,result,'Both flags must be Y. One qualifying flag alone does not satisfy the conjunction.',{selected});});return result;},
1821({rows},emit){const result=[];rows.forEach((row,index)=>{const selected=row.year===2021&&row.revenue>0;if(selected)result.push({customer_id:row.customer_id});report(emit,1821,rows,index,result,'Apply both predicates: the year must be 2021 and revenue must be strictly positive. Zero revenue and other years are excluded.',{selected});});return result;},
1873({rows},emit){const result=[];rows.forEach((row,index)=>{const eligible=row.employee_id%2===1&&!row.name.startsWith('M');result.push({employee_id:row.employee_id,bonus:eligible?row.salary:0});report(emit,1873,rows,index,result,'Retain every employee. Award full salary only to odd IDs whose name does not begin with uppercase M; other employees receive zero.',{eligible});});return result.sort((a,b)=>a.employee_id-b.employee_id);},
1890({rows},emit){const latest=new Map();rows.forEach((row,index)=>{const selected=row.time_stamp>='2020-01-01 00:00:00'&&row.time_stamp<'2021-01-01 00:00:00';if(selected&&(!latest.has(row.user_id)||row.time_stamp>latest.get(row.user_id)))latest.set(row.user_id,row.time_stamp);report(emit,1890,rows,index,[...latest].map(([user_id,last_stamp])=>({user_id,last_stamp})),'Filter to the half-open 2020 interval before taking a per-user maximum. A later login in another year must not displace the latest login within 2020.',{selected});});return[...latest].sort((a,b)=>a[0]-b[0]).map(([user_id,last_stamp])=>({user_id,last_stamp}));},
1907({rows},emit){const counts={'Low Salary':0,'Average Salary':0,'High Salary':0};rows.forEach((row,index)=>{const category=row.income<20000?'Low Salary':row.income<=50000?'Average Salary':'High Salary';counts[category]++;report(emit,1907,rows,index,Object.entries(counts).map(([category,accounts_count])=>({category,accounts_count})),'The middle category includes both 20000 and 50000. Keep all three categories in the result, even when a category has no accounts.',{category});});return Object.entries(counts).map(([category,accounts_count])=>({category,accounts_count}));},
};
