export const laterSpecs={
1401:['radius xCenter yCenter x1 y1 x2 y2','Decide whether a circle and axis-aligned rectangle overlap or touch.','The closest rectangle point is obtained by clamping each center coordinate to its interval. Squared-distance comparison avoids square roots and includes tangency.','clamp center x to [x1,x2]|clamp center y to [y1,y2]|compute squared distance to the clamped point|compare with radius squared|return whether distance is no greater','O(1) time and space.'],
1402:['satisfaction','Maximize the sum of cooking completion time times satisfaction.','Process candidate dishes from greatest satisfaction downward. Prepending one dish increases every selected completion time, giving a net gain equal to the new selected sum.','sort satisfaction descending; suffix = total = 0|for next value:|    gain = suffix+value|    stop if gain <= 0; otherwise add gain and extend suffix|return total','O(n log n) time; O(n) copied-array space.'],
1403:['nums','Choose the shortest subsequence whose sum exceeds the remaining values, preferring the greatest sum.','Taking largest values first maximizes the sum at each chosen length. The first prefix exceeding half the total has minimal length and maximal sum.','sort values descending; total = sum(nums)|for next largest value:|    append it and update chosen sum|    stop when chosen sum exceeds total-chosen|return chosen values in descending order','O(n log n) time; O(n) space.'],
1404:['s','Count add-one and halve steps needed to reduce a binary number to one.','Scan low bits while tracking carry. An effective odd bit requires an increment followed by division; an effective even bit requires division alone.','carry = steps = 0|scan bits right to left except the leading one:|    inspect bit+carry|    add two steps and set carry for odd, else add one|return steps+carry','O(n) time; O(1) state.'],
1405:['a b c','Construct a longest a/b/c string without three identical adjacent characters.','Use the most abundant available letter unless it would create a forbidden triple. Then choose the next most abundant letter to break the run.','counts = available a,b,c; output = []|repeatedly rank remaining counts:|    choose largest unless last two output letters match it|    append allowed choice, or stop when none is available|return joined output','O(a+b+c) time with constant-size ranking; output space.'],
1406:['stoneValue','Determine the winner when players optimally take one to three leading stones.','Store the best score advantage for the player whose turn starts at each suffix. Taking stones earns their sum but hands the remaining suffix advantage to the opponent.','dp after the final stone = 0|for suffix start from right to left:|    try taking one, two, or three stones|    maximize taken sum minus next suffix advantage|return Alice, Bob, or Tie from the sign of dp[0]','O(n) time and DP space.'],
1408:['words','Find words that occur as substrings of another input word.','Compare distinct word entries. A substring match anywhere qualifies, but matching a word with itself would incorrectly accept everything.','output = []|for word at index i:|    search other indices for a word containing it|    append it if a host exists|return matching words','O(n^2 * substring-search work) time; output space.'],
1409:['queries m','Answer permutation positions while moving each requested value to the front.','Each answer uses the current position before mutation. Moving a value shifts earlier entries right, affecting later query results.','permutation = 1 through m|for query value:|    locate its current index and record it|    remove it there and insert at the front|return recorded indices','O(qm) time; O(m+q) space.'],
1410:['text','Decode the six supported HTML entities once while preserving other text.','Recognize supported sequences only in the original input. Do not rescan decoded ampersands, which would incorrectly decode nested entity text twice.','output = []; index = 0|while input remains:|    look for a supported entity starting at index|    append its character and skip token, or copy one input character|return joined output','O(n) time with six fixed tokens; output space.'],
1411:['n','Count valid three-column grid colorings with adjacent cells different.','A row either uses two colors in an ABA pattern or three in an ABC pattern. Track these categories and their different compatible transition counts.','twoColor = threeColor = 6|for each later row:|    read both previous category counts|    nextTwo = 3*two+2*three; nextThree = 2*two+2*three|return category sum modulo 1000000007','O(n) time; O(1) state.'],
1413:['nums','Find the least positive starting value keeping every prefix accumulation positive.','The lowest prefix deficit determines the required reserve. Include the empty prefix so a wholly positive sequence still starts at one.','running = lowest = 0|for value:|    add it into running sum|    lower the recorded prefix minimum if needed|return 1-lowest','O(n) time; O(1) state.'],
1414:['k','Use the fewest Fibonacci numbers whose sum equals k.','Choose the greatest Fibonacci value no larger than the remaining target. Repeating on the remainder yields a minimal greedy decomposition.','generate Fibonacci values up to k|visit values from largest to smallest:|    compare with remaining target|    subtract fitting values and count selections|return selection count','O(log k) time and Fibonacci-list space.'],
1415:['n k','Return the kth lexicographic length-n string over a,b,c with no equal neighbors.','Depth-first generation tries letters in sorted order and skips the previous letter. Complete leaves therefore arrive in lexicographic order.','rank = 0; answer = empty|recursively extend prefixes in a,b,c order:|    skip a letter equal to the previous one|    count complete strings and stop at rank k|return answer or empty when k is too large','O(n*2^n) bounded enumeration time; O(n) recursion state.'],
1417:['s','Rearrange digits and lowercase letters so their types alternate.','The type counts may differ by at most one. Start with the larger class and interleave in order, leaving its possible extra character last.','separate letters from digits|reject count difference greater than one|choose the larger class first|append alternating class entries|return reformatted string','O(n) time and space.'],
1418:['orders','Build a restaurant display table grouped by table number and food name.','Food columns sort alphabetically while table rows sort numerically. Group counts ignore customer names and fill missing table-food combinations with zero.','collect food names and per-table counts|process each order into its table-food bucket|sort food names and numeric table identifiers|build header and string-valued count rows|return display table','O(o + f log f + t log t + tf) time; O(tf) table space.'],
1419:['croakOfFrogs','Find the minimum simultaneous frogs explaining the sound sequence.','Each sound must advance a frog waiting at the previous croak stage. A completed frog becomes reusable; the peak active count is the required workforce.','waiting stages = zeros; active = peak = 0|for sound in croak order:|    start a frog at c or require a preceding waiting stage|    advance or finish it and maximize active count|return peak if all finish, otherwise -1','O(n) time; O(1) stage state.'],
1422:['s','Split a binary string into nonempty parts to maximize left zeros plus right ones.','Move the split one character at a time. Left zeros grow as right ones shrink, and the final character must remain in the right part.','leftZeros = 0; rightOnes = total ones|for split before final character:|    transfer current bit to the left side|    maximize leftZeros+rightOnes|return best score','O(n) time; O(1) state.'],
1423:['cardPoints k','Maximize points by taking exactly k cards from the two ends.','The unselected cards always form one contiguous middle interval. Its length is n-k, so minimizing that interval sum maximizes the chosen sum.','total = sum(cards); width = n-k|if width is zero return total|slide a width-sized middle window|retain the least unselected sum|return total-least','O(n) time; O(1) state.'],
1424:['nums','Traverse a ragged list of rows in diagonal order.','Cells with equal row-plus-column share a diagonal. Top-down collection reverses the desired within-diagonal direction, so emit each bucket backward.','group cells by row+column|scan every existing ragged-row cell|append value to its diagonal bucket|visit diagonal keys ascending and reverse each bucket|return concatenated diagonals','O(N + d log d) time; O(N) bucket space.'],
1426:['arr','Count array occurrences whose value plus one also appears.','Membership is global, but counting is per occurrence. Repeated values each count when their successor exists at least once.','available = set(arr); count = 0|for value:|    test value+1 membership|    increment count on success|return count','O(n) expected time and set space.'],
1427:['s shift','Apply all left and right cyclic string shifts.','Rotations compose by adding signed offsets. Normalize once modulo the string length instead of moving characters after every instruction.','offset = 0|for direction,amount:|    treat right as positive and left as negative|    accumulate and normalize modulo string length|return the corresponding right rotation','O(shifts+n) time; O(n) output space.'],
1433:['s1 s2','Decide whether a permutation of one string can dominate the other character by character.','Sorted alignment is sufficient to determine dominance. All comparisons must consistently favor one side, though equality is allowed.','sort both strings|for aligned positions:|    update whether first >= second everywhere|    update whether second >= first everywhere|return whether either direction remains possible','O(n log n) time; O(n) sorted-character space.'],
1436:['paths','Find the terminal city of a directed itinerary.','The destination city appears as an arrival but never a departure. A set of departure names makes that distinction explicit.','starts = all departure cities|for path destination:|    test whether it appears in starts|    return the first destination with no outgoing path|return empty if the route promise is violated','O(n) expected time and set space.'],
1437:['nums k','Check whether consecutive ones have at least k zeros between them.','Only neighboring one positions need comparison. Subtract one from their index difference to exclude the endpoints themselves.','lastOne = none|for index containing one:|    compare index-lastOne-1 with k when a predecessor exists|    reject too-small gap, otherwise remember index|return true','O(n) time; O(1) state.'],
1438:['nums limit','Find the longest contiguous interval whose greatest and least values differ by at most limit.','Monotonic queues retain maximum and minimum candidates. Shrink the left boundary only while their difference violates the limit.','left = best = 0; extrema queues = empty|for right,value:|    maintain decreasing maxima and increasing minima|    discard left positions until range fits; maximize length|return best','O(n) amortized time; O(n) queue storage.'],
1441:['target n','Produce Push and Pop operations that build the target from stream values one through n.','Read stream values in order. Keep requested values and immediately pop skipped ones; stop as soon as the full target is constructed.','output = []; targetIndex = 0|read stream until target complete:|    always append Push|    advance target match or append Pop for an unwanted value|return operations','O(n) time and operation output space.'],
1442:['arr','Count triples splitting a contiguous interval into two equal-XOR parts.','The two parts have equal XOR exactly when the entire interval XOR is zero. An interval from left through right then offers right-left internal split positions.','total = 0|for interval start:|    extend interval end with rolling XOR|    add end-start whenever whole interval XOR is zero|return total','O(n^2) time; O(1) state.'],
1446:['s','Find the longest run of one repeated character.','A character either extends the immediately preceding equal run or starts a fresh run of length one. Retain the greatest observed run.','run = best = 0|for character:|    compare with its predecessor|    extend or restart, then maximize best|return best','O(n) time; O(1) state.'],
1447:['n','List all reduced positive proper fractions with denominator at most n.','Numerator smaller than denominator makes a proper fraction. Coprime numerator and denominator ensure it is already reduced and not a duplicate.','output = []|for denominator 2..n and numerator 1..denominator-1:|    compute gcd of numerator and denominator|    append fraction only when gcd is one|return fractions','O(n^2 log n) time; output space.'],
1450:['startTime endTime queryTime','Count students whose homework interval contains the query time.','Both interval endpoints are inclusive. Compare the query independently with each matching start/end pair.','count = 0|for student index:|    check start <= query <= end|    increment count when inside|return count','O(n) time; O(1) state.'],
1451:['text','Order sentence words by length while preserving ties and sentence capitalization.','Lowercase before sorting, use original index as a stable secondary key, and capitalize only the first output character.','split lowercased words with original indices|sort by word length then original index|join ranked words with one space|capitalize first character of joined sentence|return sentence','O(n log n + characters) time and space.'],
1455:['sentence searchWord','Find the first one-based word position with the requested prefix.','Prefix comparison must start at a word boundary. Scan in sentence order and return immediately at the earliest matching word.','split sentence into words|for index,word:|    test word starts with searchWord|    return index+1 on first match|return -1','O(total text length) time and word-list space.'],
1456:['s k','Find the greatest vowel count among length-k substrings.','One entering and one leaving character update the window count. Compare only completed windows of the requested width.','vowels = best = 0|for right character:|    add its vowel flag and remove the expired flag|    maximize best once the window reaches k|return best','O(n) time; O(1) state.'],
1460:['target arr','Decide whether reversing subarrays can transform one array into the other.','Length-two reversals permit arbitrary rearrangements. The exact requirement is matching multiplicities, not matching current order.','remaining = frequencies(target)|for arr value:|    consume one matching occurrence|    retain signed remaining counts|return every remaining count is zero','O(n) expected time and count-map space.'],
1461:['s k','Check whether every length-k binary code appears as a substring.','There are exactly two to the power k codes. Reject immediately if there are too few windows, otherwise count distinct windows.','required = 2^k|reject if number of windows is smaller|required set = all length-k slices|deduplicate repeated codes|return set size == required','O(nk) time and stored substring space.'],
1464:['nums','Maximize the product of two distinct-position values after subtracting one from each.','All values are positive, so the two largest values maximize both nonnegative factors. Track two positions even when the values are equal.','largest = second = 0|for value:|    compare with the two retained maxima|    update largest and second without losing duplicate positions|return (largest-1)*(second-1)','O(n) time; O(1) state.'],
1465:['h w horizontalCuts verticalCuts','Find the greatest rectangle area after full horizontal and vertical cake cuts.','Cuts divide each axis independently. The greatest possible piece combines the largest horizontal interval with the largest vertical interval.','include both outer boundaries on each axis|sort each axis cut list|find its greatest adjacent gap|multiply the two gaps using exact integer arithmetic|return area modulo 1000000007','O(hCuts log hCuts + vCuts log vCuts) time; copied cut-list space.'],
1470:['nums n','Interleave corresponding values from the two array halves.','Pair index i with index n+i. This preserves the order of both halves while placing each pair together.','output = []|for index zero through n-1:|    read first-half value and matching second-half value|    append them in that order|return output','O(n) time and output space.'],
1471:['arr k','Select the k strongest values relative to the lower middle median.','Strength is absolute distance from the median, with greater values breaking equal-distance ties. Sort by those keys in descending order.','sort values and choose median at floor((n-1)/2)|rank by decreasing absolute distance from median|break equal distance by decreasing numeric value|take first k ranked values|return strongest values','O(n log n) time; O(n) copied-array space.'],
1475:['prices','Apply the first subsequent no-greater price as each item discount.','A monotonic stack holds indices still waiting for a qualifying discount. The current price resolves all larger-or-equal waiting prices it reaches first.','output = copy prices; pending = []|for current price,index:|    pop waiting indices whose price >= current|    subtract current price from their output; push current index|return final prices','O(n) amortized time; O(n) space.'],
};

export function validateLater(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=80,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const list=(a,width,min=0,max=80)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(p=>vector(p,width,width));
 const text=(s,regex=/^[a-z]+$/)=>typeof s==='string'&&s.length>=1&&s.length<=160&&regex.test(s);
 for(const key of ['nums','arr','satisfaction','stoneValue','cardPoints','queries','target','prices','startTime','endTime','horizontalCuts','verticalCuts'])if(key in input&&id!==1424)check(vector(input[key]),`${key}: use 1-80 bounded integers.`);
 for(const key of ['s','s1','s2'])if(key in input)check(text(input[key],[1404,1422,1461].includes(id)?/^[01]+$/:id===1417?/^[a-z0-9]+$/:/^[a-z]+$/),`${key}: use 1-160 valid problem characters.`);
 if(id===1401)check(integer(input.radius,1,10000)&&['xCenter','yCenter','x1','y1','x2','y2'].every(k=>integer(input[k],-10000))&&input.x1<input.x2&&input.y1<input.y2,'Use bounded integer coordinates, positive radius, and a rectangle with positive width and height.');
 if([1403,1423,1464,1475].includes(id))check(input[id===1423?'cardPoints':id===1475?'prices':'nums'].every(v=>v>=1),'Use positive values.');
 if(id===1404)check(input.s[0]==='1','The positive binary number must not have leading zeros.');
 if(id===1405)check([input.a,input.b,input.c].every(v=>integer(v,0,40))&&input.a+input.b+input.c>0,'Use counts 0-40, with at least one available character.');
 if(id===1406)check(input.stoneValue.length<=40,'Use at most forty stones for readable suffix decisions.');
 if(id===1408)check(Array.isArray(input.words)&&input.words.length>=1&&input.words.length<=30&&input.words.every(w=>text(w)&&w.length<=30)&&new Set(input.words).size===input.words.length,'Use 1-30 distinct lowercase words, at most thirty characters each.');
 if(id===1409)check(integer(input.m,1,60)&&input.queries.every(v=>integer(v,1,input.m)),'Use m 1-60 and query values in 1..m.');
 if(id===1410)check(text(input.text,/^[\x20-\x7e]+$/),'Use 1-160 printable ASCII characters.');
 if(id===1411)check(integer(input.n,1,100),'Use 1-100 grid rows for inspectable category transitions.');
 if(id===1414)check(integer(input.k,1,1000000),'Use k from one through one million.');
 if(id===1415)check(integer(input.n,1,7)&&integer(input.k,1,1000),'Use length 1-7 and positive rank at most 1000 for bounded enumeration.');
 if(id===1418)check(Array.isArray(input.orders)&&input.orders.length>=1&&input.orders.length<=60&&input.orders.every(o=>Array.isArray(o)&&o.length===3&&text(o[0],/^[A-Za-z ]+$/)&&typeof o[1]==='string'&&/^[1-9]\d{0,2}$/.test(o[1])&&text(o[2],/^[A-Za-z ]+$/)),'Use [customer,tableNumberString,food] orders with table numbers 1-999 and alphabetic names.');
 if(id===1419)check(text(input.croakOfFrogs,/^[croak]+$/),'Use 1-160 letters from c,r,o,a,k.');
 if(id===1422)check(input.s.length>=2,'Use at least two bits so both split parts are nonempty.');
 if(id===1423)check(integer(input.k,1,input.cardPoints.length),'Use k between one and the card count.');
 if(id===1424)check(Array.isArray(input.nums)&&input.nums.length>=1&&input.nums.length<=12&&input.nums.every(row=>vector(row,1,12)),'Use 1-12 nonempty rows of at most twelve bounded integers; row lengths may differ.');
 if(id===1427)check(list(input.shift,2,1,60)&&input.shift.every(([d,n])=>integer(d,0,1)&&integer(n,0,10000)),'Use [direction,amount] shifts, with direction zero for left or one for right and nonnegative amount.');
 if(id===1433)check(input.s1.length===input.s2.length,'The two strings must be equally long.');
 if(id===1436){check(Array.isArray(input.paths)&&input.paths.length>=1&&input.paths.length<=40&&input.paths.every(p=>Array.isArray(p)&&p.length===2&&p.every(c=>text(c,/^[A-Za-z ]+$/))&&p[0]!==p[1]),'Use nonempty city pairs with different endpoints.');const edges=new Map(input.paths),ends=new Set(input.paths.map(p=>p[1])),starts=[...edges.keys()].filter(c=>!ends.has(c));check(edges.size===input.paths.length&&ends.size===input.paths.length&&starts.length===1,'Paths must describe one unbranched itinerary.');let city=starts[0],seen=new Set();while(edges.has(city)&&!seen.has(city)){seen.add(city);city=edges.get(city);}check(seen.size===input.paths.length&&!edges.has(city),'The itinerary must be connected and acyclic.');}
 if(id===1437)check(input.nums.every(v=>v===0||v===1)&&integer(input.k,0,input.nums.length),'Use binary values and a gap requirement between zero and the length.');
 if(id===1438)check(integer(input.limit,0,100000),'Use a nonnegative range limit at most 100000.');
 if(id===1441)check(integer(input.n,1,100)&&input.target.every((v,i,a)=>integer(v,1,input.n)&&(!i||v>a[i-1])),'Use a strictly increasing target within 1..n, with n at most one hundred.');
 if(id===1442)check(input.arr.length<=25&&input.arr.every(v=>v>=0),'Use up to twenty-five nonnegative integers for interval enumeration.');
 if(id===1447)check(integer(input.n,1,20),'Use a maximum denominator from one through twenty.');
 if(id===1450)check(input.startTime.length===input.endTime.length&&input.startTime.every((v,i)=>v>=0&&v<=input.endTime[i])&&integer(input.queryTime,0),'Use equally long valid inclusive intervals and a nonnegative query time.');
 if(id===1451)check(text(input.text,/^[A-Z][a-z]*( [a-z]+)*$/),'Use a sentence capitalized only at its first letter, with single spaces.');
 if(id===1455)check(text(input.sentence,/^[a-z]+( [a-z]+)*$/)&&text(input.searchWord),'Use a lowercase single-spaced sentence and a nonempty lowercase prefix.');
 if(id===1456)check(integer(input.k,1,input.s.length),'Use k between one and the string length.');
 if(id===1460)check(input.target.length===input.arr.length,'Arrays must have equal lengths.');
 if(id===1461)check(integer(input.k,1,20),'Use code width k from one through twenty.');
 if(id===1464)check(input.nums.length>=2,'Use at least two positive values.');
 if(id===1465)check(integer(input.h,2,1000000000)&&integer(input.w,2,1000000000)&&input.horizontalCuts.every(v=>integer(v,1,input.h-1))&&input.verticalCuts.every(v=>integer(v,1,input.w-1))&&new Set(input.horizontalCuts).size===input.horizontalCuts.length&&new Set(input.verticalCuts).size===input.verticalCuts.length,'Use positive distinct interior cuts for both axes of a cake with dimensions at least two.');
 if(id===1470)check(integer(input.n,1,50)&&input.nums.length===2*input.n,'nums must contain exactly twice n values.');
 if(id===1471)check(integer(input.k,1,input.arr.length),'Use k between one and the array length.');
 return input;
}
