export const expansionSpecs={
1100:['s k','Count length-k substrings without repeated characters.','Keep counts for exactly the active window. A complete window contains only distinct characters when its map has k keys.','counts = {}; total = 0|for right character:|    add entering and remove expired character|    count full windows with k distinct keys|return total','O(n) time; O(k) state.'],
1108:['address','Display an IPv4 address with bracketed dots.','Replace only separators and preserve every digit in order. Output positions expand when a dot becomes three characters.','output = empty text|for character:|    check whether it is a dot|    append bracketed dot or original digit|return output','O(n) output construction work for bounded addresses.'],
1109:['bookings n','Compute the reserved seats on every flight.','A booking changes occupancy at two boundaries. Prefix accumulation restores the complete range contribution without updating every flight individually.','difference = n+1 zeros|for first,last,seats booking:|    add seats at first-1 and subtract at last|    prefix-sum the first n difference entries|return flight totals','O(bookings+n) time; O(n) space.'],
1111:['seq','Split a balanced parentheses sequence into two groups with minimum maximum nesting depth.','Assign paired brackets using depth parity. Alternating nesting layers balances depth between the groups while keeping each group balanced.','depth = 0; groups = []|for bracket:|    decrement depth before assigning a closer|    append depth modulo two; increment after an opener|return groups','O(n) time and output space.'],
1118:['year month','Find the number of days in a Gregorian calendar month.','Months have fixed lengths except February. Leap years follow the divisible-by-four rule with the century and four-hundred-year exceptions.','compute leap-year flag|construct the twelve month lengths|select month-1|read the selected length|return days','O(1) time and space.'],
1119:['s','Remove lowercase vowels while preserving the other characters.','Each character makes an independent keep-or-skip decision. Appending survivors in scan order preserves their relative positions.','output = []|for character:|    test membership in a,e,i,o,u|    append only nonvowels|return joined output','O(n) time and output space.'],
1122:['arr1 arr2','Sort values according to an explicit relative order, then sort the unlisted tail.','Count multiplicities first. Consume requested buckets in arr2 order, then place remaining buckets numerically.','counts = frequencies(arr1)|for value in arr2:|    append all copies and remove its bucket|    append remaining buckets in ascending key order|return output','O(n + u log u) time; O(n+u) space.'],
1128:['dominoes','Count pairs of dominoes equivalent under rotation.','Normalize the smaller endpoint first. A new domino pairs with every earlier occurrence of its normalized key.','counts = {}; total = 0|for domino:|    normalize endpoint order|    add earlier key count, then increment it|return total','O(n) time; O(u) key space.'],
1133:['nums','Find the greatest value that occurs exactly once.','Frequency, not position, determines eligibility. Compare only singleton buckets and return minus one if none remain.','counts = frequencies(nums); best = -1|for value,count:|    check count == 1|    maximize best among eligible values|return best','O(n) time; O(u) space.'],
1134:['n','Decide whether a number equals the sum of its digits raised to its digit count.','The exponent is fixed by the original number length. Accumulate each powered digit before comparing with the unchanged original.','digits = decimal digits; total = 0|for digit:|    raise digit to number of digits|    add contribution to total|return total == n','O(d) digit operations and space for d digits.'],
1137:['n','Compute the requested Tribonacci term.','Every term after the three bases depends on the preceding three values. Build in increasing index order so dependencies are ready.','terms = [0,1,1]|for index from three through n:|    read previous three terms|    append their sum|return terms[n]','O(n) time and retained table space.'],
1144:['nums','Minimize decrements needed to make values alternate between peaks and valleys.','Only two valley parity patterns exist. Lower each chosen valley just below its smaller neighbor; valleys do not constrain each other.','costs = [0,0]|for each valley parity and matching index:|    inspect existing neighboring values|    add max(0,value-minNeighbor+1)|return smaller parity cost','O(n) time; O(1) state.'],
1150:['nums target','Decide whether a target occupies more than half of a sorted array.','Lower and upper insertion boundaries isolate all occurrences. Equality is insufficient for a majority: twice the count must exceed the length.','find first index with value >= target|find first index with value > target|subtract boundaries to obtain count|compare twice count to length|return whether strictly greater','O(log n) time; O(1) state.'],
1151:['data','Minimize arbitrary swaps needed to group all ones together.','The destination block width equals the total number of ones. Every zero inside that block can exchange with an outside one, so maximize ones already inside.','width = total ones; return zero if width is zero|slide a width-sized window:|    add entering one and remove expired one|    retain the greatest inside count|return width - bestInside','O(n) time; O(1) state.'],
1154:['date','Find the one-based day number within the given year.','Add complete preceding months to the current day. February must use the same year-specific leap rule as the date itself.','parse year,month,day|choose leap-adjusted month lengths|for every earlier month:|    add its whole length to day|return accumulated ordinal','O(1) time and space.'],
1160:['words chars','Sum the lengths of words constructible from the supplied character multiset.','Every word independently receives the complete supply. Each needed letter count must fit; unused letters do not matter.','available = character counts|for word:|    compare every needed multiplicity with available|    add word length only if all fit|return total','O(total characters) time; O(alphabet size) working state.'],
1165:['keyboard word','Compute finger travel on a single-row keyboard starting at position zero.','Map each character to its position. The movement cost is the absolute distance from the previously typed key.','positions = keyboard index map; current = total = 0|for word character:|    look up next position|    add absolute displacement; move current|return total','O(keyboard length + word length) time; O(alphabet size) state.'],
1167:['sticks','Minimize the total cost of joining all sticks into one.','Short lengths should participate in more joins. Repeatedly joining the two smallest delays expensive large lengths.','copy lengths; total = 0|while more than one stick remains:|    sort and remove two shortest|    add their sum to cost and return it to the pool|return total','O(n^2 log n) time with repeated sorting; O(n) space.'],
1170:['queries words','For each query, count words with a greater frequency of their smallest character.','Find the smallest letter before counting its occurrences. Comparisons are strict and concern frequency, not lexicographic order of entire strings.','compute smallest-character frequency for each word|for query:|    compute its smallest-character frequency|    count word frequencies strictly above it|return counts','O(total length * log(max length) + queries*words) time with direct sorting and scans.'],
1175:['n','Count permutations where prime values occupy prime-numbered positions.','Prime and nonprime values permute independently inside equally sized position groups. Multiply the two factorials modulo one billion and seven.','count primes through n|start ways = 1|for sizes primeCount and n-primeCount:|    multiply their factorial factors modulo 1000000007|return ways','O(n sqrt n) primality work; O(1) auxiliary state.'],
1176:['calories k lower upper','Score every consecutive k-day calorie interval against two thresholds.','Update one rolling sum. Totals below lower lose a point, above upper gain one, and totals on either boundary change nothing.','window = score = 0|for day:|    add current and remove the day leaving width k|    score only complete windows against strict thresholds|return score','O(n) time; O(1) state.'],
1180:['s','Count substrings consisting of one repeated character.','A run of length r ending at the current position contributes r valid suffixes. Reset the run when the character changes.','run = total = 0|for character:|    compare with previous character|    extend or reset run; add run to total|return total','O(n) time; O(1) state.'],
1184:['distance start destination','Find the shorter route between two stops on a circular bus line.','The two routes partition all edges. Sum the interval between the ordered stop indices and compare it with total minus that interval.','left,right = ordered stop indices|for edge:|    determine whether it belongs to [left,right)|    add to total and, if inside, interval sum|return min(interval,total-interval)','O(n) time; O(1) state.'],
1189:['text','Count complete copies of balloon obtainable from the available letters.','Each copy needs two l characters and two o characters. Divide each letter supply by its demand and take the bottleneck.','counts = frequencies(text)|for required letter and multiplicity:|    compute floor(available/required)|    minimize the number of complete copies|return bottleneck','O(n) time; O(alphabet size) state.'],
1196:['weight','Take the most apples without exceeding weight five thousand.','Selecting lighter apples first maximizes count. Once the lightest remaining apple does not fit, no later apple can fit.','sort weights; total = taken = 0|for next lightest apple:|    test total+weight <= 5000|    take it if possible, otherwise stop|return taken','O(n log n) time; O(n) sorted-copy space.'],
1200:['arr','Return every pair of distinct values attaining the minimum absolute difference.','A minimum-gap pair must be adjacent in sorted order. A smaller gap replaces winners; an equal gap appends another pair.','sort values; best = infinity; pairs = []|for neighboring values:|    compute their difference|    replace pairs on improvement or append on a tie|return pairs','O(n log n) time; O(n) space.'],
1208:['s t maxCost','Find the longest aligned substring whose character replacement cost fits the budget.','Per-position costs are nonnegative. Expand right and remove left costs only when over budget to keep the longest feasible ending.','costs = absolute character-code differences|for right endpoint:|    add cost; shrink left while above budget|    maximize current window length|return best','O(n) time; O(n) explicit cost-array space.'],
1209:['s k','Repeatedly remove adjacent groups of k equal characters.','A stack stores surviving character runs. Removing a full group exposes its predecessor, allowing later characters to continue that earlier run.','stack = []|for character:|    extend matching top run or push a new run|    pop when its count reaches k|return expanded surviving runs','O(n) time and stack space.'],
1213:['arr1 arr2 arr3','Return the common values in three strictly increasing arrays.','When current values differ, the smallest cannot match a later value of the arrays already ahead. Advance only pointers at that smallest value.','i = j = k = 0; output = []|while all pointers remain valid:|    compare the three current values|    append equal values and advance all, else advance minima|return output','O(n+m+p) time; output space.'],
1217:['position','Move all chips to one position at minimum cost.','Free moves by two connect all positions of one parity. Choose the larger parity group as the destination and pay only for the smaller group.','even = odd = 0|for chip position:|    inspect position parity|    increment the matching count|return min(even,odd)','O(n) time; O(1) state.'],
1218:['arr difference','Find the longest subsequence with the specified fixed adjacent difference.','Store the best length ending at each value. The only possible predecessor is current minus difference, including repeated values when difference is zero.','lengths = {}; best = 0|for value in original order:|    read lengths[value-difference]|    write prior+1 at value and maximize best|return best','O(n) expected time; O(u) state.'],
1221:['s','Split a balanced L/R string into as many balanced pieces as possible.','Every return of prefix balance to zero is a safe cut. Taking it immediately cannot reduce the choices for the untouched suffix.','balance = pieces = 0|for L or R:|    add one for L or subtract one for R|    count a piece whenever balance becomes zero|return pieces','O(n) time; O(1) state.'],
1222:['queens king','Find all queens that can attack the king on an eight-by-eight board.','Only the first queen on each of eight outward rays can attack. A nearer queen blocks every farther queen in that direction.','index queen coordinates|for each of eight directions from king:|    step outward while inside the board|    record first queen and stop that direction|return attacking coordinates','O(q + board width) time; O(q) occupancy state.'],
1227:['n','Find the probability the last passenger occupies their own seat.','For more than one passenger, intermediate displaced choices leave the decisive first and last seats symmetric. With one passenger there is only one outcome.','read passenger count|distinguish n == 1 from larger flights|one passenger has probability one|otherwise first-seat and last-seat outcomes are symmetric|return 1 or 0.5','O(1) time and space.'],
1232:['coordinates','Decide whether all points lie on one straight line.','Fix a direction from the first two distinct points. Every later displacement must have zero cross product with it, avoiding division by slope.','direction = point1-point0|for every later point:|    compute cross product with its displacement|    reject any nonzero cross product|return true','O(n) time; O(1) algorithm state.'],
1247:['s1 s2','Find the fewest cross-string swaps needed to make two x/y strings equal.','Same-direction mismatches pair in one swap. Two leftover opposite directions require two swaps; an odd total number of mismatches is impossible.','xy = yx = 0|for aligned characters:|    ignore equality and classify mismatches|    pair equal directions; resolve opposite leftovers|return swaps or -1 for odd mismatch count','O(n) time; O(1) state.'],
1248:['nums k','Count contiguous subarrays containing exactly k odd numbers.','Replace values conceptually by oddness. Earlier prefixes with k fewer odd values form all valid subarrays ending here.','counts = {0:1}; odds = total = 0|for number:|    add its oddness to prefix count|    add counts[odds-k], then record current prefix|return total','O(n) time and state.'],
1249:['s','Remove the fewest parentheses needed to make the string valid.','Match closers to available openers. Unmatched closers and leftover openers are exactly the brackets that cannot participate in any valid pairing.','openers = []; removed = set|scan characters and match brackets:|    mark closers lacking an opener|    mark leftover openers after scanning|return characters whose indices were not marked','O(n) time and space.'],
1250:['nums','Decide whether an integer linear combination of the array can equal one.','The gcd generates all possible integer linear combinations. It equals one exactly when the requested combination exists.','divisor = 0|for value:|    compute gcd(divisor,value)|    retain the reduced common divisor|return divisor == 1','O(n log M) time; O(log M) recursive gcd stack.'],
};

export function validateExpansion(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vec=(a,min=1,max=100,low=0,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const text=(s,pattern=/^[a-z]+$/)=>typeof s==='string'&&s.length>=1&&s.length<=160&&pattern.test(s);
 const words=a=>Array.isArray(a)&&a.length>=1&&a.length<=40&&a.every(w=>text(w)&&w.length<=30);
 const increasing=a=>a.every((v,i)=>!i||v>a[i-1]);
 for(const key of ['nums','arr','arr1','arr2','arr3','data','distance','position','calories','weight','sticks'])if(key in input)check(vec(input[key],1,100,['arr','nums'].includes(key)?-10000:0),`${key}: use 1-100 bounded integers.`);
 for(const key of ['s','t','text','chars','word','keyboard'])if(key in input)check(text(input[key],id===1221?/^[LR]+$/:id===1249?/^[a-z()]+$/:/^[a-z]+$/),`${key}: use 1-160 characters from this problem's alphabet.`);
 for(const key of ['words','queries'])if(key in input)check(words(input[key]),`${key}: use 1-40 lowercase words of at most 30 characters.`);
 if(id===1100)check(integer(input.k,1,160),'k must be 1-160; a width beyond the string length has zero matches.');
 if(id===1108)check(typeof input.address==='string'&&/^(0|[1-9]\d{0,2})(\.(0|[1-9]\d{0,2})){3}$/.test(input.address)&&input.address.split('.').every(v=>Number(v)<=255),'Use a valid four-part IPv4 address without leading zeros.');
 if(id===1109)check(integer(input.n,1,60)&&Array.isArray(input.bookings)&&input.bookings.length>=1&&input.bookings.length<=50&&input.bookings.every(b=>vec(b,3,3,1)&&b[0]<=b[1]&&b[1]<=input.n),'Use n 1-60 and bookings [first,last,seats] with inclusive valid flight indices and positive seats.');
 if(id===1111){check(text(input.seq,/^[()]+$/),'Use 1-160 balanced parentheses.');let depth=0;for(const c of input.seq){depth+=c==='('?1:-1;check(depth>=0,'Parentheses must balance.');}check(depth===0,'Parentheses must balance.');}
 if(id===1118)check(integer(input.year,1583,9999)&&integer(input.month,1,12),'Use a Gregorian year 1583-9999 and month 1-12.');
 if(id===1122)check(input.arr1.every(v=>v>=0)&&input.arr2.every(v=>v>=0)&&new Set(input.arr2).size===input.arr2.length&&input.arr2.every(v=>input.arr1.includes(v)),'arr2 must contain distinct values found in nonnegative arr1.');
 if(id===1128)check(Array.isArray(input.dominoes)&&input.dominoes.length>=1&&input.dominoes.length<=80&&input.dominoes.every(p=>vec(p,2,2,1,9)),'Use 1-80 dominoes with two endpoints from 1 to 9.');
 if([1133,1144,1248,1250].includes(id))check(input.nums.every(v=>v>=(id===1133?0:1)),'Use positive numbers (zero is also allowed for largest unique number).');
 if(id===1134)check(integer(input.n,1,2147483647),'Use n from 1 through 2147483647.');
 if(id===1137)check(integer(input.n,0,37),'Use n from 0 through 37.');
 if(id===1150)check(integer(input.target,-10000)&&input.nums.every((v,i,a)=>!i||v>=a[i-1]),'Use sorted nums and a bounded integer target.');
 if(id===1151)check(input.data.every(v=>v===0||v===1),'Use binary values.');
 if(id===1154){check(typeof input.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(input.date),'Use YYYY-MM-DD.');const[y,m,d]=input.date.split('-').map(Number),lengths=[31,y%400===0||(y%4===0&&y%100!==0)?29:28,31,30,31,30,31,31,30,31,30,31];check(integer(y,1900,9999)&&integer(m,1,12)&&integer(d,1,lengths[m-1]),'Use a real Gregorian calendar date from 1900 onward.');}
 if(id===1165)check(input.keyboard.length===26&&new Set(input.keyboard).size===26,'keyboard must contain each lowercase letter exactly once.');
 if([1167,1196].includes(id))check(input[id===1167?'sticks':'weight'].every(v=>v>=1),'Lengths and weights must be positive.');
 if(id===1175)check(integer(input.n,1,100),'Use n from 1 through 100.');
 if(id===1176)check(integer(input.k,1,input.calories.length)&&integer(input.lower,0,1000000)&&integer(input.upper,input.lower,1000000),'Use a fitting positive window and 0 <= lower <= upper <= 1000000.');
 if(id===1184)check(integer(input.start,0,input.distance.length-1)&&integer(input.destination,0,input.distance.length-1),'Stops must be valid distance-array indices.');
 if(id===1200)check(input.arr.length>=2&&new Set(input.arr).size===input.arr.length,'Use at least two distinct values.');
 if(id===1208)check(input.s.length===input.t.length&&integer(input.maxCost,0,100000),'Use equally long lowercase strings and a nonnegative budget at most 100000.');
 if(id===1209)check(integer(input.k,2,100),'k must be 2-100.');
 if(id===1213)check([input.arr1,input.arr2,input.arr3].every(increasing),'All three arrays must be strictly increasing.');
 if(id===1217)check(input.position.every(v=>v>=1),'Chip positions must be positive.');
 if(id===1218)check(integer(input.difference,-10000),'Use a bounded integer difference.');
 if(id===1221)check([...input.s].filter(c=>c==='L').length*2===input.s.length,'Use a string with equal numbers of L and R.');
 if(id===1222)check(vec(input.king,2,2,0,7)&&Array.isArray(input.queens)&&input.queens.length>=1&&input.queens.length<=63&&input.queens.every(q=>vec(q,2,2,0,7)&&q.join(',')!==input.king.join(','))&&new Set(input.queens.map(q=>q.join(','))).size===input.queens.length,'Use distinct board coordinates 0-7, with no queen on the king.');
 if(id===1227)check(integer(input.n,1,100000),'Use n from 1 to 100000.');
 if(id===1232)check(Array.isArray(input.coordinates)&&input.coordinates.length>=2&&input.coordinates.length<=80&&input.coordinates.every(p=>vec(p,2,2,-10000))&&new Set(input.coordinates.map(p=>p.join(','))).size===input.coordinates.length,'Use 2-80 distinct bounded coordinate pairs.');
 if(id===1247)check(text(input.s1,/^[xy]+$/)&&text(input.s2,/^[xy]+$/)&&input.s1.length===input.s2.length,'Use equally long nonempty x/y strings.');
 if(id===1248)check(integer(input.k,1,input.nums.length),'k must be 1 through the array length.');
 return input;
}
