export const dpSpecs={
1101:['logs n','Find the earliest timestamp when every person belongs to one friendship network.','Process friendships by time and merge their connected components. The first moment only one component remains is the earliest universal connection.','sort logs by timestamp; components = n|for friendship a,b:|    find their disjoint-set roots|    merge different roots and decrement components|return first time components is one, else -1','O(e log e + e alpha(n)) time; O(n+e) copied-log and DSU space.'],
1105:['books shelfWidth','Arrange ordered books on shelves to minimize total height.','Try every fitting final shelf for each prefix. Its cost is the maximum height in that shelf plus the optimal cost of the earlier prefix.','dp[0] = 0; other costs = infinity|for prefix ending at end:|    grow the last shelf backward until width exceeds limit|    minimize dp[start] + tallest height|return dp[number of books]','O(n^2) time; O(n) DP space.'],
1124:['hours','Find the longest interval with more tiring days than other days.','Encode hours greater than eight as one and other days as minus one. Preserve earliest prefix occurrences to maximize the length of a positive-sum interval.','balance = best = 0; earliest = {}|for day:|    add +1 or -1|    use full positive prefix or earliest balance-1; record first occurrence|return best','O(n) expected time and map space.'],
1130:['arr','Build an ordered leaf tree with minimum total nonleaf cost.','Every interval can split between two adjacent leaves. Its root cost is the product of the two side maxima, plus the best costs for both smaller intervals.','precompute interval maxima; singleton costs = 0|for increasing interval lengths:|    try every split of the leaf interval|    minimize left cost + right cost + product of side maxima|return whole-interval cost','O(n^3) time; O(n^2) table space.'],
1131:['arr1 arr2','Maximize the sum of two absolute value differences and index distance.','Expand the two value absolute differences through four sign choices. For each choice, the largest minus smallest transformed value captures its maximum separation.','best = 0|for four pairs of value signs:|    transform each index to sign1*arr1 + sign2*arr2 + index|    track its range and maximize best|return best','O(n) time; O(1) algorithm state.'],
1135:['n connections','Connect every city with minimum total road cost, or report impossibility.','Kruskal chooses the cheapest edge that joins different components. Cycle edges add cost without improving connectivity.','sort roads by cost; start separate city groups|for road:|    compare component roots|    accept and merge only different components|return total if n-1 roads accepted, else -1','O(e log e + e alpha(n)) time; O(n+e) space.'],
1136:['n relations','Find the fewest semesters needed when all available courses can run together.','Courses with zero remaining prerequisites form the next semester. A cycle leaves some courses locked forever.','build outgoing edges and indegrees|while zero-indegree courses remain:|    take the current batch together|    unlock successors into a separate next batch|return semesters if all completed, else -1','O(n+e) time and space.'],
1139:['grid','Find the largest square whose entire border consists of ones.','Precompute rightward and downward one-runs. Four run lengths verify a candidate border without inspecting its interior.','build right and down run tables|for top-left cell and descending candidate size:|    verify bottom and right sides along with top and left|    retain the largest valid side|return side squared','O(rc min(r,c)) time; O(rc) tables.'],
1155:['n k target','Count dice outcomes reaching the target sum modulo one billion and seven.','For each die count, the final face partitions possibilities into disjoint previous-sum groups. Read a separate previous row so one die cannot be reused.','ways[0] = 1|for each die:|    for total and face, read previous ways[total-face]|    accumulate into a fresh modulo-reduced row|return ways[target]','O(n*k*target) time; O(target) state.'],
1162:['grid','Find the water cell farthest from its nearest land cell.','Start BFS from all land cells at once. The first wave to reach a water cell supplies its shortest land distance; retain the greatest such distance.','enqueue all land at distance zero|reject all-land or all-water input with -1|expand unvisited orthogonal neighbors|assign predecessor distance+1 and retain maximum|return greatest distance','O(n^2) time and space.'],
1177:['s queries','For each substring, decide whether rearrangement and at most k replacements can form a palindrome.','A parity mask reveals odd character counts. Every replacement can fix two odd counts, and one odd character may occupy the center.','build prefix XOR character masks|for left,right,k query:|    XOR endpoint prefixes and count set bits|    compare floor(oddCount/2) with k|return decisions','O(n+26q) time; O(n+q) space.'],
1182:['colors queries','Find the nearest occurrence of the requested color for every index query.','Store sorted occurrence positions by color. At the query insertion point, only the immediate neighbors can minimize distance.','group occurrence positions by color|for index,color query:|    binary search index in that color positions|    compare predecessor and successor, or report missing|return distances','O(n+q log n) time; O(n+q) space.'],
1186:['arr','Find the maximum nonempty subarray sum after at most one deletion.','Maintain states ending here with no deletion and with one deletion. The latter either extends a prior deleted state or deletes the current value from the previous kept state.','keep = arr[0]; drop = negative infinity; best = keep|for later value:|    read previous keep before overwriting it|    update keep, drop, and the greatest nonempty result|return best','O(n) time; O(1) state.'],
1190:['s','Reverse the contents of every matched parenthesis pair, starting from nested effects.','Precompute bracket partners, then walk the string with a direction. Jumping to a partner and reversing direction implements nested reversals in one traversal.','pair bracket positions using a stack|walk from index zero in forward direction:|    at a bracket, jump to partner and reverse direction|    otherwise append the encountered letter|return joined letters','O(n) time and space.'],
1191:['arr k','Find the maximum subarray sum in k concatenated copies, allowing an empty subarray.','At most two copies are needed to capture a boundary-crossing suffix and prefix. Additional complete middle copies help only if one copy has positive total.','total = sum(arr); best = ending = 0|run nonnegative Kadane over min(k,2) copies|retain greatest within-copy or boundary-crossing sum|add max(0,k-2)*max(0,total)|return sum modulo 1000000007','O(n) time; O(1) algorithm state.'],
1202:['s pairs','Find the lexicographically smallest string reachable through allowed index swaps.','Paths of swaps connect mutually interchangeable positions. Sort characters separately within each connected component and assign them to increasing indices.','union every allowed index pair|group indices by component root|sort each component characters|place smallest characters at smallest component indices|return rebuilt string','O(n log n + p alpha(n)) time; O(n+p) space.'],
1219:['grid','Collect the maximum gold along a path that never revisits a cell.','Try each positive cell as a start. Branch to unvisited orthogonal gold neighbors and unmark on return so independent paths can reuse cells.','best = 0; visited = false grid|start DFS at each gold cell:|    mark cell, add its gold, maximize best|    explore valid neighbors, then unmark before returning|return best','Exponential path search in g gold cells; O(g + grid size) traversal state, excluding replay snapshots.'],
1220:['n','Count vowel strings satisfying the permitted next-letter rules.','Keep five counts classified by final vowel. Every next row gathers counts from allowed predecessors, and all transitions read the previous row.','ways = one for each vowel at length one|for each later length:|    gather permitted predecessor counts per vowel|    reduce each next count modulo 1000000007|return sum of final counts modulo 1000000007','O(n) time; O(1) state.'],
1239:['arr','Find the longest concatenation of a subsequence whose characters are all distinct.','At every word choose skip or take. Taking is legal only if the word is internally unique and disjoint from all chosen letters.','best = 0|search words in their original order:|    always explore skipping the word|    explore taking it only with no repeated character|return greatest concatenation length','O(2^n * total character work) search; O(n + alphabet size) recursion state, excluding snapshots.'],
1252:['m n indices','Count odd cells after repeatedly incrementing selected rows and columns.','Only increment parity matters. A cell is odd exactly when its row and column parities differ; a doubly incremented intersection stays even.','rowParity = colParity = zero arrays|for selected row,column:|    toggle each corresponding parity|    count odd rows and odd columns|return oddRows*evenCols + evenRows*oddCols','O(operations + m+n) algorithm time; O(m+n) state, excluding displayed matrices.'],
1254:['grid','Count zero-valued land components enclosed away from every grid boundary.','Flood each component completely and remember whether any cell touches an edge. One boundary contact makes the entire component open.','copy grid; closed = 0|for each unvisited land cell:|    flood its orthogonal component and track edge contact|    increment closed only if no cell touched an edge|return closed','O(rc) time and visited-grid/queue space.'],
1260:['grid k','Shift a grid forward by k flattened positions with wraparound.','Flatten each coordinate, add k modulo the cell count, and unflatten its destination. Read only the original grid while constructing the shifted result.','allocate output of the same shape|for source row,column:|    destination = (row*cols+column+k) modulo cellCount|    write source into unflattened destination|return output grid','O(rc) time and output space.'],
};

export function validateDP(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=80,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const tuples=(a,width,min=0,max=100)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(p=>vector(p,width,width));
 const text=(s,regex=/^[a-z]+$/)=>typeof s==='string'&&s.length>=1&&s.length<=120&&regex.test(s);
 for(const key of ['arr','arr1','arr2','hours','colors'])if(key in input&&id!==1239)check(vector(input[key]),`${key}: use 1-80 bounded integers.`);
 if('grid'in input){const g=input.grid;check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vector(row,1,8)&&row.length===g[0].length),'Use a rectangular grid with 1-8 rows and columns.');if([1139,1162,1254].includes(id))check(g.every(row=>row.every(v=>v===0||v===1)),'Use a binary grid.');if(id===1162)check(g.length===g[0].length,'Use a square grid.');if(id===1219)check(g.flat().every(v=>v>=0)&&g.flat().filter(v=>v>0).length<=9,'Use nonnegative gold with at most nine positive cells for readable exhaustive paths.');}
 if([1101,1135,1136].includes(id))check(integer(input.n,2,40),'Use n from 2 through 40.');
 if(id===1101)check(tuples(input.logs,3,0,100)&&input.logs.every(([time,a,b])=>integer(time,0,10000)&&integer(a,0,input.n-1)&&integer(b,0,input.n-1)&&a!==b)&&new Set(input.logs.map(p=>p[0])).size===input.logs.length,'Use distinct bounded timestamps and different zero-based people in each friendship log.');
 if(id===1105)check(integer(input.shelfWidth,1,100)&&tuples(input.books,2,1,35)&&input.books.every(([w,h])=>integer(w,1,input.shelfWidth)&&integer(h,1,1000)),'Use 1-35 [width,height] books fitting positive shelfWidth, and positive heights at most 1000.');
 if(id===1124)check(input.hours.every(v=>integer(v,0,24)),'Use working hours between zero and twenty-four.');
 if(id===1130)check(input.arr.length>=2&&input.arr.length<=10&&input.arr.every(v=>integer(v,1,100)),'Use 2-10 positive leaf values at most 100.');
 if(id===1131)check(input.arr1.length===input.arr2.length&&input.arr1.length>=2,'Use equally long arrays with at least two entries.');
 if(id===1135)check(tuples(input.connections,3,0,100)&&input.connections.every(([a,b,cost])=>integer(a,1,input.n)&&integer(b,1,input.n)&&a!==b&&integer(cost,1,10000)),'Use [cityA,cityB,cost] edges with distinct 1-based endpoints and positive cost.');
 if(id===1136)check(tuples(input.relations,2,0,100)&&input.relations.every(([a,b])=>integer(a,1,input.n)&&integer(b,1,input.n)&&a!==b)&&new Set(input.relations.map(p=>p.join(','))).size===input.relations.length,'Use unique prerequisite pairs with distinct 1-based course indices.');
 if(id===1155)check(integer(input.n,1,20)&&integer(input.k,1,20)&&integer(input.target,1,100),'Use 1-20 dice, 1-20 faces, and target 1-100.');
 if([1177,1190,1202].includes(id))check(text(input.s,id===1190?/^[a-z()]+$/:/^[a-z]+$/),'Use 1-120 lowercase characters, plus balanced parentheses for reversal.');
 if(id===1177)check(tuples(input.queries,3,1,60)&&input.queries.every(([l,r,k])=>integer(l,0,input.s.length-1)&&integer(r,l,input.s.length-1)&&integer(k,0,120)),'Use [left,right,k] queries with valid inclusive endpoints and a nonnegative replacement budget.');
 if(id===1182)check(input.colors.every(c=>integer(c,1,3))&&tuples(input.queries,2,1,60)&&input.queries.every(([i,c])=>integer(i,0,input.colors.length-1)&&integer(c,1,3)),'Colors must be 1,2,3 and queries [validIndex,color].');
 if(id===1190){let depth=0;for(const c of input.s){if(c==='(')depth++;if(c===')')depth--;check(depth>=0,'Parentheses must be balanced.');}check(depth===0,'Parentheses must be balanced.');}
 if(id===1191)check(integer(input.k,1,100000),'Use a repetition count from 1 through 100000.');
 if(id===1202)check(tuples(input.pairs,2,0,80)&&input.pairs.every(p=>p.every(v=>integer(v,0,input.s.length-1))),'Use at most 80 valid zero-based index pairs.');
 if(id===1220)check(integer(input.n,1,100),'Use a vowel-string length from 1 through 100 for trace playback.');
 if(id===1239)check(Array.isArray(input.arr)&&input.arr.length>=1&&input.arr.length<=10&&input.arr.every(w=>text(w)&&w.length<=26),'Use 1-10 lowercase words of at most 26 characters for inspectable subset search.');
 if(id===1252)check(integer(input.m,1,10)&&integer(input.n,1,10)&&tuples(input.indices,2,1,60)&&input.indices.every(([r,c])=>integer(r,0,input.m-1)&&integer(c,0,input.n-1)),'Use dimensions 1-10 and valid [row,column] operations.');
 if(id===1260)check(integer(input.k,0,10000),'Use a shift count from zero through 10000.');
 return input;
}
