export const continuingSpecs={
1481:['arr k','Minimize the number of distinct integers after exactly k removals.','A distinct value disappears only when its whole frequency bucket is removed. Spend deletions on the smallest buckets first; leftover partial deletions cannot remove another value.','count values and sort buckets by frequency|for next cheapest bucket:|    compare its count with remaining k|    remove whole bucket if affordable, otherwise stop|return remaining distinct count','O(n+u log u) time; O(u) state.'],
1482:['bloomDay m k','Find the earliest day that supplies m disjoint bouquets of k adjacent flowers.','For one candidate day, consecutive bloomed flowers form disjoint greedy groups. Feasibility only improves with time, allowing a binary search on days.','reject if m*k exceeds flower count|binary search earliest feasible day:|    count disjoint k-runs of bloomed flowers|    lower upper bound if enough, otherwise raise lower bound|return first feasible day','O(n log D) time; O(1) state.'],
1486:['n start','Compute the XOR of n values defined by start plus twice their index.','Generate terms directly and fold them into one XOR accumulator. Each term contributes once in the prescribed arithmetic sequence.','result = 0|for index zero through n-1:|    value = start+2*index|    XOR value into result|return result','O(n) time; O(1) algorithm state, excluding displayed terms.'],
1487:['names','Assign distinct names using the smallest available numeric suffix when needed.','Track all assigned names and the next suffix to try for each base. Existing names containing parentheses can occupy candidates too, so check full-name availability.','used names map = {}; output = []|for requested name:|    use directly if unused, otherwise seek first unused suffix|    reserve chosen name and update next suffix hint|return assigned names','Amortized candidate-search time plus generated-name lengths; O(n) name state.'],
1491:['salary','Compute the average after excluding the minimum and maximum salary entries.','Track both extremes and the total in one scan. Subtract the extremes and divide by the number of remaining employees.','sum = 0; minimum = infinity; maximum = negative infinity|for salary:|    update sum and both extremes|    subtract minimum and maximum from final sum|return adjusted sum divided by length-2','O(n) time; O(1) state.'],
1492:['n k','Find the kth positive factor of n in ascending order.','Scanning candidate divisors increasingly gives factor rank directly. Count only exact divisors and return minus one when there are fewer than k.','rank = 0|for candidate one through n:|    test n modulo candidate equals zero|    increment rank and return candidate when rank == k|return -1','O(n) direct-search time; O(1) state.'],
1493:['nums','Find the longest all-one subarray after deleting exactly one element.','Maintain an interval with at most one zero. Its length minus one is achievable after the mandatory deletion, even when all current entries are one.','left = zeroCount = best = 0|for right,value:|    add zero count and shrink while more than one zero remains|    maximize right-left, leaving room for the mandatory deletion|return best','O(n) time; O(1) state.'],
1496:['path','Decide whether a grid walk revisits a previously occupied point.','Remember coordinates, starting with the origin. Crossing happens on the first repeated coordinate after any unit move.','position = origin; seen = {origin}|for direction:|    move one unit on the matching axis|    return true if coordinate was seen, otherwise record it|return false','O(n) expected time and coordinate-set space.'],
1497:['arr k','Pair all array positions so each pair sum is divisible by k.','Remainder r pairs with k-r. Complementary buckets need equal sizes; a bucket pairing with itself needs an even size.','normalize all remainders and count them|for remainder bucket:|    locate its complementary remainder|    require equal counts or even self-pair count|return whether every bucket is pairable','O(n+u) time; O(u) count state.'],
1498:['nums target','Count nonempty subsequences whose minimum plus maximum does not exceed target.','After sorting, fix each possible minimum. If the current maximum fits, every subset of eligible interior positions is allowed; otherwise lower the maximum.','sort nums and precompute powers of two modulo M|while left <= right:|    compare endpoint sum with target|    count all subsets for valid minimum or discard invalid maximum|return count modulo 1000000007','O(n log n) time; O(n) state.'],
1502:['arr','Decide whether rearranging values can form an arithmetic progression.','Sorting fixes the only possible order up to reversal. Every neighboring difference must equal the first one.','sort a copy|difference = second-first|for later neighboring pair:|    reject if its difference changes|return true','O(n log n) time; O(n) copy space.'],
1503:['n left right','Find when the final ant falls off the plank.','Equal-speed collisions exchange identities without changing the set of trajectories. Treat ants as passing through and take the longest direct exit time.','times = left positions plus n-right positions|for ant exit time:|    regard collisions as identity exchanges|    retain the largest direct time|return maximum exit time','O(number of ants) time and displayed exit-time space.'],
1504:['mat','Count every all-one rectangular submatrix.','Maintain consecutive one heights for each bottom row. For a fixed column interval, its minimum height counts every possible all-one rectangle ending on that row.','heights = zero array; count = 0|for bottom row:|    update consecutive heights|    extend every right boundary leftward and add the running minimum|return count','O(rows*columns^2) time; O(columns) state.'],
1508:['nums n left right','Sum the requested rank range of sorted contiguous-subarray sums.','Enumerate each start and extend its running sum. Equal sums remain separate entries because they represent different subarrays.','collect all contiguous sums|sort the complete sum list|select one-based ranks left through right|sum selected entries modulo 1000000007|return modular sum','O(n^2 log n) time; O(n^2) stored sums.'],
1509:['nums','Minimize the array range after changing at most three entries.','Only sorted extremes need modification. Distribute three changes across the smallest and largest ends in four possible ways.','return zero when length <= 4|sort values|for zero through three changed small extremes:|    evaluate remaining maximum minus minimum|return least range','O(n log n) time; O(n) sorted-copy space.'],
1510:['n','Decide whether the first player wins by repeatedly removing a nonzero square number of stones.','A state is winning if any square removal reaches a losing state. Build states in increasing size so each opponent result is already known.','win[0] = false|for stone count one through n:|    inspect each square no greater than the count|    mark winning if any remainder is losing|return win[n]','O(n sqrt n) time; O(n) DP space.'],
1513:['s','Count substrings consisting only of ones modulo one billion and seven.','Each ending position contributes the current consecutive-one run length. Zeros reset that length and prevent substrings crossing them.','run = count = 0|for bit:|    extend run for one or reset for zero|    add run into modular count|return count','O(n) time; O(1) state.'],
1518:['numBottles numExchange','Count bottles drinkable using repeated exchanges of empty bottles.','After each exchange, newly consumed bottles become empty again. Preserve the unexchanged remainder and continue while enough empty bottles remain.','consumed = empty = initial bottles|while empty >= exchange requirement:|    compute full bottles from the exchange|    add them to consumed and combine new empties with remainder|return consumed','O(log(initial bottles)) rounds for fixed exchange rate; O(1) state.'],
1523:['low high','Count odd integers in an inclusive interval.','Count odds through high and subtract odds strictly before low. This handles odd and even endpoints without enumerating the interval.','through = floor((high+1)/2)|before = floor(low/2)|subtract before from through|preserve inclusive endpoint interpretation|return count','O(1) time and space.'],
1524:['arr','Count subarrays with odd sum modulo one billion and seven.','A subarray sum is odd when its two prefix parities differ. Count earlier opposite-parity prefixes before recording the new prefix.','evenPrefixes = 1; oddPrefixes = count = 0|for value:|    update prefix parity|    add opposite-prefix count then record current parity|return modular count','O(n) time; O(1) state.'],
1525:['s','Count splits whose nonempty halves contain the same number of distinct letters.','Transfer characters from a complete right multiset into the left multiset. Remove right keys at zero frequency before comparing distinct counts.','right = frequencies(s); left = {}; good = 0|for split before final character:|    transfer current character from right to left|    count equal distinct-key totals|return good','O(n) time; O(alphabet size) state.'],
1526:['target','Count minimum interval increments needed to form the target from zeros.','Existing increment layers can continue across level or falling heights. Each rise requires new layers beginning at that index.','previous = operations = 0|for target height:|    compute positive part of height-previous|    add that rise and update previous|return operations','O(n) time; O(1) state.'],
1528:['s indices','Reorder characters into their specified destination indices.','Indices describe final destinations, not insertion positions. Write every original character once into a separate output array.','output = empty slots|for original character,index:|    read its destination in indices|    write character at that final slot|return joined output','O(n) time and output space.'],
1529:['target','Minimize suffix flips turning an all-zero binary string into target.','All previous suffix flips give the current position one shared effective state. A mismatch forces a flip starting here; equality needs no action.','state = zero; flips = 0|for target bit:|    compare bit with effective shared state|    flip and update state only on mismatch|return flips','O(n) time; O(1) state.'],
1534:['arr a b c','Count index triples satisfying all three absolute-difference limits.','Reject an invalid first pair before trying its third index. For surviving pairs, check both remaining distances independently.','count = 0|enumerate i < j < k:|    first require abs(arr[i]-arr[j]) <= a|    count when the other two differences fit b and c|return count','O(n^3) time; O(1) counting state.'],
1535:['arr k','Find the first front-of-array champion to win k consecutive comparisons.','Only the current champion and its win streak matter. After one scan the greatest value is champion forever, even when k exceeds the array length.','champion = first value; wins = 0|for each following challenger:|    retain winner or replace champion and restart wins at one|    return champion when wins reaches k|return final champion','O(n) time; O(1) state.'],
1539:['arr k','Find the kth positive integer missing from a strictly increasing array.','At index i, arr[i]-i-1 counts missing positives before that value. Binary search the first index where this count reaches k.','low = 0; high = length|while low < high:|    missing = arr[mid]-mid-1|    search right below k, otherwise retain left half|return low+k','O(log n) time; O(1) state.'],
1540:['s t k','Decide whether at most k uniquely numbered shift moves can transform s into t.','Equal required shifts compete for the same move residue modulo twenty-six. Schedule successive occurrences at shift, shift+26, shift+52, and check the budget.','reject unequal lengths; shiftUse = zeros|for aligned characters:|    compute required forward cyclic shift|    reserve next move with that residue; reject if beyond k|return true','O(n) time; O(26) state.'],
1544:['s','Repeatedly remove adjacent copies of the same letter in opposite cases.','A stack retains the reduced prefix. A new character cancels only with an opposite-case copy at the top, exposing earlier characters for future cancellations.','stack = []|for character:|    compare letter identity and case with stack top|    pop an opposite-case match, otherwise push|return joined stack','O(n) time and stack space.'],
1545:['n k','Find the kth bit in the recursively mirrored and inverted binary sequence.','The center is one. Left-half positions descend unchanged; right-half positions mirror into the previous level and toggle inversion.','index = k; inverted = false|for levels n down to two:|    compare index with central position|    return center or mirror right half and toggle inversion|return base zero after applying inversion','O(n) time; O(1) state.'],
1546:['nums target','Maximize the number of disjoint subarrays summing to target.','Finish the earliest available valid interval. Reset prefix state afterward so later matches cannot overlap the chosen interval.','prefixes = {0}; sum = count = 0|for value:|    update sum and look for sum-target|    on match count interval and reset, otherwise record sum|return count','O(n) expected time and prefix-set space.'],
1550:['arr','Decide whether three consecutive values are all odd.','A single run counter captures the only needed history. Odd values extend it and even values reset it.','run = 0|for value:|    increment for odd or reset for even|    return true once run reaches three|return false','O(n) time; O(1) state.'],
1551:['n','Equalize the first n odd numbers with minimum paired increment/decrement operations.','The target value is their mean n. Symmetric low and high values exchange units, so sum only the deficits of the lower half.','moves = 0|for lower-half odd value 2*i+1:|    compute its deficit below n|    add that deficit once for the symmetric pair|return moves','O(n) time; O(1) state.'],
1552:['position m','Place m balls to maximize the minimum distance between any pair.','For a candidate gap, placing each ball at the earliest fitting basket leaves maximal room for later balls. Feasibility is monotone as the required gap grows.','sort basket positions|binary search candidate minimum gap:|    greedily count earliest fitting placements|    raise gap after success or lower it after failure|return greatest feasible gap','O(n log n + n log range) time; O(n) sorted-copy space.'],
1556:['n','Format a nonnegative integer with dot-separated groups of three digits.','Group from the right so place-value boundaries remain correct. The leftmost group may contain fewer than three digits.','digits = decimal representation|take groups of three from the right|prepend each group into output order|join groups with dots|return formatted number','O(d) output size; O(d^2) worst-case group prepending for d digits.'],
1557:['n edges','Find the smallest starting-vertex set reaching every vertex of a directed acyclic graph.','A zero-indegree vertex cannot be reached from any other start and is mandatory. In a DAG, every other vertex descends from at least one such source.','mark every edge destination as having incoming edges|inspect each graph vertex|select exactly vertices with no incoming edge|preserve vertex ordering in the output|return sources','O(n+e) time; O(n) state.'],
1558:['nums','Minimize individual increments and global doublings needed to build the target array.','Each one bit requires an individual increment. Doublings are shared across entries, so their count is the greatest binary length minus one.','increments = doublings = 0|for target value:|    count its one bits and highest bit position|    add one bits; maximize shared doublings|return increments+doublings','O(n log M) time; O(log M) digit space.'],
1560:['n rounds','Find the most visited sectors during clockwise rounds on a circular track.','Count the initial sector once. Each later segment counts only newly entered sectors, so shared round endpoints are not duplicated.','visits = zero sector counts; mark starting sector|for successive round endpoint:|    advance clockwise with wraparound|    count entered sectors until reaching endpoint|return all sectors tied for most visits','O(n*rounds) direct simulation time; O(n) space.'],
1561:['piles','Maximize your coins when Alice takes the largest and Bob the smallest of each chosen triple.','Reserve the smallest piles for Bob. Pair each of your choices with the largest remaining pile for Alice, taking the second-largest yourself.','sort piles; coins = 0|while piles remain:|    give greatest to Alice and smallest to Bob|    add the next greatest to your total|return coins','O(n log n) time; O(n) sorted-copy space.'],
1566:['arr m k','Detect a consecutive pattern of length m repeated at least k times without overlap.','Comparing entries m positions apart measures continuity between adjacent copies. A run of (k-1)*m equal comparisons certifies the required repeated blocks.','matches = 0|for index from m onward:|    compare arr[index] with arr[index-m]|    extend or reset run; succeed at (k-1)*m|return false if no repeated span exists','O(n) time; O(1) state.'],
1567:['nums','Find the longest subarray with strictly positive product.','Track longest positive-product and negative-product suffix lengths. A negative value swaps their roles, a positive preserves signs, and zero resets both.','positive = negative = best = 0|for value:|    read both previous suffix lengths|    update according to sign and maximize positive length|return best','O(n) time; O(1) state.'],
1570:['nums1 nums2','Compute the dot product of two vectors using their nonzero entries.','Zero entries contribute nothing. Index one vector sparsely and multiply only when the other has a nonzero value at the same index.','map first-vector nonzero positions|scan second-vector positions|when both are nonzero, multiply aligned values|accumulate their products|return dot product','O(n) time; O(nonzero first entries) state.'],
1572:['mat','Sum the primary and secondary matrix diagonals without counting the center twice.','Each row contributes its matching-column and mirrored-column entries. In an odd-sized matrix those coordinates coincide only at the center.','sum = 0|for row:|    add mat[row][row]|    add mirrored column only when different|return sum','O(n) time; O(1) state.'],
1576:['s','Replace question marks so no neighboring characters are equal.','Each unknown position excludes at most its two neighbors. Trying three letters guarantees a choice while preserving all fixed characters.','copy characters|for each question mark:|    exclude preceding and following known letters|    choose an available letter from a,b,c|return completed string','O(n) time and copied-character space.'],
1578:['colors neededTime','Remove minimum total cost so adjacent retained balloons have different colors.','In every maximal equal-color run, exactly one balloon should remain. Keep the one with greatest removal cost and pay for all others.','groupTotal = groupMax = removed = 0|scan each color run:|    add removal times and track their maximum|    charge groupTotal-groupMax at every run boundary|return completed cost plus final run cost','O(n) time; O(1) state.'],
1582:['mat','Count one-valued cells that are the only one in both their row and column.','Row and column sums summarize uniqueness. A one qualifies precisely when both associated sums are one.','compute row sums and column sums|visit every one cell:|    compare both sums with one|    count cells meeting both conditions|return count','O(rc) time; O(r+c) summary state.'],
1584:['points','Connect all points at minimum total Manhattan edge cost.','Prim maintains each unconnected point cheapest attachment to the current tree. Choose the least attachment and update costs using the newly connected point.','distance[0] = 0; other distances = infinity|repeat once per point:|    choose unused point with minimum attachment cost|    add it and relax Manhattan costs to all unused points|return total tree cost','O(n^2) time; O(n) state.'],
1588:['arr','Sum all odd-length contiguous subarrays.','Count how many odd-length intervals contain each position, then add that many copies of its value. Half of its possible start/end combinations, rounded up, have odd length.','sum = 0|for index,value:|    containing = (index+1)*(length-index)|    add value*ceil(containing/2)|return sum','O(n) time; O(1) state.'],
1590:['nums p','Remove the shortest proper subarray so the remaining sum is divisible by p.','The removed interval needs the same remainder as the total. Preserve the latest index per prefix remainder to make future matching removals shortest.','needed = total modulo p; return zero if already divisible|scan normalized prefix remainders:|    seek an earlier remainder smaller by needed|    minimize interval length and update latest prefix index|return best unless it removes the entire array','O(n) expected time and map space.'],
1592:['text','Redistribute spaces evenly between words and put leftovers at the end.','Count original spaces independently from words. Divide by the number of word gaps, with all spaces trailing when there is only one word.','count spaces and split nonempty words|gap = floor(spaces/(wordCount-1)) when multiple words|remainder = spaces-gap*(wordCount-1)|join words with gap spaces and append remainder|return rearranged text','O(n) time and output space.'],
1598:['logs','Find how many parent-folder moves return to the main folder after navigation logs.','Only folder depth matters. Child moves add one, current-folder moves do nothing, and parent moves cannot reduce depth below zero.','depth = 0|for navigation command:|    distinguish child, current, and parent moves|    update depth with a floor of zero|return depth','O(n) time; O(1) state.'],
1603:['big medium small carTypes','Process parking requests with separate fixed capacities for three car types.','A request consumes one slot only from its exact type. Rejecting a full category must leave every capacity unchanged.','remaining = capacities by type; answers = []|for requested car type:|    check positive remaining capacity for that type|    accept and decrement, or reject without mutation|return acceptance decisions','O(requests) time; O(1) capacity state plus output.'],
1605:['rowSum colSum','Construct a nonnegative matrix matching all row and column totals.','Place the smaller current unmet row or column demand. This satisfies at least one boundary and preserves equality of remaining total demand.','copy row and column demands; matrix = zeros|while rows and columns remain:|    place min(current row demand,current column demand)|    subtract and advance any satisfied boundary|return matrix','O(rows*columns) allocation time; output space plus copied demands.'],
1608:['nums','Find x such that exactly x array entries are at least x.','A valid count cannot exceed the array length. Enumerate only that bounded candidate range and compare each candidate with its actual qualifying count.','for x from zero through length:|    count values >= x|    compare count with x|    return x on equality|return -1 if absent','O(n^2) direct-counting time; O(1) state.'],
1614:['s','Find the greatest parentheses nesting depth in an arithmetic expression.','Opening parentheses raise active depth and closing parentheses lower it. Other expression characters have no effect on nesting.','depth = best = 0|for expression character:|    adjust depth only for opening or closing parenthesis|    retain the greatest depth reached|return best','O(n) time; O(1) state.'],
};

export function validateContinuing(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const pairs=(a,min=0,max=100)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(p=>vector(p,2,2));
 const text=(s,regex=/^[a-z]+$/)=>typeof s==='string'&&s.length>=1&&s.length<=160&&regex.test(s);
 for(const key of ['arr','nums','nums1','nums2','bloomDay','salary','stoneValue','position','piles','rounds','neededTime','rowSum','colSum','indices','carTypes'])if(key in input)check(vector(input[key]),`${key}: use 1-100 bounded integers.`);
 if('target'in input&&id===1526)check(vector(input.target,1,100,0),'Use nonnegative target heights.');
 for(const key of ['s','t','colors'])if(key in input)check(text(input[key],id===1513?/^[01]+$/:id===1544?/^[A-Za-z]+$/:id===1576?/^[a-z?]+$/:id===1614?/^[0-9()+*/.\-]+$/:/^[a-z]+$/),`${key}: use 1-160 characters valid for the problem.`);
 for(const key of ['mat'])if(key in input){const g=input[key];check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vector(row,1,8)&&row.length===g[0].length),'Use a rectangular matrix with 1-8 rows and columns.');if([1504,1582].includes(id))check(g.flat().every(v=>v===0||v===1),'Use a binary matrix.');if(id===1572)check(g.length===g[0].length,'Diagonal sum requires a square matrix.');}
 if(id===1481)check(integer(input.k,0,input.arr.length),'Use removals k from zero through the array length.');
 if(id===1482)check(input.bloomDay.every(v=>v>=1)&&integer(input.m,1,100)&&integer(input.k,1,input.bloomDay.length),'Use positive bloom days and bouquet parameters; m may exceed available capacity.');
 if(id===1486)check(integer(input.n,1,100)&&integer(input.start,0,1000),'Use n 1-100 and start 0-1000.');
 if(id===1487)check(Array.isArray(input.names)&&input.names.length>=1&&input.names.length<=50&&input.names.every(s=>text(s,/^[a-z0-9()]+$/)&&s.length<=40),'Use 1-50 nonempty names made from lowercase letters, digits, and parentheses.');
 if(id===1491)check(input.salary.length>=3&&input.salary.every(v=>v>=1)&&new Set(input.salary).size===input.salary.length,'Use at least three distinct positive salaries.');
 if(id===1492)check(integer(input.n,1,1000)&&integer(input.k,1,1000),'Use n and k from one through one thousand.');
 if(id===1493)check(input.nums.every(v=>v===0||v===1),'Use a binary array.');
 if(id===1496)check(text(input.path,/^[NSEW]+$/),'Use a nonempty path of N,S,E,W directions.');
 if(id===1497)check(input.arr.length%2===0&&integer(input.k,1,10000),'Use an even number of values and a positive divisor.');
 if(id===1498)check(input.nums.every(v=>v>=1)&&integer(input.target,1,100000),'Use positive nums and a positive bounded target.');
 if(id===1502)check(input.arr.length>=2,'Use at least two values.');
 if(id===1503)check(integer(input.n,1,10000)&&vector(input.left,0,100,0,input.n)&&vector(input.right,0,100,0,input.n)&&input.left.length+input.right.length>=1&&new Set([...input.left,...input.right]).size===input.left.length+input.right.length,'Use at least one ant at a distinct position within the plank on either direction list.');
 if(id===1508)check(integer(input.n,1,18)&&input.nums.length===input.n&&input.nums.every(v=>v>0)&&integer(input.left,1,input.n*(input.n+1)/2)&&integer(input.right,input.left,input.n*(input.n+1)/2),'Use n 1-18 equal to nums length and a valid one-based sum rank range.');
 if(id===1510)check(integer(input.n,1,150),'Use one through 150 stones for full game-state playback.');
 if(id===1518)check(integer(input.numBottles,1,10000)&&integer(input.numExchange,2,10000),'Use positive initial bottles and an exchange requirement of at least two.');
 if(id===1523)check(integer(input.low,0,1000000000)&&integer(input.high,input.low,1000000000),'Use 0 <= low <= high <= one billion.');
 if([1524,1558,1608].includes(id))check(input[id===1524?'arr':'nums'].every(v=>v>=0),'Use nonnegative array values.');
 if(id===1528)check(input.indices.length===input.s.length&&input.indices.every(v=>integer(v,0,input.s.length-1))&&new Set(input.indices).size===input.indices.length,'indices must be a permutation of all string positions.');
 if(id===1529)check(text(input.target,/^[01]+$/),'Use a nonempty binary target string.');
 if(id===1534)check(input.arr.length>=3&&input.arr.length<=12&&[input.a,input.b,input.c].every(v=>integer(v,0,10000)),'Use 3-12 array values and nonnegative difference bounds.');
 if(id===1535)check(input.arr.length>=2&&new Set(input.arr).size===input.arr.length&&integer(input.k,1,1000000000),'Use at least two distinct values and positive k at most one billion.');
 if(id===1539)check(input.arr.every((v,i,a)=>v>=1&&(!i||v>a[i-1]))&&integer(input.k,1,10000),'Use a strictly increasing positive array and positive k.');
 if(id===1540)check(integer(input.k,0,1000000),'Use a nonnegative move budget at most one million.');
 if(id===1545)check(integer(input.n,1,25)&&integer(input.k,1,2**input.n-1),'Use sequence level 1-25 and a valid one-based bit index.');
 if(id===1546)check(integer(input.target,-10000),'Use a bounded integer target sum.');
 if(id===1551)check(integer(input.n,1,100),'Use n from one through one hundred.');
 if(id===1552)check(input.position.length>=2&&new Set(input.position).size===input.position.length&&input.position.every(v=>v>=1)&&integer(input.m,2,input.position.length),'Use distinct positive basket positions and 2 <= m <= basket count.');
 if(id===1556)check(integer(input.n,0,2147483647),'Use a nonnegative 32-bit signed integer.');
 if(id===1557){check(integer(input.n,1,50)&&pairs(input.edges)&&input.edges.every(([a,b])=>integer(a,0,input.n-1)&&integer(b,0,input.n-1)&&a!==b),'Use at most fifty vertices and valid directed edges.');const graph=Array.from({length:input.n},()=>[]),degree=Array(input.n).fill(0);for(const[a,b]of input.edges){graph[a].push(b);degree[b]++;}const q=degree.flatMap((d,i)=>d===0?[i]:[]);for(let i=0;i<q.length;i++)for(const v of graph[q[i]])if(--degree[v]===0)q.push(v);check(q.length===input.n,'This source-set problem requires an acyclic directed graph.');}
 if(id===1560)check(integer(input.n,2,30)&&input.rounds.length>=2&&input.rounds.length<=15&&input.rounds.every((v,i,a)=>integer(v,1,input.n)&&(!i||v!==a[i-1])),'Use 2-30 sectors and 2-15 valid endpoints with adjacent endpoints distinct.');
 if(id===1561)check(input.piles.length%3===0&&input.piles.every(v=>v>=1),'Use a multiple of three positive pile sizes.');
 if(id===1566)check(integer(input.m,1,100)&&integer(input.k,2,100),'Use a positive pattern length and at least two required repetitions.');
 if(id===1570)check(input.nums1.length===input.nums2.length,'Sparse vectors must have matching dimensions.');
 if(id===1576)check([...input.s].every((c,i)=>!i||c==='?'||input.s[i-1]==='?'||c!==input.s[i-1]),'Fixed neighboring letters must already differ.');
 if(id===1578)check(input.neededTime.length===input.colors.length&&input.neededTime.every(v=>v>=1),'Each balloon needs one positive removal time.');
 if(id===1584)check(pairs(input.points,1,30),'Use 1-30 bounded coordinate pairs.');
 if(id===1590)check(input.nums.every(v=>v>=1)&&integer(input.p,1,10000),'Use positive values and divisor p.');
 if(id===1592)check(text(input.text,/^[a-z ]+$/)&&/[a-z]/.test(input.text),'Use lowercase words and spaces with at least one word.');
 if(id===1598)check(Array.isArray(input.logs)&&input.logs.length>=1&&input.logs.length<=80&&input.logs.every(log=>typeof log==='string'&&/^(?:\.\.?|[a-z0-9]+)\/$/.test(log)),'Use child-folder commands ending in /, ./, or ../.');
 if(id===1603)check([input.big,input.medium,input.small].every(v=>integer(v,0,100))&&input.carTypes.every(v=>integer(v,1,3)),'Use nonnegative capacities and car types one, two, or three.');
 if(id===1605)check(input.rowSum.length<=10&&input.colSum.length<=10&&[...input.rowSum,...input.colSum].every(v=>v>=0)&&input.rowSum.reduce((a,b)=>a+b,0)===input.colSum.reduce((a,b)=>a+b,0),'Use up to ten nonnegative row and column sums with equal totals.');
 if(id===1614){let depth=0;for(const c of input.s){if(c==='(')depth++;if(c===')')depth--;check(depth>=0,'Parentheses must be balanced.');}check(depth===0,'Parentheses must be balanced.');}
 return input;
}
