export const advanceSpecs={
1696:['nums k','Maximize score while jumping forward at most k positions and ending at the last index.','Dynamic programming needs the greatest score among the last k reachable positions. A decreasing candidate deque discards expired positions and weaker candidates.','dp[0] = nums[0]; candidates = [0]|for each later index:|    discard indices farther than k behind|    add current value to best candidate and remove dominated scores|return score at final index','O(n^2) worst case with JavaScript array shifts; O(n) state.'],
1697:['n edgeList queries','Answer whether each pair of vertices is connected using only edges shorter than its limit.','Sort edges and queries by weight threshold. As limits rise, union newly eligible edges; component membership gives each answer, stored in its original query order.','sort edges and indexed queries by threshold|initialize separate vertex components|for query, union all edges with weight < limit|compare endpoint roots and save by original index|return answers','O(E log E+Q log Q+(E+Q) alpha(n)) time; O(n+E+Q) space.'],
1698:['s','Count distinct nonempty substrings rather than their occurrences.','Enumerate every start and end, adding substring text to a set. Identical text from different positions contributes only once.','distinct = empty set|for start position:|    for every later end position:|        insert substring text into set|return set size','O(n^3) copied-character work; O(n^3) conservative string-storage bound.'],
1700:['students sandwiches','Count students left waiting when the top sandwich can no longer be served.','Queue rotation changes order but not preferences. A top sandwich can be served exactly when some remaining student wants that type.','count remaining preferences zero and one|read sandwiches from top onward|stop if current type has no waiting student|otherwise consume one matching preference|return remaining student count','O(n) time; O(1) count state.'],
1701:['customers','Compute average waiting time for customers served by one cook in arrival order.','Each preparation starts at the later of the arrival and previous completion. Waiting includes both queue delay and the customer own cooking time.','available = totalWaiting = 0|for arrival,cookingTime:|    start = max(available,arrival)|    available = start+cookingTime; add available-arrival|return totalWaiting/customerCount','O(n) time; O(1) state.'],
1702:['binary','Find the greatest binary string reachable by the permitted 00-to-10 and 10-to-01 transformations.','A prefix before the first zero stays all ones. The remaining zeros consolidate into one zero at firstZero+zeroCount-1, with ones at every other position.','find first zero; return input if absent|count zeros from that position onward|create an all-one output|place one zero at firstZero+zeroCount-1|return maximal string','O(n) time and output space.'],
1704:['s','Determine whether the two equal-length halves contain the same number of vowels.','Count both uppercase and lowercase vowels in each half. Equal character counts or matching letters are unnecessary; only vowel totals matter.','split position = length/2|scan characters|count vowels in the corresponding half|compare both totals|return whether they agree','O(n) time; O(1) state.'],
1705:['apples days','Eat the maximum number of apples when one can be eaten per day and batches expire.','Maintain available batches by expiration day. Discard rotten batches, then eat from the earliest expiration so longer-lived fruit remains available later.','for each production day and while batches remain:|    add new apples with expiration day|    discard expired batches|    eat one apple from earliest expiration|return total eaten','O((n+D)*n log n) conservative sorted-list bound; O(n) batch state.'],
1706:['grid','Find the exit column of a ball dropped above each column, or minus one when trapped.','A row allows a ball to move diagonally only when the current board and its neighbor slope together. A wall or V-shaped opposing pair traps the ball.','for each start column:|    inspect every row along its path|    require in-bounds neighbor with matching slope|    move into neighbor column or record trapped|return exit columns','O(rows*columns) time; O(columns) output space.'],
1708:['nums k','Choose the lexicographically largest contiguous subarray of length k.','Since all values are distinct, competing starts differ at their first value. The largest first value among legal starting positions determines the answer.','bestStart = 0|scan starts through length-k|replace bestStart when its first value is smaller|take k entries from bestStart|return chosen subarray','O(n) time; O(k) output space.'],
1710:['boxTypes truckSize','Load a limited number of boxes to maximize total units.','Every box costs one truck slot, so units per box alone determine priority. Take the highest-unit types first until capacity is exhausted.','sort types by units per box descending|for each type:|    take min(available boxes,remaining capacity)|    add units and reduce capacity|return units loaded','O(types log types) time; O(types) sorted-copy space.'],
1711:['deliciousness','Count pairs of meals whose total deliciousness is a positive power of two.','For each current value, inspect power-of-two target sums and count complements among earlier values. This counts each pair once even when values repeat.','previous counts = {}; pairs = 0|for each value:|    for powers of two up to twice maximum value:|        add earlier count of power-value|record current value and return pairs modulo M','O(n log M) expected time; O(n) count space.'],
1716:['n','Compute savings after n days of the increasing weekly deposit schedule.','Deposits increase by one within a week. Each new Monday starts one greater than the preceding Monday, so week index plus weekday index determines every deposit.','total = 0|for zero-based day:|    week = floor(day/7); weekday = day modulo 7|    add week+weekday+1|return total','O(n) time; O(1) state.'],
1717:['s x y','Maximize score from deleting ab and ba substrings worth different amounts.','Remove the more valuable orientation first using a stack, then process the leftover string for the other orientation. Other characters divide independent regions.','choose higher-valued pair orientation|scan with stack, deleting that orientation|scan its leftovers for the other orientation|add the score of each removed pair|return total score','O(n) time and stack space.'],
1720:['encoded first','Recover an array from its first value and XORs of adjacent pairs.','XORing the previous original value with the encoded pair cancels the previous value, leaving the next original value.','output = [first]|for encoded value:|    next = last output XOR encoded value|    append next|return recovered array','O(n) time and output space.'],
1722:['source target allowedSwaps','Minimize Hamming distance using any number of allowed index swaps.','Swap edges connect freely permutable components. For each component, match target values against its source multiset; unmatched demand is unavoidable mismatch.','union allowed swap indices|count source values per component|for each target position:|    consume its value in that component or count a mismatch|return unavoidable mismatches','O((n+swaps) alpha(n)) expected time; O(n) state.'],
1725:['rectangles','Count rectangles capable of producing the greatest possible square.','The smaller side of a rectangle limits its square. Track the greatest such limit and reset or increment the number attaining it.','largest = count = 0|for rectangle:|    side = min(length,width)|    reset count for a new maximum, increment on equality|return count','O(n) time; O(1) state.'],
1726:['nums','Count ordered distinct-value tuples whose first two values have the same product as the last two.','Count unordered pairs by product. Each collision with an earlier pair yields eight ordered tuples: swap within either pair and swap the pairs.','product counts = {}; answer = 0|for each unordered index pair:|    product = nums[i]*nums[j]|    add 8*earlierPairs[product], then record this pair|return answer','O(n^2) expected time and pair-product space.'],
1727:['matrix','Find the largest all-one submatrix when columns may be rearranged.','At each row, compute consecutive-one heights. Sorting those heights shows which columns can form a rectangle of each width ending at this row.','heights = zero columns|for each row:|    extend one heights and reset zero heights|    sort a copy descending and maximize height[width-1]*width|return greatest area','O(rows*columns log columns) time; O(columns) state.'],
1730:['grid','Find the fewest grid steps from the starting cell to any food.','Breadth-first search expands reachable cells in distance order while avoiding obstacles. The first food removed from the queue is therefore nearest.','enqueue start with distance zero|while queue has cells:|    return distance if current cell is food|    enqueue unvisited non-obstacle neighbors at distance+1|return -1 if food is unreachable','O(rows*columns) time and visited/queue space.'],
1732:['gain','Find the highest altitude along a route starting at altitude zero.','Running sums recover the altitude after each segment. Include the initial zero because every later point could be lower.','altitude = highest = 0|for elevation change:|    add change to altitude|    maximize highest with altitude|return highest','O(n) time; O(1) state.'],
1734:['encoded','Recover an odd-length permutation from XORs of adjacent values.','XOR odd-indexed encoded entries to obtain every original value except the first. XOR with all integers one through n to recover the first, then decode sequentially.','all = XOR of integers 1..n|withoutFirst = XOR encoded indices 1,3,5,...|first = all XOR withoutFirst|recover each next value using previous XOR encoded|return permutation','O(n) time and output space.'],
1736:['time','Replace unknown digits to form the latest valid 24-hour time.','Choose hour tens with the fixed hour units in mind. Once that limit is respected, each remaining unknown can take its greatest independently valid digit.','maximize unknown hour tens subject to hour units|maximize hour units under the chosen tens|set unknown minute tens to five|set unknown minute units to nine|return completed time','O(1) time and fixed-size state.'],
1738:['matrix k','Find the kth largest XOR of an origin-anchored matrix rectangle.','Two-dimensional prefix XOR combines top and left rectangles and corrects their overlap. Collect each coordinate value, retaining duplicates when ranking.','allocate zero-bordered prefix XOR matrix|for each original cell:|    XOR current, top, left, and diagonal prefix|    collect resulting coordinate value|sort descending and return rank k','O(rc log(rc)) time; O(rc) space.'],
1742:['lowLimit highLimit','Find the greatest number of numbered balls assigned to one digit-sum box.','Each ball number maps to the sum of its decimal digits. Count those destinations and track the greatest occupancy.','box counts = {}; best = 0|for ball in inclusive interval:|    box = sum of decimal digits|    increment box and update best|return greatest count','O(range*digits) time; O(distinct digit sums) space.'],
1743:['adjacentPairs','Restore an array of distinct values from its unordered adjacent pairs.','The adjacency graph is a path. Start at an endpoint and repeatedly choose the neighbor other than the preceding value; either direction is valid.','build undirected neighbor lists|choose a degree-one endpoint|append its neighbor other than the previous value|repeat until all values are restored|return reconstructed array','O(n) time and graph/output space.'],
1744:['candiesCount queries','Determine whether a favorite candy type can be eaten on a chosen day under daily limits.','Prefix sums locate each type in the required eating order. By day d inclusive, total consumption ranges from d+1 to (d+1)*cap; test overlap with the favorite type positions.','prefix-sum candy counts|for type,day,cap:|    locate first and last candy positions of that type|    compare with possible cumulative consumption interval|return overlap decisions','O(types+queries) time; O(types) prefix space plus answers.'],
1746:['nums','Maximize a nonempty subarray sum after squaring exactly one element.','Keep best suffix sums before and after using the operation. At the current value either square now or extend a suffix that already contains the squared value.','plain = 0; changed = best = negative infinity|for value, preserve both previous suffix scores|plain = max(value,oldPlain+value)|changed = max(value^2,oldPlain+value^2,oldChanged+value)|maximize best changed score and return it','O(n) time; O(1) state.'],
1748:['nums','Sum values that occur exactly once.','Determine final frequencies before adding values. An early unique appearance may later become repeated and must not contribute.','count all values|for each distinct value:|    inspect its final frequency|    add it only when frequency equals one|return sum','O(n) expected time; O(n) count space.'],
1749:['nums','Find the greatest absolute sum of any subarray, allowing the empty subarray.','Any subarray sum is a difference of two prefix sums. The largest absolute difference is the maximum prefix minus the minimum prefix, including the initial zero.','prefix = minimum = maximum = 0|for value:|    advance prefix sum|    update both prefix extremes|return maximum-minimum','O(n) time; O(1) state.'],
1750:['s','Minimize remaining string length by repeatedly deleting matching-character prefix and suffix runs.','When the end characters match, remove their complete runs from both ends. Stop when the ends disagree or fewer than two characters remain.','left = 0; right = length-1|while left < right and end characters match:|    remember matching character|    skip its runs on both ends without crossing twice|return remaining interval length','O(n) time; O(1) state.'],
1752:['nums','Decide whether an array is a rotation of a nondecreasing array.','Include the last-to-first comparison. A valid rotation has at most one strict circular decrease; duplicates introduce no extra decrease.','drops = 0|compare each value with circular successor|count strict decreases|reject once drops exceeds one|return true otherwise','O(n) time; O(1) state.'],
1753:['a b c','Maximize moves that remove one stone from each of two different piles.','Every move consumes two stones, but a dominant pile also needs partners from the other piles. The smaller of these two bounds is achievable.','sum all piles|find greatest pile|totalBound = floor(sum/2)|partnerBound = sum-greatest|return min(totalBound,partnerBound)','O(1) time and state.'],
1754:['word1 word2','Build the lexicographically greatest merge while preserving each word internal order.','At each step compare the remaining suffixes. Choosing from the greater suffix resolves equal-leading-character ties using their later differing characters.','output = empty|while either suffix remains:|    compare both complete remaining suffixes|    append the first character of the greater suffix|return merged output','O((n+m)^2) conservative suffix comparison/copy time; O(n+m) space.'],
1756:['n fetches','Process queue fetches that move the requested current-position item to the back.','Positions are one-based and change after each fetch. Remove the indexed value, append it, and record which value was fetched.','queue = [1..n]|for one-based position k:|    remove queue[k-1]|    append that value to queue and output|return fetched values','O(n*queries) array-splice time; O(n+queries) space.'],
1758:['s','Flip the fewest bits to make a binary string alternate.','Only two alternating targets exist, starting with zero or one. Count mismatches to each target in one scan.','zeroStart = oneStart = 0|for index,bit:|    compare against index parity and its complement|    increment the respective mismatch counts|return smaller mismatch count','O(n) time; O(1) state.'],
1759:['s','Count nonempty substrings made entirely of one repeated character.','A same-character suffix of length r contributes r substrings ending at this position. Reset the length when the character changes and accumulate modulo the required prime.','run = total = 0|for character:|    extend run if equal to previous, otherwise reset to one|    add run modulo 1000000007|return total','O(n) time; O(1) state.'],
1760:['nums maxOperations','Minimize the greatest bag size after a limited number of bag splits.','For a candidate maximum, each original bag needs ceil(size/maximum)-1 splits. Required operations decrease as the candidate grows, enabling binary search.','low = 1; high = greatest bag|while low < high:|    count splits needed at midpoint limit|    lower high if feasible, otherwise raise low|return smallest feasible limit','O(n log M) time; O(1) state.'],
};

export function validateAdvance(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const rows=(a,width,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(p=>vector(p,width,width,low,high));
 const text=(s,regex=/^[a-z]+$/,max=160)=>typeof s==='string'&&s.length>=1&&s.length<=max&&regex.test(s);
 for(const key of ['nums','students','sandwiches','apples','days','deliciousness','encoded','source','target','gain','candiesCount','fetches'])if(key in input)check(vector(input[key]),`${key}: use 1-100 bounded integers.`);
 if(id===1696)check(integer(input.k,1,input.nums.length),'Use jump length from one through array length.');
 if(id===1697)check(integer(input.n,2,40)&&rows(input.edgeList,3,0,120,0)&&input.edgeList.every(([a,b,w])=>a<input.n&&b<input.n&&a!==b&&w>0)&&rows(input.queries,3,1,50,0)&&input.queries.every(([a,b,limit])=>a<input.n&&b<input.n&&limit>0),'Use bounded weighted edges and [vertex,vertex,positive limit] queries.');
 if(id===1698)check(text(input.s,/^[a-z]+$/,35),'Use 1-35 lowercase characters for explicit substring enumeration.');
 if(id===1700)check(input.students.length===input.sandwiches.length&&[...input.students,...input.sandwiches].every(v=>v===0||v===1),'Use equally sized binary preference and sandwich arrays.');
 if(id===1701)check(rows(input.customers,2,1,60,1)&&input.customers.every((v,i,a)=>!i||v[0]>=a[i-1][0]),'Use [arrival,cooking time] positive pairs sorted by arrival.');
 if(id===1702)check(text(input.binary,/^[01]+$/),'Use a nonempty binary string.');
 if(id===1704)check(text(input.s,/^[A-Za-z]+$/)&&input.s.length%2===0,'Use a nonempty even-length alphabetic string.');
 if(id===1705)check(input.apples.length===input.days.length&&input.apples.length<=60&&input.apples.every((v,i)=>integer(v,0,100)&&integer(input.days[i],0,100)&&((v===0)===(input.days[i]===0))),'Use matching apple counts and shelf lives from 0-100; zero production must have zero shelf life and vice versa.');
 if([1706,1727,1738].includes(id)){const g=input[id===1706?'grid':'matrix'];check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vector(row,1,8)&&row.length===g[0].length),'Use a rectangular matrix with 1-8 rows and columns.');check(g.flat().every(v=>id===1706?v===1||v===-1:id===1727?v===0||v===1:v>=0),'Use slopes -1/1, binary area cells, or nonnegative XOR values as appropriate.');if(id===1738)check(integer(input.k,1,g.length*g[0].length),'Use a rank within the number of coordinate values.');}
 if(id===1708)check(new Set(input.nums).size===input.nums.length&&integer(input.k,1,input.nums.length),'Use distinct values and valid subarray length.');
 if(id===1710)check(rows(input.boxTypes,2,1,60,1)&&integer(input.truckSize,1,10000),'Use positive [box count,units per box] pairs and truck capacity.');
 if(id===1711)check(input.deliciousness.every(v=>v>=0),'Use nonnegative deliciousness values.');
 if(id===1716)check(integer(input.n,1,180),'Use 1-180 deposit days.');
 if(id===1717)check(text(input.s)&&integer(input.x,1,10000)&&integer(input.y,1,10000),'Use lowercase text and positive scores for ab and ba.');
 if(id===1720)check(input.encoded.every(v=>v>=0)&&integer(input.first),'Use nonnegative encodings and first value.');
 if(id===1722)check(input.source.length===input.target.length&&rows(input.allowedSwaps,2,0,100,0,input.source.length-1)&&input.allowedSwaps.every(([a,b])=>a!==b),'Use equal-size arrays and valid distinct index pairs.');
 if(id===1725)check(rows(input.rectangles,2,1,60,1),'Use positive rectangle dimensions.');
 if(id===1726)check(input.nums.length>=4&&input.nums.length<=30&&input.nums.every(v=>v>0)&&new Set(input.nums).size===input.nums.length,'Use 4-30 distinct positive values.');
 if(id===1730){const g=input.grid;check(Array.isArray(g)&&g.length>=1&&g.length<=10&&g.every(row=>Array.isArray(row)&&row.length>=1&&row.length<=10&&row.length===g[0].length&&row.every(c=>['*','#','O','X'].includes(c))),'Use a rectangular 1-10 grid of *, #, O, and X cells.');check(g.flat().filter(c=>c==='*').length===1&&g.flat().includes('#'),'Use exactly one starting cell * and at least one food cell #.');}
 if(id===1734){check(input.encoded.length%2===0&&input.encoded.every(v=>v>=0),'Use adjacent XORs of an odd-length permutation.');const n=input.encoded.length+1;let first=0;for(let v=1;v<=n;v++)first^=v;for(let i=1;i<input.encoded.length;i+=2)first^=input.encoded[i];const recovered=[first];for(const v of input.encoded)recovered.push(recovered.at(-1)^v);check(new Set(recovered).size===n&&recovered.every(v=>integer(v,1,n)),'Encoded values must represent a permutation of one through n.');}
 if(id===1736){check(typeof input.time==='string'&&/^[0-2?][0-9?]:[0-5?][0-9?]$/.test(input.time),'Use a partially hidden HH:MM time.');check(!(input.time[0]==='2'&&input.time[1]!=='?'&&input.time[1]>'3'),'Fixed hour digits must permit a valid 24-hour time.');}
 if(id===1742)check(integer(input.lowLimit,1,100000)&&integer(input.highLimit,input.lowLimit,100000)&&input.highLimit-input.lowLimit<=200,'Use a positive inclusive range of at most 201 ball numbers.');
 if(id===1743){check(rows(input.adjacentPairs,2,1,60)&&input.adjacentPairs.every(([a,b])=>a!==b),'Use bounded adjacent-value pairs without self-edges.');const graph=new Map(),edges=new Set();for(const[a,b]of input.adjacentPairs){const key=[Math.min(a,b),Math.max(a,b)].join(',');check(!edges.has(key),'Do not repeat an adjacent pair.');edges.add(key);for(const[u,v]of [[a,b],[b,a]]){if(!graph.has(u))graph.set(u,[]);graph.get(u).push(v);}}check([...graph.values()].filter(a=>a.length===1).length===2&&[...graph.values()].every(a=>a.length<=2),'Pairs must describe one simple path.');const seen=new Set(),queue=[graph.keys().next().value];for(let i=0;i<queue.length;i++){const v=queue[i];if(seen.has(v))continue;seen.add(v);queue.push(...graph.get(v).filter(u=>!seen.has(u)));}check(seen.size===graph.size,'All pairs must belong to one connected path.');}
 if(id===1744)check(input.candiesCount.every(v=>v>0)&&rows(input.queries,3,1,50,0,100000)&&input.queries.every(([type,day,cap])=>type<input.candiesCount.length&&day>=0&&cap>=1),'Use positive candy counts and [valid type,nonnegative day,positive cap] queries.');
 if(id===1748)check(input.nums.every(v=>v>=1),'Use positive values.');
 if(id===1750)check(text(input.s,/^[abc]+$/),'Use a nonempty string containing a, b, and c only.');
 if(id===1752)check(input.nums.every(v=>v>=1),'Use positive array values.');
 if(id===1753)check([input.a,input.b,input.c].every(v=>integer(v,1,100000)),'Use three positive pile sizes.');
 if(id===1754)check(text(input.word1)&&text(input.word2),'Use nonempty lowercase words.');
 if(id===1756)check(integer(input.n,1,100)&&input.fetches.every(v=>integer(v,1,input.n)),'Use queue size 1-100 and one-based fetch positions within it.');
 if(id===1758)check(text(input.s,/^[01]+$/),'Use a nonempty binary string.');
 if(id===1759)check(text(input.s),'Use a nonempty lowercase string.');
 if(id===1760)check(input.nums.every(v=>v>=1)&&integer(input.maxOperations,0,1000000),'Use positive bag sizes and a nonnegative split budget.');
 return input;
}
