export const forwardSpecs={
1762:['heights','Find building indices with an unobstructed view of the ocean to the right.','Scan from the ocean side and retain the tallest building already seen. Equality blocks the view just like a taller building.','tallest = 0; visible = []|scan buildings right to left|record index only if height > tallest|update tallest|reverse recorded indices and return','O(n) time; O(n) output space.'],
1763:['s','Find the earliest longest substring containing both cases of every letter it uses.','Expand each start while tracking present characters. A candidate is nice only if every present letter has its lowercase and uppercase counterpart; replace the best only on strict length improvement.','for each start:|    expand end and collect present characters|    check both cases for every present letter|    retain only a strictly longer nice substring|return best substring or empty string','O(n^2*alphabet) time; O(alphabet) state plus output.'],
1764:['groups nums','Match all groups as ordered, nonoverlapping contiguous blocks inside nums.','Find each group earliest possible occurrence after the preceding match. Any later occurrence would leave no more room for remaining groups.','cursor = 0|for each group in order:|    advance cursor until the full group matches|    continue after its last position, or fail if absent|return true when all groups match','O(n*maximum group length) comparison time; O(1) state.'],
1765:['isWater','Assign maximum possible terrain heights with water at zero and neighboring differences at most one.','Every water cell constrains nearby heights. Multi-source breadth-first search computes distance to the nearest water, which is the greatest feasible height at each location.','set all water heights to zero and enqueue them|while queue has cells:|    visit each unassigned orthogonal neighbor|    assign parent height+1 and enqueue neighbor|return height matrix','O(rows*columns) time and queue/matrix space.'],
1768:['word1 word2','Merge two strings by alternating their characters, starting with the first string.','Advance a common character index through both words. Append from each when that index exists, naturally preserving any longer suffix.','output = empty|for index through the greater length:|    append first-word character if present|    append second-word character if present|return merged string','O(n+m) output construction time and space.'],
1769:['boxes','Compute moves needed to gather all balls into each box independently.','A left-to-right scan accumulates movement cost from balls on the left; a mirrored scan adds costs from the right. Each step increases cost by the number of balls passed.','answers = zeros|scan left to right with ball count and movement cost|add cost, then update count and next cost|repeat right to left and add right-side costs|return answers','O(n) time; O(n) output space.'],
1770:['nums multipliers','Maximize score by repeatedly multiplying and removing either array endpoint.','The operation index and number of left selections determine both remaining endpoints. Fill future scores backward so each left/right choice can reuse its optimal continuation.','dp[operationsDone][leftTaken] = future score|iterate operations backward|derive right index from operation count and left count|compare left product+next score against right product+next score|return dp[0][0]','O(m^2) time and table space for m multipliers.'],
1773:['items ruleKey ruleValue','Count items whose selected type, color, or name matches the requested rule value.','Map the rule key to one column and compare that field in each item. Matches in other columns do not satisfy this rule.','map rule key to its field index|for each item:|    read only the selected field|    increment count on equality with rule value|return count','O(items) time; O(1) state.'],
1774:['baseCosts toppingCosts target','Choose one dessert base and up to two of each topping closest to a target cost.','Build all reachable topping totals using zero, one, or two copies of each topping. Combine them with every base and minimize distance, breaking ties toward lower cost.','reachable topping sums = {0}|for each topping, add zero, one, or two copies to prior sums|combine every base with reachable topping sums|prefer smaller absolute target gap, then smaller total|return best dessert cost','O(3^t * (t+b)) conservative time; O(3^t) reachable-sum space.'],
1775:['nums1 nums2','Make two dice-valued arrays have equal sums using as few value changes as possible.','Each smaller-side value can increase to six, and each larger-side value can decrease to one. Use those independent gains in decreasing order to close the sum gap fastest.','order arrays by their sums|collect increase gains 6-value and decrease gains value-1|sort gains descending|apply largest gains until gap closes or gains run out|return operations or -1 if impossible','O((n+m) log(n+m)) time; O(n+m) state.'],
1779:['x y points','Find the nearest point sharing x or y with the reference point, breaking ties by input index.','Filter for a shared coordinate, then minimize Manhattan distance. Keep the earlier candidate on equal distance.','bestDistance = infinity; bestIndex = -1|for each point:|    require matching x or matching y|    replace best only for a strictly smaller distance|return bestIndex','O(n) time; O(1) state.'],
1780:['n','Decide whether n is a sum of distinct powers of three.','The ternary expansion gives the coefficient of every power. Coefficients zero and one are allowed; a digit two would require using that power twice.','while n > 0:|    digit = n modulo 3|    reject if digit is two|    divide n by three and discard remainder|return true','O(log n) time; O(1) state.'],
1781:['s','Sum the difference between highest and lowest positive character frequencies over all substrings.','For each starting position, extend the substring while updating letter counts. Ignore absent letters when finding the minimum positive count.','for each substring start:|    reset character counts|    extend the end and update its letter|    add maximum count minus minimum positive count|return total beauty','O(n^2*alphabet) time; O(alphabet) state.'],
1784:['s','Check whether a binary string has at most one contiguous segment of ones.','Count positions where a one starts after zero or at the beginning. A second such start means separated one segments exist.','segments = 0|for each bit:|    count one preceded by zero or string start|    reject if segments exceeds one|return true','O(n) time; O(1) state.'],
1785:['nums limit goal','Find the fewest bounded-magnitude values to append so the sum equals goal.','Compute the signed sum gap. Each appended value closes at most limit of its magnitude, and a smaller final remainder is permitted.','current = sum(nums)|gap = abs(goal-current)|divide gap by limit|round up to account for a partial final value|return required additions','O(n) time; O(1) state.'],
1790:['s1 s2','Decide whether at most one character swap in a string can make the two strings equal.','Zero mismatches already succeeds. Otherwise exactly two positions must differ, and swapping their characters must repair both.','collect mismatch positions|reject once more than two appear|accept if no mismatches remain|for exactly two, require cross-matching characters|return whether one swap repairs them','O(n) time; O(1) bounded mismatch state.'],
1791:['edges','Find the center of a valid undirected star graph.','Every edge contains the center. Two different star edges share exactly that endpoint, so the first two determine the answer.','read first two edges|compare first edge endpoints with second edge|choose the shared endpoint|identify it as the star center|return center','O(1) algorithm time and state, excluding input validation.'],
1792:['classes extraStudents','Assign guaranteed-passing students to maximize the average class pass ratio.','The marginal gain from one extra passing student shrinks after assignment. Repeatedly choose the class with the greatest current gain.','repeat for each extra student:|    compute (pass+1)/(total+1)-pass/total per class|    select greatest marginal gain|    increment its pass and total|return mean of final class ratios','O(classes*extraStudents) direct selection time; O(classes) state.'],
1793:['nums k','Maximize minimum-value times length over subarrays containing index k.','Start at the required index and expand toward the larger available neighbor. This delays lowering the current minimum while exploring increasingly wide eligible intervals.','left = right = k; minimum = nums[k]|while another neighbor exists:|    expand toward the greater available neighbor|    lower minimum and maximize minimum*width|return greatest score','O(n) time; O(1) state.'],
1796:['s','Find the second greatest distinct decimal digit present in a mixed string.','Track two different digit values in descending order. Ignore letters and duplicate appearances of the maximum.','largest = second = -1|for each digit character:|    promote old maximum when a greater digit appears|    otherwise update second only with a distinct smaller digit|return second','O(n) time; O(1) state.'],
1797:['timeToLive operations','Simulate token generation, renewal, and counting with exact expiration times.','Before each operation discard tokens whose expiry is at or before the current time. Renew only tokens still alive and return counts for count operations.','for each increasing-time operation:|    remove tokens with expiry <= time|    generate sets expiry; renew updates only a live token|    count appends number of live tokens|return count-query results','O(operations*tokens) direct cleanup time; O(tokens) state plus results.'],
1798:['coins','Count consecutive constructible sums beginning at zero when each coin can be used once.','If all sums through reach are available, a coin at most reach+1 extends coverage through reach+coin. A larger coin leaves the first gap permanently uncovered.','sort coins; reach = 0|for coin:|    stop if coin > reach+1|    otherwise extend reach by coin|return reach+1 including zero','O(n log n) time; O(n) sorted-copy space.'],
1799:['nums','Pair all values to maximize the sum of operation-index times pair GCD.','A used-value mask determines how many operations have occurred. Try every pair as the latest operation and combine its weighted GCD with the optimal smaller mask.','precompute every pair GCD|visit masks with even numbers of used values|operation = usedCount/2|try each selected pair as last and maximize previousMaskScore+operation*gcd|return score for full mask','O(2^n*n^2) time; O(2^n+n^2) state.'],
1800:['nums','Find the greatest sum of a strictly ascending contiguous subarray.','A greater current value extends the previous ascending suffix. Equal or smaller values break that run and start a new one.','run = best = 0|for value:|    extend run only on a strict increase|    otherwise reset run to current value; update best|return best','O(n) time; O(1) state.'],
1802:['n index maxSum','Maximize one array position under positive-value, adjacent-difference, and total-sum limits.','For a candidate peak, the cheapest sides descend by one down to a floor of one. Compute their arithmetic-series sums and binary search the greatest affordable peak.','search peak from one through maxSum-n+1|compute minimum left and right sums for candidate peak|add peak to get required total|raise lower bound when affordable, otherwise lower upper bound|return greatest feasible peak','O(log maxSum) time; O(1) state.'],
};

export function validateForward(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const text=(s,regex=/^[a-z]+$/,max=160)=>typeof s==='string'&&s.length>=1&&s.length<=max&&regex.test(s);
 for(const key of ['heights','nums','nums1','nums2','multipliers','baseCosts','toppingCosts','coins'])if(key in input)check(vector(input[key]),`${key}: use 1-100 bounded integers.`);
 if(id===1762)check(input.heights.every(v=>v>0),'Use positive building heights.');
 if(id===1763)check(text(input.s,/^[A-Za-z]+$/,24),'Use 1-24 alphabetic characters for detailed substring playback.');
 if(id===1764)check(Array.isArray(input.groups)&&input.groups.length>=1&&input.groups.length<=20&&input.groups.every(g=>vector(g,1,20)),'Use 1-20 nonempty integer groups.');
 if(id===1765){const g=input.isWater;check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vector(row,1,8,0,1)&&row.length===g[0].length)&&g.flat().includes(1),'Use a rectangular binary grid up to 8 by 8 with at least one water cell.');}
 if(id===1768)check(text(input.word1)&&text(input.word2),'Use nonempty lowercase words.');
 if(id===1769)check(text(input.boxes,/^[01]+$/),'Use a binary string, with one indicating a ball.');
 if(id===1770)check(input.multipliers.length<=input.nums.length&&input.multipliers.length<=12,'Use at most twelve multipliers, no more than the number of values.');
 if(id===1773)check(Array.isArray(input.items)&&input.items.length>=1&&input.items.length<=60&&input.items.every(row=>Array.isArray(row)&&row.length===3&&row.every(v=>text(v,/^[a-z]+$/,30)))&&['type','color','name'].includes(input.ruleKey)&&text(input.ruleValue),'Use [type,color,name] lowercase items and a valid rule key and value.');
 if(id===1774)check(input.baseCosts.length<=20&&input.toppingCosts.length<=8&&[...input.baseCosts,...input.toppingCosts].every(v=>v>0)&&integer(input.target,1,100000),'Use positive base costs, at most eight positive topping costs, and a positive target.');
 if(id===1775)check([...input.nums1,...input.nums2].every(v=>v>=1&&v<=6),'Both arrays must contain dice values one through six.');
 if(id===1779)check(integer(input.x,-10000)&&integer(input.y,-10000)&&Array.isArray(input.points)&&input.points.length>=1&&input.points.length<=60&&input.points.every(p=>vector(p,2,2)),'Use a bounded reference coordinate and 1-60 coordinate pairs.');
 if(id===1780)check(integer(input.n,1,100000000),'Use a positive integer at most one hundred million.');
 if(id===1781)check(text(input.s,/^[a-z]+$/,30),'Use 1-30 lowercase characters for full substring counting.');
 if(id===1784)check(text(input.s,/^1[01]*$/),'Use a positive binary string without leading zeros.');
 if(id===1785)check(integer(input.limit,1,10000)&&input.nums.every(v=>Math.abs(v)<=input.limit)&&integer(input.goal,-100000000,100000000),'Use positive limit, input magnitudes within it, and a bounded integer goal.');
 if(id===1790)check(text(input.s1)&&text(input.s2)&&input.s1.length===input.s2.length,'Use equal-length nonempty lowercase strings.');
 if(id===1791){check(Array.isArray(input.edges)&&input.edges.length>=2&&input.edges.length<=60&&input.edges.every(e=>vector(e,2,2,1,input.edges.length+1)&&e[0]!==e[1]),'Use at least two valid one-based star edges.');const degree=new Map(),unique=new Set();for(const[a,b]of input.edges){const key=[Math.min(a,b),Math.max(a,b)].join(',');check(!unique.has(key),'Star edges must not repeat.');unique.add(key);degree.set(a,(degree.get(a)||0)+1);degree.set(b,(degree.get(b)||0)+1);}check(degree.size===input.edges.length+1&&[...degree.values()].filter(v=>v===input.edges.length).length===1&&[...degree.values()].filter(v=>v===1).length===input.edges.length,'Edges must form one star.');}
 if(id===1792)check(Array.isArray(input.classes)&&input.classes.length>=1&&input.classes.length<=30&&input.classes.every(c=>vector(c,2,2,1)&&c[0]<=c[1])&&integer(input.extraStudents,1,100),'Use valid positive [passing,total] pairs and 1-100 extra students.');
 if(id===1793)check(input.nums.every(v=>v>0)&&integer(input.k,0,input.nums.length-1),'Use positive values and an in-range required index.');
 if(id===1796)check(text(input.s,/^[a-z0-9]+$/),'Use a nonempty lowercase alphanumeric string.');
 if(id===1797){check(integer(input.timeToLive,1,10000)&&Array.isArray(input.operations)&&input.operations.length>=1&&input.operations.length<=80,'Use positive token lifetime and 1-80 operations.');let previous=0;const generated=new Set();for(const op of input.operations){check(Array.isArray(op)&&['generate','renew','count'].includes(op[0]),'Use generate, renew, or count operations.');const count=op[0]==='count';check(op.length===(count?2:3)&&(count||text(op[1],/^[a-z0-9]+$/,30)),'Use [count,time] or [generate/renew,token,time].');const time=op[count?1:2];check(integer(time,previous+1,1000000),'Operation times must be strictly increasing positive integers.');previous=time;if(op[0]==='generate'){check(!generated.has(op[1]),'Each generated token ID must be unique.');generated.add(op[1]);}}}
 if(id===1798)check(input.coins.every(v=>v>0),'Use positive coin values.');
 if(id===1799)check(input.nums.length>=2&&input.nums.length<=10&&input.nums.length%2===0&&input.nums.every(v=>v>0),'Use 2-10 positive values, with an even length for pairing.');
 if(id===1800)check(input.nums.every(v=>v>0),'Use positive array values.');
 if(id===1802)check(integer(input.n,1,1000000)&&integer(input.index,0,input.n-1)&&integer(input.maxSum,input.n,1000000000),'Use positive array length, a valid index, and a sum budget at least the length.');
 return input;
}
