export const progressSpecs={
1615:['n roads','Find the greatest number of distinct roads incident to a pair of cities.','City degrees include every attached road. A direct road between the chosen cities appears in both degrees, so subtract it once.','count degrees and record connections|for each distinct city pair:|    rank = degree[a]+degree[b]-sharedRoad|    retain the greatest rank|return maximum rank','O(n^2+roads) time; O(n+roads) space.'],
1616:['a b','Decide whether a prefix from one string and a suffix from the other can form a palindrome.','Match outer characters across the two strings until they disagree. At that point the untouched center must be a palindrome entirely within either original string. Try both prefix directions.','try both prefix/suffix orders|move inward while cross-string endpoints match|on first mismatch, inspect each possible same-string center|accept if either center is palindromic|return whether any order succeeds','O(n) time; O(1) algorithm state.'],
1619:['arr','Average the array after removing its smallest and largest five percent.','Sort so both trimmed tails occupy known positions. Average exactly the remaining ninety percent, retaining repeated values by their positions.','sort values|trim = length/20|sum entries from trim through length-trim-1|divide by length-2*trim|return trimmed mean','O(n log n) time; O(n) sorted-copy space.'],
1624:['s','Find the longest substring strictly between equal endpoint characters.','Remember the earliest index for each character. Every later copy can use that farthest-left endpoint; exclude both endpoints from the measured length.','first positions = {}; best = -1|for index,character:|    save index only on its first appearance|    otherwise maximize index-first-1|return best','O(n) time; O(alphabet) space.'],
1626:['scores ages','Build a maximum-score team with no younger player outscoring an older teammate.','Sort by increasing age, breaking ties by increasing score. A maximum-weight nondecreasing score subsequence then includes only compatible players while allowing all same-age players.','sort players by age then score|dp[i] = score[i]|for earlier player j with score[j] <= score[i]:|    maximize dp[i] with dp[j]+score[i]|return greatest ending score','O(n^2) time; O(n) state.'],
1629:['releaseTimes keysPressed','Find the key with the longest individual press, resolving ties toward the greatest character.','Each duration is the difference between consecutive release times, with the first press starting at zero. Compare individual presses, not accumulated time per key.','previous release = 0|for each release and key:|    duration = release-previous|    update longest and break ties by greater key|return chosen key','O(n) time; O(1) state.'],
1630:['nums l r','Determine which queried subarrays can be rearranged into arithmetic progressions.','Each query is independent. Sort its values and compare every adjacent gap with the first gap, allowing zero differences.','for query endpoints:|    copy and sort selected subarray|    measure its first gap|    require all later gaps to match|return one boolean per query','O(q*n log n) worst-case time; O(n) temporary space plus answers.'],
1636:['nums','Sort values by increasing frequency and by decreasing value when frequencies tie.','Count occurrences before sorting. The comparison key is the pair of frequency ascending and numeric value descending.','count each value|sort a copy using frequency first|break equal frequency by larger value first|retain repeated entries|return sorted array','O(n log n) time; O(n) space.'],
1637:['points','Find the widest empty vertical strip between points.','Only horizontal coordinates affect vertical-strip width. Sort those coordinates; any empty strip is bounded by neighboring distinct coordinates in this order.','extract and sort x coordinates|for each neighboring pair:|    compute right-left|    retain greatest gap|return widest gap','O(n log n) time; O(n) space.'],
1638:['s t','Count pairs of equal-length substrings that differ at exactly one character.','Choose both starting positions and extend them together. After the first mismatch every extension counts until the second mismatch makes all longer extensions invalid.','for each pair of start positions:|    extend aligned characters|    track mismatch count|    count lengths with one mismatch; stop at two|return total pairs','O(st*min(s,t)) direct enumeration time; O(1) algorithm state.'],
1640:['arr pieces','Decide whether whole pieces can be reordered to form the target array.','Values are distinct, so the next target value uniquely identifies its piece. Match that whole piece without changing its internal order before moving to the next one.','map first value to its piece|read next uncovered target value|find its piece or reject|match every piece value in order or reject|return true once target is covered','O(n) expected time; O(number of pieces) map space.'],
1641:['n','Count nondecreasing strings of length n made from the five vowels.','For each ending vowel, sum shorter strings ending in any vowel no greater than it. Updating left to right computes these prefix sums in place.','one string per vowel at length one|for each greater length:|    scan vowels left to right|    add previous vowel cumulative count|return sum of five ending counts','O(n) time; O(1) five-vowel state.'],
1642:['heights bricks ladders','Reach the farthest building using limited bricks and ladders.','Among positive climbs seen so far, ladders should cover the largest. Keep candidate ladder climbs sorted and pay bricks for the smallest whenever their count exceeds the ladder supply.','scan building differences|put positive climb among ladder candidates|if too many candidates, pay bricks for the smallest|stop before a climb when bricks become negative|return last reached index','O(n^2 log n) direct sorted-list implementation; O(n) state.'],
1646:['n','Find the maximum value in the specified recursively generated array through index n.','Even indices copy their half-index; odd indices add the two surrounding half-indices. Increasing index order always computes dependencies first.','initialize zero and, if needed, one|for index two through n:|    apply even-copy or odd-sum rule|    update greatest value|return maximum','O(n) time and array space.'],
1647:['s','Delete the fewest characters so all remaining positive character frequencies differ.','Process frequencies from largest to smallest. Keep each as high as possible below the previous kept frequency; zero means a character disappears and can repeat freely.','sort frequencies descending|allowed = infinity; removed = 0|keep min(frequency,allowed)|add discarded count and lower allowed to max(0,kept-1)|return removals','O(n+u log u) time; O(u) frequency state.'],
1652:['code k','Replace each circular-array value with the sum of its requested neighboring values.','Read only from the unchanged input. Positive k sums next entries, negative k previous entries, and zero gives zero at every position.','for each index:|    total = 0|    walk abs(k) neighbors in the sign of k with wraparound|    append their sum|return replacement array','O(n*abs(k)) direct simulation time; O(n) output space.'],
1653:['s','Delete the fewest characters so every a appears before every b.','Track earlier b characters and the cheapest balanced prefix. A new a can be deleted, or all earlier b characters can be deleted instead.','bCount = deletions = 0|for character:|    count b characters|    at a, deletions = min(deletions+1,bCount)|return deletions','O(n) time; O(1) state.'],
1656:['n operations','Emit consecutive ordered-stream values as out-of-order insertions fill gaps.','Store values by their one-based IDs and remember the first unread position. An insertion may release nothing or an entire waiting chain.','allocate n empty slots and pointer zero|for insert(id,value):|    fill the indexed slot|    emit and advance while pointer slot is filled|return chunks in insertion order','O(n+operations) time; O(n) storage plus output.'],
1657:['word1 word2','Decide whether position swaps and existing-character identity swaps can transform one word into the other.','Allowed operations preserve the set of characters and the multiset of their counts. Both conditions, together with equal length, characterize transformability.','count both words|compare sets of present characters|sort their frequency lists|require those lists and word lengths to match|return whether both invariants agree','O(n+u log u) time; O(u) state.'],
1658:['nums x','Remove the fewest values from the array ends whose sum is x.','The values left behind form one contiguous middle. Since inputs are positive, a sliding window finds the longest middle with sum total minus x.','target = total-x|handle negative or zero target|slide a positive-value window, shrinking excess sum|retain longest window equal to target|return length-longest, or -1 if absent','O(n) time; O(1) state.'],
1662:['word1 word2','Decide whether two arrays of string chunks represent the same complete string.','Chunk boundaries disappear when the strings are concatenated. Compare the resulting character sequences, including any length difference.','join each list of chunks|scan positions across both joined strings|compare characters, treating a missing position as end|reject at first mismatch|return true after all positions match','O(total characters) time and concatenated-string space.'],
1663:['n k','Construct the lexicographically smallest length-n lowercase string whose character values sum to k.','Start every position at a, the minimum. Spend remaining value at the rightmost positions first so earlier characters stay as small as possible.','values = n ones; extra = k-n|scan positions right to left:|    add min(25,extra) to current position|    subtract spent extra|convert values to letters and return string','O(n) time and output space.'],
1664:['nums','Count deletions that leave equal sums at even and odd indices.','Removing an entry shifts every later entry left, swapping its parity. Combine unchanged left-side sums with opposite-parity right-side sums.','compute total even and odd sums|for removal index:|    subtract current value from right sums|    compare leftEven+rightOdd with leftOdd+rightEven|move current value to left sums and return match count','O(n) time; O(1) state.'],
1668:['sequence word','Find the largest consecutive repetition count of word present inside sequence.','Build candidates word, word+word, and so on. Once a repeated candidate is absent, no longer repetition can appear because it contains the absent candidate.','candidate = word; count = 0|while candidate can fit:|    search for candidate in sequence|    stop if absent; otherwise increment count and append word|return count','O(n^3) conservative substring-search bound; O(n) candidate space.'],
1673:['nums k','Choose the lexicographically smallest subsequence of exactly k values.','Maintain increasing choices when possible. Remove a larger previous choice only if enough remaining positions can still complete k selections.','stack = []|for each value:|    pop greater last values while completion remains possible|    push current value if fewer than k selected|return stack','O(n) amortized time; O(k) output state.'],
1678:['command','Interpret the command tokens G, (), and (al).','Consume one complete token at a time and append its defined expansion. Token lengths determine where the next reading position begins.','output = empty|read next complete token|append G for G, o for (), or al for (al)|advance by token length|return output','O(n) time and output space.'],
1679:['nums k','Maximize disjoint pairs whose values sum to k.','Keep counts of unmatched values. Matching an available complement immediately consumes two positions without reducing the number of future possible pairs.','unmatched counts = {}; pairs = 0|for value:|    seek k-value among unmatched counts|    consume it and count a pair, or store current value|return pairs','O(n) expected time; O(n) space.'],
1680:['n','Concatenate binary representations from one through n and return the result modulo 1000000007.','Appending a binary word shifts the existing number by that word length and adds its value. Modular reduction preserves the requested remainder while keeping arithmetic bounded.','answer = 0|for value one through n:|    width = binary digit length|    answer = (answer*2^width+value) modulo M|return answer','O(n log n) digit-generation time; O(log n) temporary space.'],
1684:['allowed words','Count words that use only allowed characters.','A set gives membership checks for each letter. Repeated letters are fine; even one outside the set invalidates the whole word.','allowedSet = set of allowed letters|for word:|    inspect every character membership|    count word only if all belong|return count','O(total input characters) expected time; O(alphabet) state.'],
1685:['nums','Compute the sum of absolute differences from every value to all other sorted-array values.','Sorted order lets left differences use value minus earlier entries and right differences use later entries minus value. Prefix totals evaluate both sides without rescanning.','total = sum(nums); prefix = 0|for index,value:|    left = value*index-prefix|    right = total-prefix-value-value*(length-index-1)|append left+right, advance prefix, return array','O(n) time; O(n) output space.'],
1686:['aliceValues bobValues','Determine the winner when two players optimally take stones with different personal values.','Choosing a stone gains your value and denies the opponent theirs. Order stones by the sum of both values, then alternate choices and compare each player actual total.','sort stone indices by combined value descending|alternate indices between Alice and Bob|add only the picking player personal value|compare final totals|return 1 for Alice, -1 for Bob, or 0 for tie','O(n log n) time; O(n) order space.'],
1688:['n','Count the matches needed to reduce a tournament to one winner.','Each round pairs as many teams as possible; an odd leftover advances without playing. Track eliminated teams through successive rounds.','matches = 0|while teams > 1:|    played = floor(teams/2); bye = teams modulo 2|    add played and set teams = played+bye|return matches','O(log n) round simulation time; O(1) state.'],
1689:['n','Find the minimum number of decimal numbers with only zero and one digits that sum to n.','Each addend can contribute at most one at any decimal position. The maximum digit supplies a lower bound and that many nested digit layers attain it.','maximum = 0|for decimal digit:|    compare digit with current maximum|    retain larger layer requirement|return maximum digit','O(digits) time; O(1) state.'],
1690:['stones','Find the optimal score difference in a game where removing an endpoint scores the remaining interval sum.','For each interval, compare the score earned now minus the opponent best difference on the smaller interval. Prefix sums provide both remaining sums quickly.','compute prefix sums; singleton differences = zero|grow interval lengths:|    leftChoice = remainingLeftSum-dp[left+1][right]|    rightChoice = remainingRightSum-dp[left][right-1]|store the greater choice and return full interval difference','O(n^2) time and interval-table space.'],
1691:['cuboids','Stack rotatable cuboids for maximum total height while respecting all three dimension limits.','Sort each cuboid dimensions so its largest dimension becomes height, then order cuboids. Dynamic programming tries every compatible smaller stack above each candidate base.','sort dimensions within each cuboid and sort cuboids|dp[i] = cuboid height|for earlier cuboid fitting in all three dimensions:|    maximize dp[i] with earlier stack height plus base height|return maximum stack height','O(n^2+n log n) time; O(n) state.'],
1694:['number','Remove separators and regroup phone digits into blocks of two or three.','Take three digits while more than four remain. Finish four as two pairs, preventing a final singleton block.','strip spaces and hyphens|while more than four digits remain:|    take next three digits|finish four as two pairs, otherwise use the remaining block|join blocks with hyphens','O(n^2) conservative slicing time; O(n) string space.'],
1695:['nums','Find the greatest sum of a contiguous subarray containing no repeated values.','Keep a set and running sum for the current unique window. On a repeated incoming value, remove left entries through its old occurrence; positive values make the longest valid suffix best.','left = total = best = 0; seen = {}|for right,value:|    remove left entries while value already present|    insert value, add it, and maximize total|return best','O(n) expected time; O(n) set space.'],
};

export function validateProgress(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const text=(s,regex=/^[a-z]+$/,max=160)=>typeof s==='string'&&s.length>=1&&s.length<=max&&regex.test(s);
 const strings=(a)=>Array.isArray(a)&&a.length>=1&&a.length<=40&&a.every(s=>text(s,/^[a-z]+$/,40));
 for(const key of ['arr','scores','ages','releaseTimes','nums','l','r','heights','code','aliceValues','bobValues','stones'])if(key in input)check(vector(input[key]),`${key}: use 1-100 bounded integers.`);
 if(id===1615){check(integer(input.n,2,30)&&Array.isArray(input.roads)&&input.roads.length<=100&&input.roads.every(p=>vector(p,2,2,0,input.n-1)&&p[0]!==p[1]),'Use 2-30 cities and valid distinct undirected roads.');check(new Set(input.roads.map(([a,b])=>[Math.min(a,b),Math.max(a,b)].join(','))).size===input.roads.length,'Do not repeat a road.');}
 if(id===1616)check(text(input.a)&&text(input.b)&&input.a.length===input.b.length,'Use equal-length nonempty lowercase strings.');
 if(id===1619)check(input.arr.length%20===0&&input.arr.every(v=>v>=0),'Use 20-100 nonnegative values, with length divisible by twenty.');
 if([1624,1647,1653].includes(id))check(text(input.s,id===1653?/^[ab]+$/:/^[a-z]+$/),'Use nonempty lowercase text, restricted to a and b for the balancing problem.');
 if(id===1626)check(input.scores.length===input.ages.length&&input.scores.every(v=>v>0)&&input.ages.every(v=>v>0),'Use equal-length positive scores and ages.');
 if(id===1629)check(text(input.keysPressed)&&input.keysPressed.length===input.releaseTimes.length&&input.releaseTimes.every((v,i,a)=>v>0&&(!i||v>a[i-1])),'Use one lowercase key per strictly increasing positive release time.');
 if(id===1630)check(input.l.length===input.r.length&&input.l.length<=30&&input.l.every((v,i)=>integer(v,0,input.nums.length-2)&&integer(input.r[i],v+1,input.nums.length-1)),'Use matching query endpoints selecting at least two valid positions.');
 if(id===1637)check(Array.isArray(input.points)&&input.points.length>=2&&input.points.length<=60&&input.points.every(p=>vector(p,2,2)),'Use 2-60 bounded coordinate pairs.');
 if(id===1638)check(text(input.s,/^[a-z]+$/,25)&&text(input.t,/^[a-z]+$/,25),'Use nonempty lowercase strings of at most 25 characters for detailed enumeration.');
 if(id===1640){check(new Set(input.arr).size===input.arr.length&&Array.isArray(input.pieces)&&input.pieces.length>=1&&input.pieces.every(p=>vector(p)),'Use distinct target values and nonempty integer pieces.');const flat=input.pieces.flat();check(flat.length===input.arr.length&&new Set(flat).size===flat.length,'Piece entries must be distinct and total the target length.');}
 if(id===1641)check(integer(input.n,1,50),'Use string length 1-50.');
 if(id===1642)check(input.heights.every(v=>v>=1)&&integer(input.bricks,0,1000000)&&integer(input.ladders,0,input.heights.length),'Use positive heights and nonnegative resource supplies.');
 if(id===1646)check(integer(input.n,0,100),'Use an index from zero through one hundred.');
 if(id===1652)check(input.code.every(v=>v>=1)&&integer(input.k,1-input.code.length,input.code.length-1),'Use positive code values and abs(k) smaller than the array length.');
 if(id===1656){check(integer(input.n,1,60)&&Array.isArray(input.operations)&&input.operations.length>=1&&input.operations.length<=input.n&&input.operations.every(p=>Array.isArray(p)&&p.length===2&&integer(p[0],1,input.n)&&text(p[1],/^[a-z]+$/,20)),'Use size 1-60 and insertions [unique ID, lowercase value].');check(new Set(input.operations.map(p=>p[0])).size===input.operations.length,'Each stream ID can be inserted only once.');}
 if(id===1657)check(text(input.word1)&&text(input.word2),'Use nonempty lowercase words.');
 if(id===1658)check(input.nums.every(v=>v>=1)&&integer(input.x,1,1000000),'Use positive values and a positive removed-sum target.');
 if(id===1662)check(strings(input.word1)&&strings(input.word2),'Use nonempty lists of lowercase string chunks.');
 if(id===1663)check(integer(input.n,1,100)&&integer(input.k,input.n,26*input.n),'Use length 1-100 and a value between n and 26*n.');
 if(id===1664)check(input.nums.every(v=>v>=1),'Use positive array values.');
 if(id===1668)check(text(input.sequence)&&text(input.word),'Use a nonempty lowercase sequence and word.');
 if(id===1673)check(integer(input.k,1,input.nums.length),'Use a subsequence length between one and array length.');
 if(id===1678)check(text(input.command,/^(?:G|\(\)|\(al\))+$/),'Use only concatenated tokens G, (), and (al).');
 if(id===1679)check(input.nums.every(v=>v>=1)&&integer(input.k,1,20000),'Use positive values and a positive pair target.');
 if(id===1680)check(integer(input.n,1,100),'Use n 1-100 for individual concatenation playback.');
 if(id===1684)check(text(input.allowed)&&new Set(input.allowed).size===input.allowed.length&&strings(input.words),'Use distinct lowercase allowed letters and lowercase words.');
 if(id===1685)check(input.nums.every((v,i,a)=>v>=1&&(!i||v>=a[i-1])),'Use a nondecreasing positive array.');
 if(id===1686)check(input.aliceValues.length===input.bobValues.length&&[...input.aliceValues,...input.bobValues].every(v=>v>=1),'Use matching positive stone valuations for both players.');
 if(id===1688)check(integer(input.n,1,1000000),'Use one through one million teams.');
 if(id===1689)check(text(input.n,/^[1-9][0-9]*$/),'Use a positive decimal string without leading zeros.');
 if(id===1690)check(input.stones.length>=2&&input.stones.length<=20&&input.stones.every(v=>v>=1),'Use 2-20 positive stone values for interval-table playback.');
 if(id===1691)check(Array.isArray(input.cuboids)&&input.cuboids.length>=1&&input.cuboids.length<=40&&input.cuboids.every(c=>vector(c,3,3,1,1000)),'Use 1-40 cuboids, each with three positive dimensions.');
 if(id===1694)check(text(input.number,/^[0-9 -]+$/)&&input.number.replace(/[ -]/g,'').length>=2,'Use digits, spaces, and hyphens, containing at least two digits.');
 if(id===1695)check(input.nums.every(v=>v>=1),'Use positive values for the maximum-sum unique window.');
 return input;
}
