export const broadSpecs={
1870:['dist hour','Find the smallest integer train speed that meets a time budget with whole-hour departures.','Every nonfinal ride rounds up to a whole hour. Feasibility improves with speed, so binary search using exact hundredth-hour comparisons.','reject budgets leaving no time for the last ride|binary search integer speed|sum rounded nonfinal rides and fractional final ride|lower speed bound on failure, upper bound on success|return first feasible speed','O(n log 10000000) time; O(1) state.'],
1871:['s minJump maxJump','Reach the final zero using jumps within the allowed length interval.','Keep a sliding count of reachable predecessor indices. A zero position is reachable when at least one legal predecessor is reachable.','reachable[0] = true|scan later positions|add entering and remove leaving predecessor reachability|mark a zero reachable when predecessor count is positive|return final-position reachability','O(n) time; O(n) reachability state.'],
1872:['stones','Find the optimal score difference in a game merging at least two leftmost stones each turn.','Prefix sums represent all possible merged values. Scan legal first-move boundaries backward, comparing the existing best with current prefix sum minus opponent continuation.','build prefix sums; best = whole-array sum|scan boundaries backward, excluding the first singleton|candidate = prefix[boundary]-best|best = max(best,candidate)|return optimal difference','O(n) time; O(n) prefix space.'],
1874:['nums1 nums2','Minimize the product sum by rearranging array pairings.','Pair one array in increasing order with the other in decreasing order. This avoids multiplying large values together when a smaller partner is available.','sort one array ascending and the other descending|visit aligned positions|multiply each opposing-rank pair|add products to total|return minimum product sum','O(n log n) time; O(n) sorted-copy space.'],
1876:['s','Count length-three substrings with three distinct characters.','Slide a three-character window; the window qualifies precisely when its character set has size three.','answer = 0|visit every length-three window|check distinct character count|add one only for three distinct characters|return answer','O(n) time; O(1) state.'],
1877:['nums','Pair all entries to minimize the greatest pair sum.','Sorted extremes should pair together. Assigning the largest value its smallest possible partner prevents an unnecessarily large worst pair.','sort values|pair smallest remaining with largest remaining|compute their sum|retain the greatest pair sum|return minimized maximum','O(n log n) time; O(n) sorted-copy space.'],
1879:['nums1 nums2','Minimize XOR sum by assigning second-array positions to first-array positions.','A bitmask records used second-array positions. Its population count identifies the next first-array entry, making all assignment histories with the same mask share one best cost.','dp[empty mask] = 0|visit used-position masks|try every unused second-array position|relax enlarged mask with current cost plus pair XOR|return full-mask cost','O(n*2^n) time; O(2^n) DP space.'],
1880:['firstWord secondWord targetWord','Compare numeric word values after mapping letters a through j to digits.','Treat each word as decimal digits, including leading zero letters. Accumulate values and compare the first two summed with the third.','convert each word independently|for each mapped digit|value = 10*value+digit|compare first value plus second with target value|return equality','O(total word length) time; O(1) numeric state.'],
1881:['n x','Insert digit x into a signed decimal string to maximize its numeric value.','For positive numbers insert before the first smaller digit. For negative numbers reduce magnitude by inserting before the first larger digit; otherwise append.','detect sign and skip any minus sign|scan existing digits|find first digit improved by insertion under the sign|insert there, or append if no earlier improvement|return new signed string','O(n) time and output space.'],
1882:['servers tasks','Assign arriving tasks to servers using weight and index priority while preserving task order.','Track each server next-free time. Process tasks in arrival order, waiting for the first completion if necessary, then choose the lowest-weight available server and smallest index.','free times = zero; clock = zero|for each task in arrival order|collect available servers or jump to earliest completion|choose lowest weight then index and update its finish time|return assigned server indices','O(tasks*servers log servers) direct sorting bound; O(servers+tasks) space.'],
1884:['n','Find the minimum worst-case moves to determine the critical floor using two eggs.','With m moves, decreasing drop gaps can cover m+(m-1)+...+1 floors. Increase the move count until this triangular coverage reaches n.','moves = covered = 0|while coverage is below n|increment moves|add moves to covered floors|return moves','O(sqrt(n)) time; O(1) state.'],
1885:['nums1 nums2','Count index pairs whose first-array sum exceeds their second-array sum.','Subtract aligned arrays to convert the condition into a positive pair sum. Sort differences and count whole ranges of successful partners with two pointers.','sort aligned differences|while left < right|if endpoint sum is positive, all partners for right qualify|count them and lower right; otherwise raise left|return pair count','O(n log n) time; O(n) difference space.'],
1886:['mat target','Decide whether rotating a square matrix by quarter-turns can match the target.','Compare all cells at each of the four possible orientations. Rotate coordinates clockwise between comparisons.','copy matrix|try zero, one, two, and three quarter-turns|compare every cell with target|return true on a match, otherwise rotate|return false after all orientations fail','O(n^2) time and copied-matrix space.'],
1887:['nums','Count reductions needed to make every value equal by repeatedly lowering a maximum to the next distinct value.','After sorting, a value crosses one reduction level for each distinct smaller value. Add its level count once per occurrence.','sort values; levels = answer = 0|scan after the first value|increase level at each distinct-value boundary|add current level for each occurrence|return operation count','O(n log n) time; O(n) sorted-copy space.'],
1888:['s','Minimize bit flips to make some cyclic rotation alternate.','Every length-n window of the doubled string represents a rotation. Maintain mismatch count against an alternating target; the complement target has n minus that count.','double the binary string|slide a length-n window|add incoming and remove outgoing parity mismatches|minimize mismatch count and its complement|return fewest flips','O(n) time; O(n) doubled-string space.'],
1891:['ribbons k','Cut at least k equal-length ribbon pieces while maximizing their integer length.','At a candidate length, each ribbon supplies its floor-divided piece count. Feasibility decreases with larger cuts, allowing binary search with zero as the impossible result.','low = 0; high = longest ribbon|try upper midpoint length|count sum(floor(ribbon/length)) pieces|raise low if at least k pieces, otherwise lower high|return greatest feasible length','O(n log maximum ribbon) time; O(1) state.'],
1893:['ranges left right','Check that every integer in an inclusive target interval is covered by some input range.','Track the next uncovered integer while reading sorted ranges. Overlapping or adjacent ranges extend coverage; a range starting later exposes a permanent gap.','sort ranges; next = left|ignore ranges ending before next|reject any next start beyond next|extend next to end+1 and finish when beyond right|return whether target was fully covered','O(n log n) time; O(n) sorted-copy space.'],
1894:['chalk k','Find the first student who cannot complete their turn with the available chalk.','Full rounds consume a constant total, so reduce k modulo that total. Scan one partial round and require strictly less chalk than the current need to trigger replacement.','reduce k modulo total chalk per cycle|scan student needs in order|compare remaining with current need|return index if insufficient, otherwise subtract need|return the first failing student','O(n) time; O(1) state.'],
1897:['words','Decide whether redistributing characters can make all words equal.','Only total frequency matters because characters may move across word boundaries. Every letter count must be divisible by the number of words.','count all characters across words|inspect each distinct letter|test divisibility by number of words|reject any remainder|return true if every count divides evenly','O(total characters) time; O(alphabet) state.'],
1898:['s p removable','Remove the longest prefix of the removal list while keeping p as a subsequence of s.','Store each position removal order. For a proposed count, skip removed positions and greedily match p; feasibility is monotone under additional removals.','record removal time per string position|binary search proposed removal count|match p while skipping positions removed before that count|keep feasible larger counts, reject infeasible ones|return maximum count','O((length s)*log removal count) time; O(length s) state.'],
1899:['triplets target','Decide whether coordinatewise maximum merges can produce the target triplet.','Any triplet exceeding the target in one coordinate is unusable. Merge all compatible triplets; success requires reaching each target coordinate.','best = zero triplet|for each triplet|discard it if any coordinate exceeds target|otherwise update compatible coordinate maxima|return best equals target','O(n) time; O(1) state.'],
1905:['grid1 grid2','Count grid-two islands entirely contained inside grid-one land.','Traverse each grid-two component completely. Every cell must be land in grid one; continue traversal even after failure so the same island is never counted again.','mark grid-two cells unvisited|start a traversal at each new land component|inspect every cell against grid one and visit all neighbors|count the component only when every cell is covered|return sub-island count','O(rows*columns) time and traversal/visited space.'],
1915:['word','Count substrings with at most one character occurring an odd number of times.','Prefix parity masks differ by the substring parity. Equal masks give all-even counts; a one-bit difference gives exactly one odd-count letter.','previous mask zero has count one|toggle current letter bit in prefix mask|count earlier equal masks and all ten one-bit neighbors|add those counts and record current mask|return total wonderful substrings','O(10*n) time; O(2^10) mask-count state.'],
};
export function broadResultStage(id, result, lastFrame) {
 if (id === 1870 && result === -1) return 'failed';
 if (id === 1886 && result) return 'accepted';
 if (id === 1893) return result ? 'accepted' : lastFrame?.codeStage === 'gap' ? 'gapReturn' : 'return';
 if (id === 1897 && !result) return 'rejected';
 return 'return';
}
export function validateBroad(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const int=(v,lo=0,hi=10000)=>Number.isSafeInteger(v)&&v>=lo&&v<=hi;
 const vec=(a,min=1,max=80,lo=-10000,hi=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>int(v,lo,hi));
 const text=(s,re=/^[a-z]+$/,max=120)=>typeof s==='string'&&s.length>=1&&s.length<=max&&re.test(s);
 for(const key of ['dist','stones','nums','nums1','nums2','servers','tasks','ribbons','chalk','removable','target'])if(key in input&&!(id===1886&&key==='target'))check(vec(input[key],key==='removable'?0:1),`${key}: use bounded integer arrays of at most eighty entries.`);
 if(id===1870)check(input.dist.every(v=>v>0)&&typeof input.hour==='number'&&Number.isFinite(input.hour)&&input.hour>0&&input.hour<=10000&&Math.abs(input.hour*100-Math.round(input.hour*100))<1e-7,'Use positive distances and positive hours with at most two decimal places.');
 if(id===1871)check(text(input.s,/^0[01]+$/)&&int(input.minJump,1,input.s.length-1)&&int(input.maxJump,input.minJump,input.s.length-1),'Use a binary string starting with zero and valid minimum/maximum jump lengths.');
 if(id===1872)check(input.stones.length>=2,'Use at least two stone values.');
 if([1874,1879,1885].includes(id))check(input.nums1.length===input.nums2.length&&[...input.nums1,...input.nums2].every(v=>v>=0),'Use equally sized nonnegative arrays.');
 if(id===1876)check(text(input.s),'Use a lowercase string.');
 if(id===1877)check(input.nums.length%2===0&&input.nums.every(v=>v>0),'Use an even number of positive values.');
 if(id===1879)check(input.nums1.length<=9,'Use at most nine positions for explicit mask-state playback.');
 if(id===1880)check(['firstWord','secondWord','targetWord'].every(key=>text(input[key],/^[a-j]+$/,8)),'Use words of one through eight letters from a through j.');
 if(id===1881)check(text(input.n,/^-?[1-9][1-9]*$/)&&int(input.x,1,9),'Use a signed nonzero digit string without zeros and one inserted digit from one through nine.');
 if(id===1882)check(input.servers.every(v=>v>0)&&input.tasks.every(v=>v>0),'Use positive server weights and task durations.');
 if(id===1884)check(int(input.n,1,10000),'Use one through ten thousand floors.');
 if(id===1886){for(const key of ['mat','target']){const g=input[key];check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vec(row,g.length,g.length,0,1)),'Use square binary matrices up to eight by eight.');}check(input.mat.length===input.target.length,'Matrices must have matching dimensions.');}
 if(id===1887)check(input.nums.every(v=>v>0),'Use positive values.');
 if(id===1888)check(text(input.s,/^[01]+$/),'Use a nonempty binary string.');
 if(id===1891)check(input.ribbons.every(v=>v>0)&&int(input.k,1,1000000),'Use positive ribbon lengths and a positive requested piece count.');
 if(id===1893)check(Array.isArray(input.ranges)&&input.ranges.length>=1&&input.ranges.length<=50&&input.ranges.every(r=>vec(r,2,2,1)&&r[0]<=r[1])&&int(input.left,1)&&int(input.right,input.left),'Use valid positive inclusive ranges and target endpoints.');
 if(id===1894)check(input.chalk.every(v=>v>0)&&int(input.k,0,1000000000),'Use positive chalk needs and a nonnegative budget at most one billion.');
 if(id===1897)check(Array.isArray(input.words)&&input.words.length>=1&&input.words.length<=30&&input.words.every(w=>text(w,/^[a-z]+$/,30)),'Use nonempty lowercase words.');
 if(id===1898){check(text(input.s)&&text(input.p)&&new Set(input.removable).size===input.removable.length&&input.removable.every(v=>int(v,0,input.s.length-1)),'Use lowercase strings and distinct valid removal indices.');let j=0;for(const c of input.s)if(c===input.p[j])j++;check(j===input.p.length,'p must initially be a subsequence of s.');}
 if(id===1899)check(vec(input.target,3,3,1)&&Array.isArray(input.triplets)&&input.triplets.length>=1&&input.triplets.length<=60&&input.triplets.every(t=>vec(t,3,3,1)),'Use positive triplets and a positive three-coordinate target.');
 if(id===1905){for(const key of ['grid1','grid2']){const g=input[key];check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vec(row,1,8,0,1)&&row.length===g[0].length),'Use rectangular binary grids up to eight by eight.');}check(input.grid1.length===input.grid2.length&&input.grid1[0].length===input.grid2[0].length,'Both grids must have matching dimensions.');}
 if(id===1915)check(text(input.word,/^[a-j]+$/),'Use letters a through j only.');
 return input;
}
