export const moreSpecs={
1262:['nums','Find the greatest subset sum divisible by three.','Keep the best achievable sum for each remainder. Every value reads an unchanged previous row, preventing it from being selected more than once.','best = [0, unreachable, unreachable]|for value:|    consider skip and take from each previous remainder|    replace best with the completed next row|return best[0]','O(n) time; O(1) state.'],
1266:['points','Visit points in order using the least number of unit horizontal, vertical, or diagonal moves.','Use diagonal motion while both coordinates differ, then finish along the remaining axis. Each segment needs the larger absolute coordinate difference.','total = 0|for consecutive point pair:|    compute absolute x and y differences|    add their maximum|return total','O(n) time; O(1) state.'],
1275:['moves','Determine the result of an alternating tic-tac-toe move sequence.','Only lines passing through the newest mark can become newly complete. Return the first winning player, otherwise distinguish a full board from an unfinished game.','board = empty 3 by 3 grid|for alternating move:|    mark its player and inspect affected lines|    return player if a line is complete|return Draw for nine moves, otherwise Pending','O(number of moves) time; O(1) board space.'],
1276:['tomatoSlices cheeseSlices','Find nonnegative jumbo and small burger counts that use all ingredients.','Cheese fixes the total burger count. Two tomatoes per burger form the baseline; every additional pair converts one small burger into a jumbo.','jumbo = tomatoes/2 - cheese|small = cheese-jumbo|check jumbo is an integer|require both counts nonnegative|return [jumbo,small] or an empty list','O(1) time and space.'],
1277:['matrix','Count every square submatrix containing only ones.','At a one cell, the smallest neighboring square limit determines how far a new square can extend. Its maximal side also counts all square sizes ending there.','dp = zero matrix; total = 0|for each cell in row order:|    if one, read upper, left, and upper-left limits|    write one plus their minimum and add it to total|return total','O(rc) time and DP space.'],
1281:['n','Subtract the sum of decimal digits from their product.','Maintain independent product and sum accumulators. A zero digit collapses the product but leaves the other digits relevant to the sum.','product = 1; total = 0|for decimal digit:|    convert digit to integer|    multiply product and add into total|return product-total','O(d) time and digit representation space.'],
1282:['groupSizes','Partition people so each group has its members requested size.','Maintain a waiting bucket per requested size. Once a bucket fills exactly, emit it and start a fresh bucket for later people of that size.','waiting = {}; output = []|for person,size:|    append person to size bucket|    emit and clear bucket when it reaches size|return groups','O(n) time and grouping space.'],
1287:['arr','Find the unique value occurring in more than a quarter of a sorted array.','Equal values occupy consecutive positions. Matching endpoints separated by floor(n/4) certify a run longer than one quarter.','offset = floor(length/4)|for each possible starting index:|    compare value with the value offset positions later|    return value if endpoints match|return -1 if the frequency promise is violated','O(n) time; O(1) state.'],
1288:['intervals','Count intervals not covered by another interval.','Sort by start ascending and end descending. An end no farther than the greatest earlier end is fully covered, including equal-start intervals.','sort by start ascending, then end descending|for interval:|    compare end with farthest earlier end|    count and extend farthest only when end is larger|return retained count','O(n log n) time; O(n) sorted-copy space.'],
1291:['low high','List all numbers within the range whose digits increase consecutively by one.','Every such number is a contiguous slice of 123456789. Enumerate valid lengths and starts, then retain the inclusive range matches.','output = []|for length two through nine and valid start:|    form that consecutive-digit slice|    retain values between low and high|return sorted output','O(1) bounded candidate count; output space.'],
1292:['mat threshold','Find the largest square whose sum is at most the threshold.','A two-dimensional prefix table answers square sums with four accesses. Nonnegative entries make larger squares at one corner no cheaper than smaller ones.','build two-dimensional prefix sums; best = 0|for top-left corner:|    try larger squares than current best|    extend while sum fits, stop when it exceeds threshold|return best side length','O(rc min(r,c)) time; O(rc) prefix space.'],
1296:['nums k','Decide whether all values partition into groups of k consecutive numbers.','The smallest remaining value must start every group containing its remaining copies. Consume the same multiplicity from the next k-1 values or reject.','reject length not divisible by k; count values|for smallest remaining value:|    read its remaining multiplicity|    remove that many copies from each required consecutive value|return true if all demands fit','O(n log n + uk) direct counting work; O(u) space.'],
1299:['arr','Replace each element with the greatest element strictly to its right.','Scanning backward makes the suffix maximum available before updating it with the current value. The last output is minus one because its suffix is empty.','greatest = -1; output = same-length array|for index from right to left:|    write current suffix greatest|    update greatest with original value|return output','O(n) time and output space.'],
1300:['arr target','Choose an integer cap making the capped sum closest to the target, preferring the smaller cap on ties.','Capped sums are monotone. Find the first cap whose sum reaches the target, then compare it with its predecessor to handle undershoot and overshoot.','low = 0; high = maximum value|binary search the first capped sum >= target|compute errors at crossing cap and predecessor|choose smaller error, breaking ties toward smaller cap|return cap','O(n log M) time; O(1) algorithm state.'],
1304:['n','Construct n distinct integers summing to zero.','Opposite nonzero pairs cancel independently. If an odd count is needed, include a single zero without duplicating any existing number.','output = []|for value one through floor(n/2):|    choose the pair -value and value|    append both, then add zero when n is odd|return output','O(n) time and output space.'],
1306:['arr start','Decide whether exact left or right jumps can reach a zero-valued index.','Treat indices as graph vertices with at most two outgoing edges. A visited set prevents cycles while breadth-first traversal explores every reachable candidate.','queue = [start]; visited = {start}|for each queued index:|    return true if its value is zero|    enqueue unseen in-range index plus or minus its value|return false when the reachable set is exhausted','O(n) time and traversal space.'],
1309:['s','Decode one-digit and hash-terminated two-digit alphabet codes.','Look ahead for a hash two positions later before consuming a digit. It identifies the two-digit codes for letters j through z.','output = []|while encoded characters remain:|    choose two digits if followed by hash, otherwise one|    convert code to a letter and advance past its full token|return joined output','O(n) time and output space.'],
1310:['arr queries','Answer inclusive subarray XOR queries.','XOR is self-canceling. The XOR of two prefix values removes the common earlier prefix and retains exactly the requested interval.','prefix[0] = 0|append cumulative XOR for each value|for left,right query:|    append prefix[right+1] XOR prefix[left]|return query answers','O(n+q) time and space.'],
1313:['nums','Expand a flat list of frequency-value pairs.','Every even-position entry is a count and its following entry is the repeated value. Preserve pair order and append exactly the requested multiplicity.','output = []|visit pairs two entries at a time:|    read frequency then value|    append value frequency times|return output','O(encoded length + output length) time; output space.'],
1314:['mat k','Compute the sum of each cell neighborhood within row and column distance k.','Clip neighborhood boundaries to the matrix, then apply four-corner inclusion-exclusion to a prefix table. Keep input and output separate.','build two-dimensional prefix sums|for every output cell:|    clip top,left,bottom,right to valid bounds|    recover the clipped rectangle sum|return output matrix','O(rc) time and space.'],
1317:['n','Split n into two positive integers containing no zero digits.','Try a positive first addend and derive the other by subtraction. Check both decimal representations before returning any valid pair.','for first from one through n-1:|    second = n-first|    inspect both decimal strings for zero|    return pair if neither contains zero|return empty list if no pair exists','O(n log n) direct-search time; O(log n) representation space.'],
1318:['a b c','Count the fewest input bit flips needed to make a OR b equal c.','Bits are independent. A target zero requires clearing both input ones, while a target one requires a single flip only if both inputs are zero.','flips = 0|while any value has remaining bits:|    inspect both input low bits and target low bit|    add required flips and shift all values right|return flips','O(log M) time; O(1) state.'],
1323:['num','Maximize a number by changing at most one six to nine or nine to six.','Changing the earliest six yields the largest place-value gain. If there is no six, leaving the number unchanged is optimal.','digits = decimal digits|find the first six|if present, replace it with nine|join digits back into a number|return number','O(d) time and representation space.'],
1328:['palindrome','Replace one character to create the lexicographically smallest nonpalindrome.','Lower the earliest non-a in the first half, avoiding an odd middle character. If none exists, raise the last character to b. A single character is impossible.','return empty for length one|scan only the first half:|    find first character not equal to a|    replace it with a and return, or change final character to b|return rebuilt string','O(n) time and copied-character space.'],
1331:['arr','Replace values with one-based ranks among distinct sorted values.','Equal values share one rank. Rank increments only when the sorted distinct value changes, so there are no skipped ranks.','sort distinct values|map each value to its index plus one|for original value:|    append its mapped rank|return ranks in original order','O(n log n) time; O(n) space.'],
1332:['s','Minimize removals of palindromic subsequences from an a/b string.','One removal suffices exactly when the whole string is palindromic. Otherwise, all a characters and then all b characters form two removable subsequences.','compare s with its reversal|if they are equal:|    the whole string is one valid removal|otherwise use the two single-letter subsequences|return one or two','O(n) time and reversal space.'],
1337:['mat k','Return the k weakest matrix rows, resolving equal strength by row index.','A row strength is its soldier count. Sorting by the pair of strength and original index establishes both the main order and deterministic ties.','count soldiers in each row|sort rows by count then index|for first k ranked rows:|    append original row index|return selected indices','O(rc + r log r) time; O(r) ranking state.'],
1342:['num','Count the required operations to reduce a nonnegative integer to zero.','An odd value must lose one before division can help; an even value halves. Apply the specified rule until no value remains.','steps = 0|while value is nonzero:|    inspect whether it is odd or even|    subtract one or halve, then count a step|return steps','O(log(num+1)) time; O(1) state.'],
1343:['arr k threshold','Count length-k subarrays whose average is at least the threshold.','Maintain one rolling sum. Comparing it to k times the threshold avoids division and preserves the inclusive comparison.','sum = count = 0|for next value:|    add entering value and remove expired value|    count complete windows with sum >= k*threshold|return count','O(n) time; O(1) state.'],
1344:['hour minutes','Find the smaller angle between the clock hands.','The hour hand advances within the hour as minutes pass. Compute both absolute angles, then choose the smaller of the direct and complementary gaps.','hourAngle = (hour modulo 12)*30 + minutes/2|minuteAngle = minutes*6|difference = absolute angle difference|compare difference with 360-difference|return smaller angle','O(1) time and space.'],
1346:['arr','Decide whether two distinct positions contain a value and its double.','Before inserting the current value, look for its double or integer half among earlier values. This handles either order and requires two zero occurrences.','seen = empty set|for value:|    check earlier double or an integer half|    return true on match, otherwise remember value|return false','O(n) expected time and space.'],
1347:['s t','Minimize replacements in t needed to make it an anagram of s.','Positive count deficits measure the letters t lacks. Since lengths agree, its surplus characters can supply exactly those replacements.','counts = frequencies(s) minus frequencies(t)|for character deficit:|    ignore zero and negative deficits|    add positive deficits to replacement count|return replacements','O(n) time; O(alphabet size) state.'],
1351:['grid','Count negative cells in a row- and column-nonincreasing matrix.','From the bottom-left corner, a negative value certifies its entire rightward row suffix. A nonnegative value certifies the whole upward column prefix.','row = bottom; column = zero; count = 0|while inside the matrix:|    inspect current sign|    count right suffix and move up if negative, otherwise move right|return count','O(rows+columns) time; O(1) state.'],
1356:['arr','Sort values by their number of one bits, then numerically.','Compute binary population counts as the primary key. Numeric tie-breaking makes values with equal bit counts appear in ascending order.','copy values|compute binary one-count keys|sort by (one count, numeric value)|read ranked values in order|return sorted copy','O(n log n * log M) direct bit-count sorting work; O(n) space.'],
1360:['date1 date2','Count calendar days between two dates regardless of their order.','Use midnight in UTC for both dates. Daylight-saving transitions then cannot distort the number of complete calendar days.','parse both dates at UTC midnight|subtract their timestamps|take the absolute difference|divide by milliseconds in one day|return day count','O(1) time and space.'],
1365:['nums','For each entry, count strictly smaller values at other positions.','Its first index in a sorted copy equals the number of smaller entries. Repeated values all share the same first index.','sort a copy|record first index of each distinct value|scan original values|append each value first index|return counts','O(n log n) time; O(n) space.'],
1370:['s','Reorder a string by alternating increasing and decreasing available-letter sweeps.','Each sweep takes at most one of each remaining character. Counts preserve duplicates for later sweeps until all characters are used.','count letters and sort distinct keys|while characters remain:|    take available letters once in current direction|    reverse direction for the next sweep|return joined output','O(n * alphabet size) bounded-alphabet work; O(n) output space.'],
1374:['n','Construct a length-n string where every occurring character has odd frequency.','For odd n, one character suffices. For even n, use n-1 copies of one character and one copy of a different character.','inspect parity of n|if n is odd:|    choose n copies of a|otherwise choose n-1 copies of a and one b|return constructed string','O(n) output time and space.'],
1380:['matrix','Find values that are minimum in their row and maximum in their column.','Row minima and column maxima impose independent requirements. A lucky cell must satisfy both at the same coordinates.','compute row minima and column maxima|visit each cell:|    compare with its row minimum and column maximum|    collect cells satisfying both|return lucky values','O(rc) time; O(r+c) summary state plus output.'],
1385:['arr1 arr2 d','Count first-array values farther than d from every second-array value.','One close second-array value disqualifies a candidate. Distance equal to d is still too close because the requirement is strictly greater.','count = 0|for value in first array:|    search second array for distance <= d|    count value only when no such neighbor exists|return count','O(nm) time; O(1) auxiliary state.'],
1389:['nums index','Construct a target array by inserting each value at its supplied current index.','Apply insertions in order. Every insertion shifts the existing suffix, and subsequent indices address the updated array.','target = []|for input position i:|    read nums[i] and index[i]|    insert value into current target at that index|return target','O(n^2) time for shifting insertions; O(n) space.'],
1394:['arr','Find the largest integer equal to its own occurrence count.','Build complete frequencies before comparing values with counts. Return the largest equality, or minus one if no value qualifies.','counts = frequencies(arr); best = -1|for value,frequency:|    compare value with frequency|    maximize best only on equality|return best','O(n) time; O(u) state.'],
1399:['n','Count digit-sum groups tied for the largest size among integers one through n.','Accumulate the population of each digit-sum bucket. Then count every bucket whose population matches the global maximum.','groups = {}|for value from one through n:|    compute its decimal digit sum|    increment that bucket size|return number of buckets with maximum size','O(n log n) time; O(log n) possible digit-sum buckets.'],
1400:['s k','Decide whether all characters can form exactly k nonempty palindromes.','Each odd-frequency character requires a separate center. Between that minimum and the character count, pairs can be split to create additional nonempty palindromes.','counts = letter frequencies|count odd frequencies|require odd count <= k|require k <= total character count|return whether both requirements hold','O(n) time; O(alphabet size) state.'],
};

export function validateMore(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const tuples=(a,width,min=1,max=80)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(p=>vector(p,width,width));
 const text=(s,regex=/^[a-z]+$/)=>typeof s==='string'&&s.length>=1&&s.length<=160&&regex.test(s);
 const frequencies=a=>{const m=new Map();for(const v of a)m.set(v,(m.get(v)||0)+1);return m;};
 for(const key of ['nums','arr','arr1','arr2','groupSizes','index'])if(key in input)check(vector(input[key],id===1331?0:1),`${key}: use at most 100 bounded integer entries.`);
 for(const key of ['matrix','mat','grid'])if(key in input){const g=input[key];check(Array.isArray(g)&&g.length>=1&&g.length<=10&&g.every(row=>vector(row,1,10)&&row.length===g[0].length),`${key}: use a rectangular 1-10 by 1-10 integer grid.`);if([1277,1337].includes(id))check(g.flat().every(v=>v===0||v===1),'Use a binary matrix.');if([1292,1314].includes(id))check(g.flat().every(v=>v>=0),'Use nonnegative matrix values.');}
 for(const key of ['s','t','palindrome'])if(key in input)check(text(input[key],id===1309?/^(?:[1-9]|(?:1[0-9]|2[0-6])#)+$/:id===1332?/^[ab]+$/:/^[a-z]+$/),`${key}: use valid nonempty characters for this problem, at most 160.`);
 if([1262,1296,1299,1300,1343,1394].includes(id))check(input[id===1262||id===1296?'nums':'arr'].every(v=>v>=1),'Use positive array values.');
 if(id===1266)check(tuples(input.points,2,1,60),'Use 1-60 bounded coordinate pairs.');
 if(id===1275){check(tuples(input.moves,2,0,9)&&input.moves.every(p=>p.every(v=>integer(v,0,2)))&&new Set(input.moves.map(p=>p.join(','))).size===input.moves.length,'Use up to nine distinct board coordinates from zero to two.');const board=Array.from({length:3},()=>Array(3).fill('.'));for(let i=0;i<input.moves.length;i++){const[r,c]=input.moves[i],p=i%2?'B':'A';board[r][c]=p;const win=board.some(row=>row.every(v=>v===p))||[0,1,2].some(col=>board.every(row=>row[col]===p))||board.every((row,j)=>row[j]===p)||board.every((row,j)=>row[2-j]===p);check(!win||i===input.moves.length-1,'No moves may follow an already won game.');}}
 if(id===1276)check(integer(input.tomatoSlices,0,1000000)&&integer(input.cheeseSlices,0,1000000),'Ingredient counts must be nonnegative bounded integers.');
 if(id===1281)check(integer(input.n,1,1000000000),'Use a positive integer at most one billion.');
 if(id===1282)check(input.groupSizes.every(v=>integer(v,1,input.groupSizes.length))&&[...frequencies(input.groupSizes)].every(([size,count])=>count%size===0),'Requested group sizes must permit a complete partition.');
 if(id===1287)check(input.arr.every((v,i,a)=>!i||v>=a[i-1])&&[...frequencies(input.arr).values()].filter(n=>4*n>input.arr.length).length===1,'Use a sorted array with exactly one value appearing more than 25 percent.');
 if(id===1288)check(tuples(input.intervals,2)&&input.intervals.every(([a,b])=>a<b)&&new Set(input.intervals.map(p=>p.join(','))).size===input.intervals.length,'Use distinct intervals with start < end.');
 if(id===1291)check(integer(input.low,10,1000000000)&&integer(input.high,input.low,1000000000),'Use 10 <= low <= high <= one billion.');
 if(id===1292)check(integer(input.threshold,0,1000000),'Use a nonnegative threshold at most one million.');
 if(id===1296)check(integer(input.k,1,input.nums.length),'k must be positive and no larger than the array.');
 if(id===1300)check(integer(input.target,0,1000000),'Use a nonnegative target at most one million.');
 if([1304,1374].includes(id))check(integer(input.n,1,100),'Use n from one through one hundred.');
 if(id===1306)check(input.arr.every(v=>v>=0)&&integer(input.start,0,input.arr.length-1),'Use nonnegative jumps and a valid start index.');
 if(id===1310)check(input.arr.every(v=>integer(v,0,1000000000))&&tuples(input.queries,2,1,80)&&input.queries.every(([l,r])=>integer(l,0,input.arr.length-1)&&integer(r,l,input.arr.length-1)),'Use nonnegative values and valid inclusive [left,right] ranges.');
 if(id===1313)check(input.nums.length%2===0&&input.nums.every(v=>v>=1)&&input.nums.filter((_,i)=>i%2===0).reduce((a,b)=>a+b,0)<=200,'Use positive frequency-value pairs with total expanded length at most 200.');
 if(id===1314)check(integer(input.k,0,100),'Use k from zero through one hundred.');
 if(id===1317)check(integer(input.n,2,1000),'Use n from two through one thousand for readable search.');
 if(id===1318)check([input.a,input.b,input.c].every(v=>integer(v,0,1000000000)),'Use nonnegative integers at most one billion.');
 if(id===1323)check(integer(input.num,1,999999999)&&/^[69]+$/.test(String(input.num)),'Use an integer containing only digits six and nine.');
 if(id===1328)check(input.palindrome===[...input.palindrome].reverse().join(''),'The input must already be a palindrome.');
 if(id===1337)check(input.mat.every(row=>row.every((v,i)=>!i||v<=row[i-1]))&&integer(input.k,1,input.mat.length),'Each row must have ones before zeros; k must fit the row count.');
 if(id===1342)check(integer(input.num,0,1000000000),'Use a nonnegative integer at most one billion.');
 if(id===1343)check(integer(input.k,1,input.arr.length)&&integer(input.threshold,0,10000),'Use a fitting positive window and a nonnegative bounded threshold.');
 if(id===1344)check(integer(input.hour,1,12)&&integer(input.minutes,0,59),'Use hour 1-12 and minutes 0-59.');
 if(id===1347)check(input.s.length===input.t.length,'The two strings must have equal lengths.');
 if(id===1351)check(input.grid.every((row,r)=>row.every((v,c)=>(!c||v<=row[c-1])&&(!r||v<=input.grid[r-1][c]))),'Rows and columns must both be nonincreasing.');
 if(id===1356)check(input.arr.every(v=>v>=0),'Use nonnegative integers.');
 if(id===1360)for(const date of [input.date1,input.date2]){check(typeof date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(date),'Use dates formatted YYYY-MM-DD.');const parsed=new Date(date+'T00:00:00Z');check(Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===date&&Number(date.slice(0,4))>=1971&&Number(date.slice(0,4))<=2100,'Use real dates from 1971 through 2100.');}
 if(id===1380)check(new Set(input.matrix.flat()).size===input.matrix.flat().length,'Use distinct matrix entries.');
 if(id===1385)check(integer(input.d,0,10000),'Use a nonnegative distance limit at most 10000.');
 if(id===1389)check(input.nums.length===input.index.length&&input.index.every((v,i)=>integer(v,0,i)),'Each insertion index must fit the target length at that step.');
 if(id===1399)check(integer(input.n,1,300),'Use n from one through three hundred for readable grouping.');
 if(id===1400)check(integer(input.k,1,10000),'Use a positive desired palindrome count.');
 return input;
}
