export const continuedSpecs={
1805:['word','Count distinct integers embedded in a mixed lowercase-and-digit string.','Read maximal digit runs and remove leading zeros. Compare normalized text rather than numeric conversion so arbitrarily long integers retain their exact identity.','scan to the next digit|consume its complete digit run|strip leading zeros, using zero for an all-zero run|insert normalized text into a set|return set size','O(n) expected character work; O(n) stored text.'],
1806:['n','Find the positive number of shuffle operations needed to restore the initial even-length permutation.','Follow the specified index mapping starting at index one. Its return period equals the order of this perfect-shuffle permutation.','position = 1; operations = 0|apply the even/odd index mapping|increment operations|repeat until position returns to one|return operations','O(n) period simulation time; O(1) state.'],
1807:['s knowledge','Replace bracketed keys by known values and unknown keys by question marks.','Build a lookup map and scan complete bracket pairs. Preserve ordinary text, replacing each entire pair once without rescanning the inserted value.','build key-to-value map|scan ordinary characters into output|at opening bracket, read through closing bracket|append mapped value or question mark|return completed string','O(input+output+knowledge) character work; O(knowledge+output) space.'],
1812:['coordinates','Determine whether a named chessboard square is white.','Files and ranks alternate colors independently. With a1 black, the parity of zero-based file plus zero-based rank determines the color.','convert file to zero-based index|convert rank to zero-based index|add both indices|test whether the sum is odd|return white-square boolean','O(1) time and state.'],
1813:['sentence1 sentence2','Decide whether inserting one contiguous block of words can make two sentences identical.','Match a common word prefix and then a nonoverlapping common suffix. The shorter sentence must be fully covered; unmatched longer words then form one middle block.','order sentences by word count|match equal words from the beginning|match equal words from the end without overlap|require prefixCount+suffixCount == shorterLength|return similarity','O(total words) time and split-word space.'],
1814:['nums','Count pairs satisfying nums[i]+reverse(nums[j]) = nums[j]+reverse(nums[i]).','Rearrange the equation to equal differences value minus reversed value. Count earlier occurrences of each difference to add pairs once.','counts = {}; answer = 0|for value:|    key = value-reverse(value)|    add prior count of key, then increment it|return count modulo 1000000007','O(n*digits) time; O(n) count space.'],
1816:['s k','Return exactly the first k words of a sentence.','Split at the defined single-space word boundaries and keep the first k whole words, preserving order.','split sentence into words|take the first k entries|preserve their order|join using one space|return truncated sentence','O(sentence length) time and word/output space.'],
1817:['logs k','Count users by their number of distinct active minutes.','Build a set of minutes per user so repeated logs in one minute do not inflate activity. Then count users in the matching minute-count bucket.','map user IDs to minute sets|insert every logged minute into its user set|allocate k zero buckets|increment bucket setSize-1 for each user|return activity histogram','O(logs+k) expected time; O(logs+k) space.'],
1818:['nums1 nums2','Minimize absolute sum difference by replacing at most one first-array entry with another value from that array.','For each partner value, binary search the closest available replacement in sorted nums1. Subtract the single greatest possible saving from the original total.','sort a copy of nums1|sum original absolute differences|for each partner, check lower-bound neighbors for closest replacement|retain greatest originalDifference-newDifference|return total-bestSaving modulo M','O(n log n) time; O(n) sorted-copy space.'],
1820:['grid','Maximize accepted invitations with no participant assigned more than once.','Use augmenting paths in a bipartite graph. When a desired partner is occupied, recursively reassign their current owner; a successful chain adds one new matched pair.','owner per partner = unassigned|for each inviting participant:|    search acceptable unvisited partners|    take a free partner or reroute its current owner|count successful augmentations and return matching size','O(boys*edges) time; O(boys+girls) search/matching space.'],
1822:['nums','Return the sign of the array product without multiplying its magnitudes.','A zero fixes the answer immediately. Otherwise only the parity of the negative-factor count changes the product sign.','sign = positive|for value:|    return zero if value is zero|    flip sign for a negative value|return sign','O(n) time; O(1) state.'],
1823:['n k','Find the final player after repeatedly eliminating every kth player in a circle.','Track the current position in the surviving list. Count the starting player as one, remove the kth, and continue at the same list index after removal.','circle = players 1..n; index = 0|while more than one player remains:|    index = (index+k-1) modulo remaining count|    remove that player; continue at successor|return surviving player','O(n^2) array-splice simulation time; O(n) space.'],
1824:['obstacles','Reach the road end from lane two using the fewest sideways jumps.','Maintain the best side-jump count for each lane. Invalidate the blocked lane before allowing transitions among currently open lanes at the same position.','lane costs = [1,0,1]|for each forward position:|    mark blocked lane unreachable|    minimize every open lane using bestOpenCost+1|return cheapest ending lane','O(n) time; O(1) three-lane state.'],
1827:['nums','Make the array strictly increasing with the fewest single-value increments.','At each position keep the original value if already large enough; otherwise raise it to exactly previous repaired value plus one. Extra increments never help later positions.','result = []; operations = 0|scan values left to right|required = max(original,previous+1)|add required-original and append required|return operation count','O(n) time; O(n) displayed result space.'],
1828:['points queries','Count points inside or on each query circle.','For each point compare squared coordinate distance with squared radius. Independent queries count boundary points and repeated point positions as given.','for each center and radius:|    count = 0|    compute squared distance for every point|    include when distanceSquared <= radiusSquared|return counts in query order','O(points*queries) time; O(queries) output space.'],
1829:['nums maximumBit','Choose a bounded integer maximizing XOR for each shrinking-array query.','The best result is an all-one value within the allowed bit width. XOR the current array total with that mask, then remove the final value from the total using XOR again.','xor = XOR of all values; mask = 2^maximumBit-1|while values remain:|    append mask XOR xor|    remove final value from xor|return query answers','O(n) time; O(n) output space.'],
1832:['sentence','Check whether a lowercase sentence contains every English alphabet letter.','Track distinct letters; repeated occurrences do not increase coverage. Exactly twenty-six distinct lowercase letters is sufficient.','seen = empty set|for character:|    insert character|    track missing alphabet letters for the story|return seen size == 26','O(n) time; O(1) alphabet state.'],
1833:['costs coins','Buy the greatest number of ice cream bars within the coin budget.','Every purchase increases the answer equally, so choose cheaper bars before expensive ones. Stop at the first unaffordable sorted cost.','sort costs ascending|for price:|    stop if price exceeds remaining coins|    pay price and increment purchases|return purchases','O(n log n) time; O(n) sorted-copy space.'],
1834:['tasks','Return the order in which a single-threaded CPU processes arriving tasks.','Maintain ready tasks separately from future arrivals. Select shortest duration then smallest original index; when none are ready, jump time to the next arrival.','sort tasks by arrival, retaining original indices|when idle, advance time to next arrival|add every task available at current time|select shortest ready task, break ties by index, and run to completion|return processing order','O(n^2 log n) direct sorted-ready-list bound; O(n) state.'],
};

export function validateContinued(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
 const vector=(a,min=1,max=100,low=-10000,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
 const text=(s,regex=/^[a-z]+$/,max=160)=>typeof s==='string'&&s.length>=1&&s.length<=max&&regex.test(s);
 const sentence=s=>text(s,/^[A-Za-z]+(?: [A-Za-z]+)*$/);
 for(const key of ['nums','nums1','nums2','obstacles','costs'])if(key in input)check(vector(input[key]),`${key}: use 1-100 bounded integers.`);
 if(id===1805)check(text(input.word,/^[a-z0-9]+$/),'Use nonempty lowercase alphanumeric text.');
 if(id===1806)check(integer(input.n,2,100)&&input.n%2===0,'Use an even permutation length from two through one hundred.');
 if(id===1807){check(text(input.s,/^(?:[a-z]|\([a-z]+\))+$/)&&Array.isArray(input.knowledge)&&input.knowledge.length<=60&&input.knowledge.every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>text(v,/^[a-z]+$/,30))),'Use lowercase text with complete unnested bracket keys and [key,value] knowledge pairs.');check(new Set(input.knowledge.map(p=>p[0])).size===input.knowledge.length,'Knowledge keys must be distinct.');}
 if(id===1812)check(typeof input.coordinates==='string'&&/^[a-h][1-8]$/.test(input.coordinates),'Use a chess coordinate from a1 through h8.');
 if(id===1813)check(sentence(input.sentence1)&&sentence(input.sentence2),'Use alphabetic words separated by single spaces.');
 if(id===1814)check(input.nums.every(v=>v>=0),'Use nonnegative integer values.');
 if(id===1816)check(sentence(input.s)&&integer(input.k,1,input.s.split(' ').length),'Use a single-space sentence and k within its word count.');
 if(id===1817){check(Array.isArray(input.logs)&&input.logs.length>=1&&input.logs.length<=100&&input.logs.every(p=>vector(p,2,2,0))&&integer(input.k,1,100),'Use nonnegative [user,minute] logs and positive histogram length.');const map=new Map();for(const[u,m]of input.logs){if(!map.has(u))map.set(u,new Set());map.get(u).add(m);}check([...map.values()].every(s=>s.size<=input.k),'k must cover every user distinct active-minute count.');}
 if(id===1818)check(input.nums1.length===input.nums2.length&&[...input.nums1,...input.nums2].every(v=>v>0),'Use equally sized positive arrays.');
 if(id===1820){const g=input.grid;check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>vector(row,1,8,0,1)&&row.length===g[0].length),'Use a rectangular binary invitation grid at most 8 by 8.');}
 if(id===1823)check(integer(input.n,1,100)&&integer(input.k,1,10000),'Use 1-100 players and a positive count interval.');
 if(id===1824)check(input.obstacles.length>=2&&input.obstacles.every(v=>v>=0&&v<=3)&&input.obstacles[0]===0&&input.obstacles.at(-1)===0,'Use lane numbers zero through three with clear starting and ending positions.');
 if(id===1827)check(input.nums.every(v=>v>=1),'Use positive original values.');
 if(id===1828)check(Array.isArray(input.points)&&input.points.length>=1&&input.points.length<=40&&input.points.every(p=>vector(p,2,2,0,1000))&&Array.isArray(input.queries)&&input.queries.length>=1&&input.queries.length<=20&&input.queries.every(q=>vector(q,3,3,0,1000)&&q[2]>=1),'Use nonnegative coordinate pairs and [centerX,centerY,positive radius] queries.');
 if(id===1829)check(integer(input.maximumBit,1,20)&&input.nums.every((v,i,a)=>v>=0&&v<2**input.maximumBit&&(!i||v>=a[i-1])),'Use a nondecreasing nonnegative array within the specified 1-20 bit width.');
 if(id===1832)check(text(input.sentence),'Use nonempty lowercase alphabetic text.');
 if(id===1833)check(input.costs.every(v=>v>0)&&integer(input.coins,0,1000000),'Use positive costs and a nonnegative coin budget.');
 if(id===1834)check(Array.isArray(input.tasks)&&input.tasks.length>=1&&input.tasks.length<=60&&input.tasks.every(t=>vector(t,2,2,1,100000)),'Use 1-60 tasks as positive [enqueue time,processing time] pairs.');
 return input;
}
