export const rangeSpecs={
1835:['arr1 arr2','Compute the XOR of every pairwise bitwise AND between two arrays.','Bitwise AND distributes over XOR. Reduce each array independently, then AND the two totals instead of enumerating the cross product.','firstXor = secondXor = 0|scan both arrays independently|XOR each value into its array accumulator|combine both accumulators with bitwise AND|return combined value','O(n+m) time; O(1) state.'],
1837:['n k','Sum the digits of n in base k without converting to decimal text.','Repeated remainder extracts the least significant base-k digit. Integer division removes that digit so the remaining positions can be processed.','answer = 0|while digits remain|digit = n modulo k|add digit and replace n by floor(n/k)|return digit sum','O(log_k n) time; O(1) state.'],
1838:['nums k','Maximize an element frequency using at most k increments.','In sorted order, raise a contiguous window to its greatest value. The exact cost is target times count minus the window sum; shrink whenever that cost exceeds the budget.','sort values; left = sum = best = 0|extend the right endpoint|compare target*width-sum with k|shrink excess cost and retain greatest feasible width|return maximum frequency','O(n log n) time; O(n) sorted-copy space.'],
1839:['word','Find the longest substring containing all five vowels in nondecreasing order.','A descending vowel starts a new run. In a nondecreasing run count distinct vowel groups; five groups means all required vowels appear.','start = groups = best = 0|scan vowels left to right|restart on a decrease, count groups on an increase|maximize run length only when all five groups occur|return greatest beautiful length','O(n) time; O(1) state.'],
1844:['s','Replace each digit with the preceding letter shifted forward by its value.','Even positions hold original letters and odd positions hold offsets. Each replacement depends only on the immediately preceding letter.','copy characters|visit odd positions|read digit offset and preceding letter|write the shifted character|return completed string','O(n) time and output space.'],
1845:['n operations','Always reserve the smallest available seat and support returning seats.','Keep the set of currently free seat numbers. A reservation removes its minimum; an unreserve adds that exact held seat back.','initialize all seats as free|for reserve or unreserve operation|reserve selects the minimum free seat|remove selected seat or restore returned seat|return reservation results','O(n*operations) direct minimum-search time; O(n) availability state.'],
1846:['arr','Maximize the final value after decreases and rearrangement under adjacent-gap constraints.','Sort and greedily make each position as large as permitted: no greater than its original value or the preceding repaired value plus one. The first position becomes one.','sort values; previous = 0|for original value|allowed = min(original,previous+1)|append allowed and make it the new previous|return last repaired value','O(n log n) time; O(n) sorted/output space.'],
1848:['nums target start','Find the shortest index distance from start to an occurrence of target.','Inspect target occurrences and compare absolute index differences. Values that differ from target cannot contribute.','best = infinity|scan array indices|consider only values equal to target|minimize abs(index-start)|return best distance','O(n) time; O(1) state.'],
1849:['s','Split a digit string into at least two descending consecutive numeric values.','Choose a first chunk and recursively try following chunks equal to previous minus one. Leading zeros are allowed; arbitrary-precision integers preserve long chunk values.','search from position zero with no previous value|extend the next candidate chunk|require it to equal previous-1 after the first chunk|recurse on matching chunks; require at least two parts at the end|return whether a valid split exists','Exponential worst-case search time; O(n) recursion depth plus big-integer state.'],
1851:['intervals queries','Find the shortest inclusive interval containing each query point.','Sort queries and activate intervals when their left endpoint is reached. Remove expired intervals, then select the shortest remaining interval and store the answer in original query order.','sort intervals and indexed queries|for each query activate intervals starting by it|discard intervals ending before it|choose smallest inclusive interval length or -1|return answers in original order','O(q*n log n) direct active-list sorting bound; O(n+q) space.'],
1852:['nums k','Count distinct values in each fixed-length subarray.','Maintain occurrence counts for the sliding window. Delete a key when its last copy leaves so the map size equals the number of distinct values.','counts = {}; answers = []|add each arriving value|remove the departing value once window exceeds k|record map size for every full window|return counts in window order','O(n) expected time; O(k) count state plus output.'],
1854:['logs','Return the earliest year with maximum living population.','Treat life intervals as birth-inclusive and death-exclusive. Apply combined yearly deltas in increasing year order; update the best year only for a strictly larger population.','record +1 at births and -1 at deaths|scan sorted event years|apply the current year net change|replace best only on a greater population|return earliest maximum year','O(n log n) time; O(n) event space.'],
1855:['nums1 nums2','Maximize j-i subject to i <= j and nums1[i] <= nums2[j].','Both arrays are nonincreasing. A valid pair can extend its right index; an invalid value comparison must advance the left index because later right values cannot be larger.','i = j = best = 0|while both indices remain valid|ensure j >= i and compare values|advance j on success, otherwise i; retain greatest distance|return best distance','O(n+m) time; O(1) state.'],
1856:['nums','Maximize subarray sum times its minimum, reducing only the final maximum modulo the required prime.','A monotonic stack finds each minimum candidate widest eligible interval. Positive values make the widest interval best for that fixed minimum, and prefix sums supply its total.','build prefix sums and increasing stack|read each value and a final smaller sentinel|pop minima whose interval ends here|compute interval sum*minimum and retain maximum before modulo|return maximum modulo 1000000007','O(n) time; O(n) stack/prefix space.'],
1857:['colors edges','Find the greatest count of one color on a directed path, or -1 if a cycle exists.','Topological traversal ensures all incoming path counts are available. Propagate one best count per color to successors; vertices left unprocessed reveal a cycle.','build adjacency, indegrees, and color-count DP|process zero-indegree vertices|propagate predecessor counts plus successor color|release ready successors and retain best color count|return -1 for a cycle, otherwise best count','O(26*(vertices+edges)) time; O(26*vertices+edges) space.'],
1858:['words','Find the longest word whose every nonempty prefix is also present.','Check each prefix against the dictionary set. Select only complete prefix chains, breaking equal-length ties lexicographically.','put words in a set|for each word|check every shorter nonempty prefix|retain longest valid word, then lexicographically smallest|return best word or empty string','O(sum of squared word lengths) copied-prefix work; O(total word characters) space.'],
1859:['s','Restore a shuffled sentence using each word trailing position digit.','The final digit identifies the original one-based slot. Remove it and place the word directly, independent of input order.','split shuffled tokens and allocate output slots|for each token|read its final position digit|place the remaining word in that slot|return words joined by single spaces','O(sentence length) time and output space.'],
1860:['memory1 memory2','Simulate increasing memory requests until neither bank can satisfy the next request.','At second t allocate t units from the bank with more free memory, breaking ties toward bank one. Report the first failing second and both remaining capacities.','second = 1|while some bank can satisfy second|choose larger free bank, preferring first on equality|subtract request and increment second|return failing second and remaining capacities','O(sqrt(memory1+memory2)) steps; O(1) state.'],
1861:['box','Rotate the box clockwise and let stones fall against obstacles and the bottom.','Before rotation, gravity corresponds to rightward movement within each row. Pack stones against each compartment right boundary, then rotate the settled grid.','copy box|scan each row right to left|reset free position at obstacles, move stones into next free slot|rotate settled coordinates clockwise|return rotated box','O(rows*columns) time and output space.'],
1863:['nums','Sum XOR totals over every subset, including the empty subset.','Each bit present in any input value appears in exactly half of all subset XORs. OR identifies contributing bits; multiply that value by half the subset count.','presentBits = 0|for each value|OR its bits into presentBits|multiply presentBits by 2^(length-1)|return subset XOR total','O(n) time; O(1) state.'],
1864:['s','Find the fewest arbitrary-position swaps making a binary string alternate.','Alternation requires zero and one counts differing by at most one. For each count-compatible target, a swap repairs two mismatched positions.','count zeros and ones|reject count difference greater than one|count mismatches to each compatible alternating target|divide mismatches by two and keep minimum|return swaps or -1','O(n) time; O(1) state.'],
1865:['nums1 nums2 operations','Update second-array values and count cross-array index pairs summing to a query total.','Maintain second-array frequencies through updates. Each count query adds the complement frequency for every first-array position, preserving multiplicity.','build second-array frequency map|for each add or count operation|add removes one old occurrence and inserts its updated value|count sums complementary frequencies for all first positions|return count-query answers','O(second length + updates + queries*first length) expected time; O(second length) state.'],
1866:['n k','Count stick permutations with exactly k visible sticks from the left.','Insert the shortest stick into an order of the others. At the front it adds one visible stick; each other insertion position leaves visibility unchanged.','dp[0] = 1 for zero sticks|grow stick count|next[v] = dp[v-1]+(size-1)*dp[v]|apply modulo and replace previous row|return dp[k]','O(n*k) time; O(k) DP space.'],
1868:['encoded1 encoded2','Multiply two run-length encoded arrays and keep the result maximally compressed.','Consume the shorter remaining run from both inputs. Equal adjacent result products must merge even when an input run boundary caused the split.','initialize run pointers and remaining lengths|while encoded inputs remain|consume min(remaining1,remaining2) at the product value|merge equal output runs and advance exhausted input runs|return compressed product','O(runs1+runs2) time and output space.'],
1869:['s','Decide whether the longest one run is strictly longer than the longest zero run.','Track the active run length and separate maximums for each bit. Equality is a negative answer because the comparison is strict.','run = longestZero = longestOne = 0|scan bits|extend equal run or restart at one|update the maximum for the current bit|return longestOne > longestZero','O(n) time; O(1) state.'],
};

export function rangeCodeStage(id, state, phase) {
 if (phase === 'start') return undefined;
 if (id === 1835) return state.metrics?.secondXor === undefined ? 'first' : 'second';
 if (id === 1845) return state.metrics.action;
 if (id === 1849) return 'search';
 if (id === 1855) return phase === 'update' ? 'extend' : 'shrink';
 if (id === 1857) return phase === 'update' ? 'update' : 'cycle';
 if (id === 1861) return state.metrics ? 'settle' : 'rotate';
 if (id === 1864) return phase === 'update' ? 'compare' : 'impossible';
 if (id === 1865) return state.metrics.added === undefined ? 'count' : 'add';
 return 'update';
}
export const rangePseudocodeStages={1835:{first:3,second:3},1849:{search:3},1861:{settle:3,rotate:4}};

export function validateRange(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const int=(v,lo=0,hi=10000)=>Number.isSafeInteger(v)&&v>=lo&&v<=hi;
 const vec=(a,min=1,max=80,lo=0,hi=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>int(v,lo,hi));
 const text=(s,re=/^[a-z]+$/,max=100)=>typeof s==='string'&&s.length>=1&&s.length<=max&&re.test(s);
 for(const key of ['nums','nums1','nums2','arr','arr1','arr2','queries'])if(key in input)check(vec(input[key]),`${key}: use 1-80 nonnegative bounded integers.`);
 if(id===1837)check(int(input.n,1,1000000)&&int(input.k,2,36),'Use a positive number at most one million and a base from 2 through 36.');
 if(id===1838)check(input.nums.every(v=>v>0)&&int(input.k,0,1000000),'Use positive values and a nonnegative increment budget.');
 if(id===1839)check(text(input.word,/^[aeiou]+$/),'Use 1-100 lowercase vowels.');
 if(id===1844)check(text(input.s,/^(?:[a-z][0-9])*[a-z]?$/)&&[...input.s].every((c,i)=>i%2===0||input.s.charCodeAt(i-1)+Number(c)<=122),'Alternate lowercase letters and digit shifts that do not pass z.');
 if(id===1845){check(int(input.n,1,60)&&Array.isArray(input.operations)&&input.operations.length>=1&&input.operations.length<=80,'Use 1-60 seats and 1-80 operations.');const free=new Set(Array.from({length:input.n},(_,i)=>i+1));for(const op of input.operations){check(Array.isArray(op),'Each operation must be an array.');if(op[0]==='reserve'){check(op.length===1&&free.size>0,'Reserve requires an available seat.');free.delete(Math.min(...free));}else{check(op[0]==='unreserve'&&op.length===2&&int(op[1],1,input.n)&&!free.has(op[1]),'Unreserve requires a currently held seat.');free.add(op[1]);}}}
 if(id===1846)check(input.arr.every(v=>v>0),'Use positive values.');
 if(id===1848)check(int(input.start,0,input.nums.length-1)&&int(input.target)&&input.nums.includes(input.target),'Use a valid start index and a target present in nums.');
 if(id===1849)check(text(input.s,/^[0-9]+$/,14),'Use 1-14 decimal digits for inspectable recursive search.');
 if(id===1851)check(Array.isArray(input.intervals)&&input.intervals.length>=1&&input.intervals.length<=50&&input.intervals.every(p=>vec(p,2,2)&&p[0]<=p[1]),'Use valid inclusive [left,right] intervals.');
 if(id===1852)check(int(input.k,1,input.nums.length),'Use k between one and array length.');
 if(id===1854)check(Array.isArray(input.logs)&&input.logs.length>=1&&input.logs.length<=60&&input.logs.every(p=>vec(p,2,2,1950,2050)&&p[0]<p[1]),'Use [birth,death] pairs from 1950-2050 with birth before death.');
 if(id===1855)check([input.nums1,input.nums2].every(a=>a.every((v,i)=>v>0&&(!i||v<=a[i-1]))),'Both arrays must be positive and nonincreasing.');
 if(id===1856)check(input.nums.every(v=>v>0),'Use positive values so expanding a fixed-minimum interval cannot lower its sum.');
 if(id===1857)check(text(input.colors,/^[a-z]+$/,30)&&Array.isArray(input.edges)&&input.edges.length<=100&&input.edges.every(p=>vec(p,2,2,0,input.colors.length-1)),'Use 1-30 color letters and valid zero-based directed edges; cycles are allowed inputs.');
 if(id===1858)check(Array.isArray(input.words)&&input.words.length>=1&&input.words.length<=30&&input.words.every(w=>text(w,/^[a-z]+$/,15)),'Use 1-30 lowercase words of at most 15 letters.');
 if(id===1859){check(text(input.s,/^[A-Za-z]+[1-9](?: [A-Za-z]+[1-9])*$/,160),'Use alphabetic words followed by position digits, separated by single spaces.');const tokens=input.s.split(' '),positions=tokens.map(t=>Number(t.at(-1)));check(tokens.length<=9&&new Set(positions).size===tokens.length&&positions.every(p=>p<=tokens.length),'Positions must be a permutation of one through the word count.');}
 if(id===1860)check(int(input.memory1,0,10000)&&int(input.memory2,0,10000),'Use nonnegative bank capacities at most ten thousand.');
 if(id===1861){const g=input.box;check(Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>Array.isArray(row)&&row.length>=1&&row.length<=8&&row.length===g[0].length&&row.every(c=>['#','*','.'].includes(c))),'Use a rectangular box up to 8 by 8 with stones #, obstacles *, and empty cells .');}
 if(id===1863)check(input.nums.length<=20,'Use at most twenty values for exactly represented subset totals.');
 if([1864,1869].includes(id))check(text(input.s,/^[01]+$/),'Use a nonempty binary string.');
 if(id===1865){check(input.nums1.every(v=>v>0)&&input.nums2.every(v=>v>0)&&Array.isArray(input.operations)&&input.operations.length>=1&&input.operations.length<=60,'Use positive arrays and 1-60 operations.');for(const op of input.operations)check(Array.isArray(op)&&(op[0]==='count'&&op.length===2&&int(op[1],1,1000000)||op[0]==='add'&&op.length===3&&int(op[1],0,input.nums2.length-1)&&int(op[2],1,10000)),'Use [count,total] or [add,index,positive increment].');}
 if(id===1866)check(int(input.n,1,80)&&int(input.k,1,input.n),'Use 1 <= k <= n <= 80.');
 if(id===1868){for(const key of ['encoded1','encoded2'])check(Array.isArray(input[key])&&input[key].length>=1&&input[key].length<=30&&input[key].every(p=>vec(p,2,2,1,1000)),`${key}: use positive [value,length] runs.`);check(input.encoded1.reduce((s,p)=>s+p[1],0)===input.encoded2.reduce((s,p)=>s+p[1],0),'Both expanded arrays must have the same length.');}
 return input;
}
