export const graphGridSpecs={
1901:['mat','Find any cell strictly greater than its orthogonal neighbors.','Binary search columns. The maximum of the current column already dominates vertical neighbors; a greater horizontal neighbor determines which half still contains a peak.','search column interval|find the maximum row in the middle column|compare its left and right neighbors|return a peak or continue toward a greater neighbor|return peak coordinates','O(rows*log columns) time; O(1) state.'],
1914:['grid k','Rotate every rectangular ring counterclockwise by k positions.','List ring coordinates counterclockwise. Reduce k modulo ring length and write each original value to its shifted destination in a separate result grid.','copy result grid|enumerate each layer counterclockwise|reduce k modulo ring length|move each original value to its shifted ring position|return rotated grid','O(rows*columns) time and copied-grid space.'],
1916:['prevRoom','Count room-building orders that place every parent before its children.','Compute subtree sizes and order counts bottom-up. Child orders interleave according to a multinomial coefficient while preserving their internal parent constraints.','build child lists and factorials|visit rooms after all descendants|combine child counts and factorial interleaving factor|store subtree size and count modulo 1000000007|return root order count','O(n log modulus) reference time; O(n) state.'],
1926:['maze entrance','Find the shortest path to an exit other than the entrance.','Breadth-first search discovers cells by increasing distance. Open boundary cells qualify except the starting cell, even if the entrance itself is on the boundary.','enqueue entrance at distance zero|take the next unvisited-distance cell|check boundary status while excluding entrance|enqueue unvisited open neighbors one step farther|return exit distance or -1','O(rows*columns) time and traversal space.'],
1971:['n edges source destination','Determine whether an undirected path connects source and destination.','Traverse reachable vertices and mark them when queued. Repeated edges of a cycle cannot cause repeated exploration, and a vertex reaches itself without traversing an edge.','build undirected adjacency lists|enqueue source and mark it reachable|visit queued vertices and check destination|enqueue each unseen neighbor|return destination reachability','O(vertices+edges) time and graph/traversal space.'],
1976:['n roads','Count shortest routes from vertex zero to vertex n-1.','Dijkstra tracks both shortest distance and number of ways. Better distances replace counts; equal distances add counts. Strictly positive weights keep settled predecessor counts final.','distance[0] = 0; ways[0] = 1|choose the nearest unsettled vertex|inspect each weighted neighbor|replace on shorter distance, add ways on equal distance|return destination ways modulo 1000000007','O(n^2+edges) direct-selection Dijkstra time; O(n+edges) space.'],
};
export function validateGraphGrid(id,input){
 const check=(ok,message)=>{if(!ok)throw new Error(message);};
 const int=(v,lo=0,hi=10000)=>Number.isSafeInteger(v)&&v>=lo&&v<=hi;
 const grid=(g,test)=>Array.isArray(g)&&g.length>=1&&g.length<=8&&g.every(row=>Array.isArray(row)&&row.length>=1&&row.length<=8&&row.length===g[0].length&&row.every(test));
 if(id===1901){check(grid(input.mat,v=>int(v,1)),'Use a positive integer matrix up to eight by eight.');check(input.mat.every((row,r)=>row.every((v,c)=>(!r||v!==input.mat[r-1][c])&&(!c||v!==row[c-1]))),'Orthogonally adjacent values must differ.');}
 if(id===1914)check(grid(input.grid,v=>int(v,1))&&input.grid.length%2===0&&input.grid[0].length%2===0&&int(input.k,1,1000000000),'Use an even-by-even positive matrix and positive rotation count.');
 if(id===1916){const parents=input.prevRoom;check(Array.isArray(parents)&&parents.length>=2&&parents.length<=40&&parents[0]===-1&&parents.slice(1).every((p,i)=>int(p,0,parents.length-1)&&p!==i+1),'Use 2-40 room parents with root parent -1 and valid other parent indices.');const children=Array.from({length:parents.length},()=>[]),queue=[0],seen=new Set([0]);for(let i=1;i<parents.length;i++)children[parents[i]].push(i);for(let i=0;i<queue.length;i++)for(const child of children[queue[i]])if(!seen.has(child)){seen.add(child);queue.push(child);}check(seen.size===parents.length,'Parents must describe one tree rooted at room zero.');}
 if(id===1926)check(grid(input.maze,c=>c==='.'||c==='+')&&Array.isArray(input.entrance)&&input.entrance.length===2&&int(input.entrance[0],0,input.maze.length-1)&&int(input.entrance[1],0,input.maze[0].length-1)&&input.maze[input.entrance[0]][input.entrance[1]]==='.', 'Use a maze of . and + cells and an open in-bounds entrance.');
 if([1971,1976].includes(id)){check(int(input.n,1,30),'Use 1-30 vertices.');const edges=id===1971?input.edges:input.roads;check(Array.isArray(edges)&&edges.length<=100&&edges.every(e=>Array.isArray(e)&&e.length===(id===1971?2:3)&&int(e[0],0,input.n-1)&&int(e[1],0,input.n-1)&&e[0]!==e[1]&&(id===1971||int(e[2],1,10000))),'Use valid edges, with strictly positive weights for roads.');check(new Set(edges.map(([a,b])=>[Math.min(a,b),Math.max(a,b)].join(','))).size===edges.length,'Do not repeat undirected edges.');if(id===1971)check(int(input.source,0,input.n-1)&&int(input.destination,0,input.n-1),'Use valid source and destination indices.');}
 return input;
}
