export const nextSpecs = {
1006:['n','Evaluate descending factorial terms with cycling multiply, divide, add, and subtract operations.','Preserve multiplication and division precedence inside signed terms. Sum terms only after those operations have been resolved.','stack = [n]|for next descending value:|    select operation by its position modulo four|    multiply/divide current term or append signed term|return sum(stack)','O(n) time and space.'],
1007:['tops bottoms','Find the fewest domino rotations that make either row uniform.','The target must be on the first domino. For each candidate, every later domino must contain it; count rotations toward each row separately.','candidates = distinct values on first domino|for target, scan all dominoes:|    reject a domino with neither side equal to target|    count top and bottom mismatches for feasible targets|return least rotation count, or -1','O(n) time; O(1) auxiliary state.'],
1009:['n','Complement every digit of the binary representation without introducing leading bits.','The written width matters: complement only significant digits, while zero is represented by one zero digit.','bits = binary representation of n|for each written bit:|    distinguish zero from one|    append one minus that bit|return integer represented by complemented bits','O(log(n+1)) time and representation space.'],
1010:['time','Count pairs of distinct songs whose total duration is divisible by sixty.','A remainder r needs (60-r) modulo 60. Count earlier partners before adding the current song, including the special zero and thirty buckets.','counts = sixty zeros; pairs = 0|for duration:|    find its remainder and complementary remainder|    add earlier partners, then record current remainder|return pairs','O(n) time; O(60) auxiliary state.'],
1011:['weights days','Find the least ship capacity that delivers ordered packages within the deadline.','Feasibility is monotone: a capacity that works makes every larger capacity work. Greedy day packing tests one candidate while binary search narrows the capacity interval.','low = maximum weight; high = total weight|while low < high, try midpoint capacity:|    greedily pack ordered weights and count days|    lower high if feasible; otherwise raise low past midpoint|return low','O(n log(sum(weights))) time; O(n) temporary assignment space.'],
1013:['arr','Decide whether two cuts create three nonempty parts with equal sums.','The total fixes each target sum. Close two matching prefixes as early as possible and leave a nonempty suffix; its sum must then be the same target.','reject total not divisible by three|scan through the penultimate element:|    accumulate toward total/3|    close a part on equality; succeed after two parts|return false if two cuts were not found','O(n) time; O(1) state.'],
1014:['values','Maximize the values of two sightseeing spots minus their distance.','Separate the score into values[i]+i and values[j]-j. Keep the best strictly earlier left contribution and evaluate before inserting the right endpoint.','left = values[0]; best = negative infinity|for right endpoint j from one:|    score = left + values[j]-j|    maximize best, then update left with values[j]+j|return best','O(n) time; O(1) state.'],
1015:['k','Find the shortest all-ones decimal number divisible by k, or report none.','Appending a one transforms the remainder without storing a huge integer. Repeating a nonzero remainder proves a cycle that will never reach zero.','remainder = 0; seen = empty set|for lengths one through k:|    remainder = (10*remainder+1) modulo k|    return length on zero; reject repeated remainder|return -1','O(k) time and remainder-set space.'],
1017:['n','Represent a nonnegative integer using base negative two.','Choose a remainder of zero or one, subtract it, then divide by negative two. The quotient may change sign, but output digits stay valid.','remaining = n; reversedDigits = []|repeat at least once:|    choose normalized parity bit in {0,1}|    append bit; remaining = (remaining-bit)/-2|return digits in reverse order','O(log(n+1)) time and digit space.'],
1018:['nums','Report which binary prefixes are divisible by five.','The full prefix may exceed integer precision. Its remainder alone is sufficient because appending a bit doubles the value and adds that bit.','remainder = 0; answers = []|for bit:|    compute (2*remainder+bit) modulo five|    append whether remainder is zero|return answers','O(n) time and output space.'],
1021:['s','Remove the outermost pair from each primitive balanced-parentheses section.','Depth identifies primitive boundaries. An opener at depth zero and a closer returning to zero are outer brackets; retain the brackets inside them.','depth = 0; output = []|for bracket:|    reduce depth before handling a closer|    retain at positive depth; increase depth after an opener|return joined output','O(n) time and output space.'],
1023:['queries pattern','Decide which queries can be formed by inserting lowercase letters into a pattern.','Consume pattern characters in order. Unmatched lowercase letters may be inserted, but any unmatched uppercase letter invalidates the query.','answers = []|for query, reset pattern position:|    match next pattern character or skip a lowercase character|    reject unmatched capitals; require the entire pattern|return answers','O(total query characters) time; O(number of queries) output space.'],
1025:['n','Decide whether the first player can force a win in the divisor subtraction game.','A state is winning when one legal divisor leads to a losing opponent state. Build smaller answers before using them to explain each choice.','wins = false for every state through n|for value from two through n:|    inspect proper positive divisors|    mark winning if subtracting a divisor leaves a losing state|return wins[n]','O(n^2) time in this explicit game-state DP; O(n) space.'],
1029:['costs','Send exactly half the people to each city at minimum total cost.','Compare each person by their relative A-versus-B cost, not their cheapest absolute cost. Give A seats to the smallest differences.','rank people by costA-costB|for each ranked person:|    choose A for the first half, otherwise B|    add that person city cost|return total','O(n log n) time; O(n) ranking space.'],
1030:['rows cols rCenter cCenter','List every matrix cell in nondecreasing distance from a chosen center.','Manhattan distance is the sum of row and column offsets. Sorting by it groups equal-distance rings; tie order is unrestricted.','enumerate all valid cells|compute Manhattan distance to center|sort by distance, then coordinates for stable playback|append cells in that order|return ordered coordinates','O(rc log(rc)) time; O(rc) space.'],
1037:['points','Determine whether three points form a nondegenerate triangle.','Subtract one point to get two direction vectors. A zero cross product means collinearity, including repeated points, without dividing by slope.','read three points|form AB and AC vectors|compute AB.x*AC.y - AB.y*AC.x|inspect whether the signed area is zero|return cross product != 0','O(1) time and space.'],
1041:['instructions','Decide whether indefinitely repeating the robot program stays bounded.','After one cycle, return to the origin or face a different direction to remain bounded. A changed heading makes displacement cancel over later cycles.','position = origin; heading = north|for instruction:|    distinguish forward motion from left/right rotation|    update coordinates or heading|return at origin or heading is not north','O(n) time; O(1) state.'],
1046:['stones','Find the remaining weight after repeatedly smashing the two heaviest stones.','Equal weights cancel. Unequal weights leave their difference, which must compete with all remaining stones at the next step.','copy stones|while more than one stone remains:|    sort and remove the two largest|    put back their difference if nonzero|return remaining stone, or zero','O(n^2 log n) time with repeated sorting; O(n) working space.'],
1051:['heights','Count positions whose height differs from the sorted lineup.','Compare against a sorted copy so original positions stay visible. The answer measures mismatched positions, not the number of exchanges.','expected = sorted copy of heights|for index in original lineup:|    compare original and expected height|    count unequal positions|return mismatch count','O(n log n) time; O(n) copied-array space.'],
1052:['customers grumpy minutes','Maximize satisfied customers using one contiguous calm interval.','Count naturally satisfied customers once. Slide a window over only otherwise-lost customers and add the best recoverable amount to that baseline.','baseline = customers at non-grumpy times|slide a window of at most minutes:|    add entering grumpy customers; remove leaving ones|    maximize recovered customers|return baseline + best recovery','O(n) time; O(1) auxiliary state.'],
};

export function validateNext(id,input) {
  const check=(ok,message)=>{if(!ok)throw new Error(message);};
  const integer=(v,min=0,max=10000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
  const vector=(a,min=1,max=80,low=0,high=10000)=>Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(v=>integer(v,low,high));
  const text=(s,pattern)=>typeof s==='string'&&s.length>=1&&s.length<=120&&pattern.test(s);
  if([1006,1009,1017,1025].includes(id))check(integer(input.n,[1006,1025].includes(id)?1:0,id===1006?80:id===1025?60:1000000000),'Use an integer n within the visual limit: 1-80 for clumsy factorial, 1-60 for divisor game, or 0-1000000000 for binary representations.');
  if(id===1007)check(vector(input.tops,2,80,1,6)&&vector(input.bottoms,2,80,1,6)&&input.tops.length===input.bottoms.length,'Use equally sized top and bottom arrays with 2-80 values from 1 to 6.');
  if(id===1010)check(vector(input.time,1,80,1,500),'Use 1-80 positive durations no greater than 500.');
  if(id===1011)check(vector(input.weights,1,60,1,500)&&integer(input.days,1,input.weights.length),'Use 1-60 positive weights at most 500 and days from 1 through the package count.');
  if(id===1013)check(vector(input.arr,3,80,-10000),'Use 3-80 bounded signed integers.');
  if(id===1014)check(vector(input.values,2,80,1,1000),'Use 2-80 positive sightseeing values at most 1000.');
  if(id===1015)check(integer(input.k,1,150),'Use a divisor k from 1 through 150 for inspectable remainder playback.');
  if(id===1018)check(vector(input.nums,1,120,0,1),'Use 1-120 binary digits.');
  if(id===1021){check(text(input.s,/^[()]+$/),'Use 1-120 balanced parentheses.');let depth=0;for(const c of input.s){depth+=c==='('?1:-1;check(depth>=0,'A closing bracket cannot precede its opener.');}check(depth===0,'All parentheses must balance.');}
  if(id===1023)check(Array.isArray(input.queries)&&input.queries.length>=1&&input.queries.length<=30&&input.queries.every(s=>text(s,/^[A-Za-z]+$/))&&text(input.pattern,/^[A-Za-z]+$/),'Use 1-30 alphabetic queries and an alphabetic pattern, each at most 120 characters.');
  if(id===1029)check(Array.isArray(input.costs)&&input.costs.length>=2&&input.costs.length<=40&&input.costs.length%2===0&&input.costs.every(p=>vector(p,2,2,1,10000)),'Use an even number of people (2-40), each with two positive city costs.');
  if(id===1030)check(integer(input.rows,1,10)&&integer(input.cols,1,10)&&integer(input.rCenter,0,input.rows-1)&&integer(input.cCenter,0,input.cols-1),'Use 1-10 rows and columns with the center inside the matrix.');
  if(id===1037)check(Array.isArray(input.points)&&input.points.length===3&&input.points.every(p=>vector(p,2,2,0,100)),'Use exactly three [x,y] pairs with coordinates from 0 to 100.');
  if(id===1041)check(text(input.instructions,/^[GLR]+$/),'Use 1-120 instructions consisting only of G, L, and R.');
  if(id===1046)check(vector(input.stones,1,30,1,1000),'Use 1-30 positive stone weights at most 1000.');
  if(id===1051)check(vector(input.heights,1,80,1,100),'Use 1-80 heights from 1 through 100.');
  if(id===1052)check(vector(input.customers,1,80,0,1000)&&vector(input.grumpy,1,80,0,1)&&input.customers.length===input.grumpy.length&&integer(input.minutes,1,input.customers.length),'Use matching customer and binary grumpy arrays, and a positive window length no greater than their length.');
  return input;
}
