const specs={568:['flights days','Choose weekly cities to maximize vacation days starting from city zero.','Before each week, stay in the current city or take one direct flight. Keep only the best total for each ending city: every future choice depends on that city, so smaller totals at the same city can be discarded.','start with only city zero reachable before week zero|create a fresh unreachable score for every city each week|try staying or one direct flight from each reachable city|keep the largest total for each destination city|return the largest total after the final week','O(weeks*cities^2) time; O(cities) score space, excluding visualization snapshots.']};
const solvers={568({flights,days},emit){const n=flights.length,weeks=days[0].length;let scores=Array(n).fill(-Infinity);scores[0]=0;for(let week=0;week<weeks;week++){const next=Array(n).fill(-Infinity),origins=Array(n).fill(null);for(let from=0;from<n;from++){if(!Number.isFinite(scores[from]))continue;for(let to=0;to<n;to++){if(from!==to&&!flights[from][to])continue;const candidate=scores[from]+days[to][week],improves=candidate>next[to];if(improves){next[to]=candidate;origins[to]=from;}emit(improves?'This allowed weekly move improves the best total ending in its destination. Future weeks need only that city and its best total.':'This allowed move reaches the same destination with no better total. Its future options are identical, so discard the weaker history.',{matrix:flights,matrixLabel:'Direct flights (staying is always allowed)',cell:[from,to],outputMatrix:days,outputMatrixLabel:'Vacation days by city and week',outputCell:[to,week],table:next.map((v,city)=>[city,Number.isFinite(scores[city])?scores[city]:'unreachable',Number.isFinite(v)?v:'unreachable',origins[city]??'—']),tableHeaders:['City','Previous week best','This week best','Best incoming city'],codeStage:'transition',metrics:{week:week+1,from,to,daysEarned:days[to][week],candidate,improves}},'update');}}scores=next;emit('Commit the completed week together. A fresh score array prevents taking multiple flights during one week.',{matrix:flights,output:[...scores].map(v=>Number.isFinite(v)?v:'unreachable'),codeStage:'week',metrics:{completedWeeks:week+1,best:Math.max(...scores)}},'update');}return Math.max(...scores);}};
const python={568:`def maxVacationDays(flights, days):
    cities, weeks = len(flights), len(days[0])
    scores = [float('-inf')] * cities
    scores[0] = 0
    for week in range(weeks):
        following = [float('-inf')] * cities
        for origin in range(cities):
            if scores[origin] == float('-inf'):
                continue
            for destination in range(cities):
                if origin == destination or flights[origin][destination]:
                    following[destination] = max(  # step: transition
                        following[destination],
                        scores[origin] + days[destination][week])
        scores = following  # step: week
    return max(scores)  # step: return`};
const cases={568:[['A connected itinerary trades early rewards for better later cities',{flights:[[0,1,0,0],[0,0,1,0],[1,0,0,1],[0,1,0,0]],days:[[3,2,6,1,4,2],[6,1,2,5,1,4],[1,7,1,3,7,2],[2,2,7,1,2,7]]}],['Rich unreachable cities cannot contribute vacation days',{flights:[[0,0,0],[0,0,1],[0,1,0]],days:[[1,2,3,2],[7,7,7,7],[6,6,6,6]]}],['One city means staying every week',{flights:[[0]],days:[[2,0,7,4,1,6]]}],['A two-flight chain cannot be completed in a single week',{flights:[[0,1,0],[0,0,1],[0,0,0]],days:[[2],[4],[7]]}]]};
function validate(id,input){const {flights,days}=input,need=(ok,message)=>{if(!ok)throw new Error(message);};need(Array.isArray(flights)&&flights.length>=1&&flights.length<=8&&flights.every((row,r)=>Array.isArray(row)&&row.length===flights.length&&row.every((v,c)=>(v===0||v===1)&&(r!==c||v===0))),'Use a square binary flight matrix for 1-8 cities, with zero diagonal.');need(Array.isArray(days)&&days.length===flights.length&&Array.isArray(days[0])&&days[0].length>=1&&days[0].length<=12&&days.every(row=>Array.isArray(row)&&row.length===days[0].length&&row.every(v=>Number.isInteger(v)&&v>=0&&v<=7)),'Supply 1-12 weeks for every city, each with 0-7 vacation days.');return input;}
export default {specs,solvers,python,cases,validate,pseudocodeStages:{568:{transition:4,week:2}},tags:{568:['Dynamic Programming','Matrix']}};
