// Generated by npm run build:definition-groups; edit the source batch instead.
import { createDefinitions } from '../createDefinitions.js';
import examples0 from '../../../../config/examples/collection--510.js';
import batch from '../parentSuccessorBatch.js';

export const definitions = createDefinitions({
  authoredSpecs: {"510":["root target","Find the inorder successor of a BST node using its child and parent links.","If a right subtree exists, its leftmost node is next. Otherwise climb past ancestors reached from their right child; the first ancestor reached from its left child is the next larger node.","locate the target and attach parent links while decoding the tree|if the target has a right child enter that subtree|follow left children to its smallest node|otherwise climb while the current node is a right child|return the first left-side ancestor or null","O(h) successor search with O(1) auxiliary space; O(n) JSON tree decoding."]},
  authoredPython: {"510":"class Node:\n    def __init__(self, value, parent=None):\n        self.val, self.parent = value, parent\n        self.left = self.right = None\n\ndef inorderSuccessor(root, target):\n    from collections import deque\n    tree = Node(root[0])\n    queue, index, selected = deque([tree]), 1, None\n    while queue:\n        node = queue.popleft()\n        if node.val == target:\n            selected = node\n        for side in ('left', 'right'):\n            if index < len(root):\n                value = root[index]\n                index += 1\n                if value is not None:\n                    child = Node(value, node)\n                    setattr(node, side, child)\n                    queue.append(child)\n    node = selected\n    if node.right:\n        node = node.right  # step: right\n        while node.left:\n            node = node.left  # step: left\n        return node.val  # step: found\n    while node.parent and node.parent.right is node:\n        node = node.parent  # step: climb\n    return node.parent.val if node.parent else None  # step: return"},
  authoredPythonStages: {"510":{"right":24,"left":26,"found":27,"climb":29,"return":30}},
  authoredPseudocodeStages: {"510":{"right":2,"left":3,"climb":4,"found":5}},
  specs: {"510":["root target","Find the inorder successor of a BST node using its child and parent links.","If a right subtree exists, its leftmost node is next. Otherwise climb past ancestors reached from their right child; the first ancestor reached from its left child is the next larger node.","locate the target and attach parent links while decoding the tree|if the target has a right child enter that subtree|follow left children to its smallest node|otherwise climb while the current node is a right child|return the first left-side ancestor or null","O(h) successor search with O(1) auxiliary space; O(n) JSON tree decoding."]},
  collectionStoryMetadata: {"510":{"number":"510","title":"Inorder Successor in BST II","slug":"inorder-successor-in-bst-ii","difficulty":"Medium","url":"https://leetcode.com/problems/inorder-successor-in-bst-ii/"}},
  collectionStoryExamples: {510: examples0},
  solvers: batch.solvers,
  validateAuthored: batch.validate,
  authoredResultStage: (id,result,input) => batch.resultStage?.(id,result,input) ?? 'return',
  authoredInputState: (id,input) => batch.inputState?.(id,input) ?? {},
  authoredResultState: (id,result) => batch.resultState?.(id,result) ?? {}
});
