// Generated by npm run build:definition-groups; edit the source batch instead.
import { createDefinitions } from '../createDefinitions.js';
import examples0 from '../../../../config/examples/collection--558.js';
import batch from '../quadUnionBatch.js';

export const definitions = createDefinitions({
  authoredSpecs: {"558":["grid1 grid2","Compute logical OR of two compressed binary images and compress the result.","A true leaf makes its entire region true, while a false leaf contributes nothing and can reuse the other subtree. Only two mixed regions require four recursive comparisons. Equal result leaves collapse back into one leaf.","decode both binary images into compressed quad trees|short circuit when either region is a true leaf|reuse the other region when one is a false leaf|otherwise combine four matching quadrants and collapse equal leaves|return the compressed OR tree","O(n^2) input decoding; O(number of visited quad-tree nodes) OR time; O(n^2) representation space."]},
  authoredPython: {"558":"def intersect(grid1, grid2):\n    def leaf(value):\n        return {'isLeaf': True, 'val': bool(value), 'children': []}\n    def compress(children):\n        if all(child['isLeaf'] and child['val'] == children[0]['val'] for child in children):\n            return leaf(children[0]['val'])\n        return {'isLeaf': False, 'val': True, 'children': children}\n    def build(grid, row, col, size):\n        if size == 1:\n            return leaf(grid[row][col])\n        half = size // 2\n        return compress([build(grid, r, c, half) for r, c in (\n            (row, col), (row, col + half),\n            (row + half, col), (row + half, col + half))])\n    def merge(first, second):\n        if (first['isLeaf'] and first['val']) or (second['isLeaf'] and second['val']):\n            return leaf(True)  # step: trueLeaf\n        if first['isLeaf']:\n            return second  # step: reuse\n        if second['isLeaf']:\n            return first\n        children = [merge(a, b) for a, b in zip(first['children'], second['children'])]\n        return compress(children)  # step: combine\n    size = len(grid1)\n    return merge(build(grid1, 0, 0, size), build(grid2, 0, 0, size))  # step: return"},
  authoredPythonStages: {"558":{"trueLeaf":17,"reuse":19,"combine":23,"return":25}},
  authoredPseudocodeStages: {"558":{"trueLeaf":2,"reuse":3,"combine":4}},
  specs: {"558":["grid1 grid2","Compute logical OR of two compressed binary images and compress the result.","A true leaf makes its entire region true, while a false leaf contributes nothing and can reuse the other subtree. Only two mixed regions require four recursive comparisons. Equal result leaves collapse back into one leaf.","decode both binary images into compressed quad trees|short circuit when either region is a true leaf|reuse the other region when one is a false leaf|otherwise combine four matching quadrants and collapse equal leaves|return the compressed OR tree","O(n^2) input decoding; O(number of visited quad-tree nodes) OR time; O(n^2) representation space."]},
  collectionStoryMetadata: {"558":{"number":"558","title":"Logical OR of Two Binary Grids Represented as Quad-Trees","slug":"logical-or-of-two-binary-grids-represented-as-quad-trees","difficulty":"Medium","url":"https://leetcode.com/problems/logical-or-of-two-binary-grids-represented-as-quad-trees/"}},
  collectionStoryExamples: {558: examples0},
  solvers: batch.solvers,
  validateAuthored: batch.validate,
  authoredResultStage: (id,result,input) => batch.resultStage?.(id,result,input) ?? 'return',
  authoredInputState: (id,input) => batch.inputState?.(id,input) ?? {},
  authoredResultState: (id,result) => batch.resultState?.(id,result) ?? {}
});
