// Generated by npm run build:definition-groups; edit the source batch instead.
import { createDefinitions } from '../createDefinitions.js';
import examples0 from '../../../../config/examples/collection--568.js';
import batch from '../vacationPlanningBatch.js';

export const definitions = createDefinitions({
  authoredSpecs: {"568":["flights days","Choose weekly cities to maximize vacation days starting from city zero.","Before each week, stay in the current city or take one direct flight. Keep only the best total for each ending city: every future choice depends on that city, so smaller totals at the same city can be discarded.","start with only city zero reachable before week zero|create a fresh unreachable score for every city each week|try staying or one direct flight from each reachable city|keep the largest total for each destination city|return the largest total after the final week","O(weeks*cities^2) time; O(cities) score space, excluding visualization snapshots."]},
  authoredPython: {"568":"def maxVacationDays(flights, days):\n    cities, weeks = len(flights), len(days[0])\n    scores = [float('-inf')] * cities\n    scores[0] = 0\n    for week in range(weeks):\n        following = [float('-inf')] * cities\n        for origin in range(cities):\n            if scores[origin] == float('-inf'):\n                continue\n            for destination in range(cities):\n                if origin == destination or flights[origin][destination]:\n                    following[destination] = max(  # step: transition\n                        following[destination],\n                        scores[origin] + days[destination][week])\n        scores = following  # step: week\n    return max(scores)  # step: return"},
  authoredPythonStages: {"568":{"transition":12,"week":15,"return":16}},
  authoredPseudocodeStages: {"568":{"transition":4,"week":2}},
  specs: {"568":["flights days","Choose weekly cities to maximize vacation days starting from city zero.","Before each week, stay in the current city or take one direct flight. Keep only the best total for each ending city: every future choice depends on that city, so smaller totals at the same city can be discarded.","start with only city zero reachable before week zero|create a fresh unreachable score for every city each week|try staying or one direct flight from each reachable city|keep the largest total for each destination city|return the largest total after the final week","O(weeks*cities^2) time; O(cities) score space, excluding visualization snapshots."]},
  collectionStoryMetadata: {"568":{"number":"568","title":"Maximum Vacation Days","slug":"maximum-vacation-days","difficulty":"Hard","url":"https://leetcode.com/problems/maximum-vacation-days/"}},
  collectionStoryExamples: {568: examples0},
  solvers: batch.solvers,
  validateAuthored: batch.validate,
  authoredResultStage: (id,result,input) => batch.resultStage?.(id,result,input) ?? 'return',
  authoredInputState: (id,input) => batch.inputState?.(id,input) ?? {},
  authoredResultState: (id,result) => batch.resultState?.(id,result) ?? {}
});
